package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelTransportWa
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer Butt;
    private final ModelRenderer Head;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer Cloth03;
    private final ModelRenderer EquipBase;
    private final ModelRenderer Cloth01b;
    private final ModelRenderer Cloth01a;
    private final ModelRenderer Cloth2b;
    private final ModelRenderer Cloth2a;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer LegRight02;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer ClothLeg;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer EquipHeadBase;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairU01;
    private final ModelRenderer Hair01;
    private final ModelRenderer ClothHead;
    private final ModelRenderer EquipHead01;
    private final ModelRenderer EquipHead02;
    private final ModelRenderer EquipHead03;
    private final ModelRenderer EquipHead04;
    private final ModelRenderer EquipHead05;
    private final ModelRenderer EquipHead06;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer Cloth04;
    private final ModelRenderer Cloth00a;
    private final ModelRenderer Cloth00b;
    private final ModelRenderer Cloth00c;
    private final ModelRenderer Cloth00d;
    private final ModelRenderer EquipBack01a;
    private final ModelRenderer EquipBack01b;
    private final ModelRenderer EquipBack01c;
    private final ModelRenderer EquipBack01d;
    private final ModelRenderer EquipBack01e;
    private final ModelRenderer EquipBack01f;
    private final ModelRenderer EquipBack01g;
    private final ModelRenderer EquipBack01h;
    private final ModelRenderer EquipBack01i;
    private final ModelRenderer EquipBack01j;
    private final ModelRenderer EquipBack01k;
    private final ModelRenderer EquipBack01l;
    private final ModelRenderer EquipBack01m;
    private final ModelRenderer EquipBack01n;
    private final ModelRenderer EquipBack01o;
    private final ModelRenderer EquipBack01p;
    private final ModelRenderer EquipBack01q;
    private final ModelRenderer EquipBack01r;
    private final ModelRenderer EquipTubeR01;
    private final ModelRenderer EquipTubeL01;
    private final ModelRenderer EquipBack01s;
    private final ModelRenderer EquipBack01t;
    private final ModelRenderer EquipBack01u;
    private final ModelRenderer EquipBack01v;
    private final ModelRenderer EquipBack01w;
    private final ModelRenderer EquipBack01x;
    private final ModelRenderer EquipBack01y;
    private final ModelRenderer EquipBack01z;
    private final ModelRenderer EquipBack01za;
    private final ModelRenderer EquipBack01zb;
    private final ModelRenderer EquipBack01zc;
    private final ModelRenderer EquipBack01zd;
    private final ModelRenderer EquipTubeR02;
    private final ModelRenderer EquipTubeR03;
    private final ModelRenderer EquipTubeL02;
    private final ModelRenderer EquipTubeL03;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowBodyMain2;
    private final ModelRenderer GlowHead;
    private final ModelRenderer GlowEquipBase;
    private final ModelRenderer GlowEquipTubeL01;
    private final ModelRenderer GlowEquipTubeL02;
    private final ModelRenderer GlowEquipTubeR01;
    private final ModelRenderer GlowEquipTubeR02;

    public ModelTransportWa() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.scale = 0.4f;
        this.offsetY = 2.35f;
        this.offsetItem = new float[]{0.06f, 1.05f, -0.06f};
        this.offsetBlock = new float[]{0.06f, 1.05f, -0.06f};
        this.setDefaultFaceModel();
        this.Cloth00b = new ModelRenderer(this, 19, 79);
        this.Cloth00b.setRotationPoint(0.0f, 0.5f, 3.3f);
        this.Cloth00b.addBox(-7.0f, -2.0f, 0.0f, 7, 4, 2, 0.0f);
        this.setRotateAngle(this.Cloth00b, -0.20943952f, 0.2617994f, 0.17453292f);
        this.EquipBack01t = new ModelRenderer(this, 0, 0);
        this.EquipBack01t.mirror = true;
        this.EquipBack01t.setRotationPoint(0.0f, -10.0f, 32.0f);
        this.EquipBack01t.addBox(0.0f, 0.0f, 0.0f, 10, 10, 6, 0.0f);
        this.EquipBack01m = new ModelRenderer(this, 21, 6);
        this.EquipBack01m.setRotationPoint(16.0f, -10.0f, 16.0f);
        this.EquipBack01m.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipHeadBase = new ModelRenderer(this, 0, 0);
        this.EquipHeadBase.setRotationPoint(0.0f, -13.8f, 0.0f);
        this.EquipHeadBase.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.EquipBack01v = new ModelRenderer(this, 0, 0);
        this.EquipBack01v.setRotationPoint(-10.0f, 0.0f, 32.0f);
        this.EquipBack01v.addBox(0.0f, 0.0f, 0.0f, 10, 10, 6, 0.0f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -11.8f, -1.0f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.setRotateAngle(this.Head, 0.10471976f, 0.0f, 0.0f);
        this.HairU01 = new ModelRenderer(this, 50, 45);
        this.HairU01.setRotationPoint(0.0f, -6.0f, -6.5f);
        this.HairU01.addBox(-8.5f, 0.0f, 0.0f, 17, 14, 7, 0.0f);
        this.BodyMain = new ModelRenderer(this, 0, 105);
        this.BodyMain.setRotationPoint(0.0f, -11.0f, -3.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 16, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.10471976f, 0.0f, 0.0f);
        this.Cloth01b = new ModelRenderer(this, 96, 19);
        this.Cloth01b.mirror = true;
        this.Cloth01b.setRotationPoint(-5.6f, -11.6f, -0.6f);
        this.Cloth01b.addBox(-4.0f, 0.0f, -4.0f, 8, 14, 8, 0.0f);
        this.setRotateAngle(this.Cloth01b, (float)Math.PI / 90, 0.0f, -0.08726646f);
        this.EquipBack01j = new ModelRenderer(this, 0, 0);
        this.EquipBack01j.setRotationPoint(-16.0f, -16.0f, 16.0f);
        this.EquipBack01j.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipBack01q = new ModelRenderer(this, 0, 0);
        this.EquipBack01q.mirror = true;
        this.EquipBack01q.setRotationPoint(-22.0f, 0.0f, 16.0f);
        this.EquipBack01q.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipBack01x = new ModelRenderer(this, 0, 0);
        this.EquipBack01x.mirror = true;
        this.EquipBack01x.setRotationPoint(0.0f, -22.0f, 16.0f);
        this.EquipBack01x.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.EquipBack01zb = new ModelRenderer(this, 0, 14);
        this.EquipBack01zb.mirror = true;
        this.EquipBack01zb.setRotationPoint(-10.0f, 16.0f, 6.0f);
        this.EquipBack01zb.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.LegRight02 = new ModelRenderer(this, 0, 83);
        this.LegRight02.setRotationPoint(3.0f, 12.0f, -3.0f);
        this.LegRight02.addBox(-6.0f, 0.0f, 0.0f, 6, 13, 6, 0.0f);
        this.EquipBack01n = new ModelRenderer(this, 0, 0);
        this.EquipBack01n.setRotationPoint(16.0f, 0.0f, 16.0f);
        this.EquipBack01n.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipBack01a = new ModelRenderer(this, 0, 0);
        this.EquipBack01a.setRotationPoint(0.0f, -16.0f, 0.0f);
        this.EquipBack01a.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipBack01p = new ModelRenderer(this, 7, 6);
        this.EquipBack01p.setRotationPoint(-22.0f, -10.0f, 6.0f);
        this.EquipBack01p.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipBack01i = new ModelRenderer(this, 0, 0);
        this.EquipBack01i.mirror = true;
        this.EquipBack01i.setRotationPoint(-16.0f, 0.0f, 16.0f);
        this.EquipBack01i.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipBack01d = new ModelRenderer(this, 0, 0);
        this.EquipBack01d.mirror = true;
        this.EquipBack01d.setRotationPoint(-16.0f, 0.0f, 0.0f);
        this.EquipBack01d.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipBack01w = new ModelRenderer(this, 0, 0);
        this.EquipBack01w.mirror = true;
        this.EquipBack01w.setRotationPoint(0.0f, -22.0f, 6.0f);
        this.EquipBack01w.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.Hair01 = new ModelRenderer(this, 0, 32);
        this.Hair01.setRotationPoint(0.0f, 7.2f, 1.1f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 9, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.08726646f, 0.0f, 0.0f);
        this.ArmLeft02 = new ModelRenderer(this, 2, 84);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(3.0f, 10.0f, 2.5f);
        this.ArmLeft02.addBox(-5.0f, 0.0f, -5.0f, 5, 11, 5, 0.0f);
        this.EquipBack01o = new ModelRenderer(this, 26, 12);
        this.EquipBack01o.setRotationPoint(-22.0f, 0.0f, 6.0f);
        this.EquipBack01o.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipHead03 = new ModelRenderer(this, 0, 0);
        this.EquipHead03.setRotationPoint(0.0f, -4.3f, -7.0f);
        this.EquipHead03.addBox(-8.0f, 0.0f, -9.0f, 16, 10, 16, 0.0f);
        this.setRotateAngle(this.EquipHead03, 0.2617994f, 0.0f, 0.0f);
        this.EquipTubeL02 = new ModelRenderer(this, 12, 0);
        this.EquipTubeL02.setRotationPoint(0.0f, 16.0f, 4.0f);
        this.EquipTubeL02.addBox(-4.5f, 0.0f, -8.5f, 9, 16, 9, 0.0f);
        this.setRotateAngle(this.EquipTubeL02, -0.95609134f, 0.0f, 0.0f);
        this.Butt = new ModelRenderer(this, 52, 66);
        this.Butt.setRotationPoint(0.0f, 3.0f, 1.3f);
        this.Butt.addBox(-7.5f, 0.0f, -5.7f, 15, 7, 8, 0.0f);
        this.setRotateAngle(this.Butt, 0.31415927f, 0.0f, 0.0f);
        this.LegLeft01 = new ModelRenderer(this, 0, 83);
        this.LegLeft01.mirror = true;
        this.LegLeft01.setRotationPoint(4.4f, 5.5f, -2.6f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 12, 6, 0.0f);
        this.setRotateAngle(this.LegLeft01, -0.2443461f, 0.0f, 0.10471976f);
        this.Cloth01a = new ModelRenderer(this, 96, 19);
        this.Cloth01a.setRotationPoint(5.6f, -11.6f, -0.6f);
        this.Cloth01a.addBox(-4.0f, 0.0f, -4.0f, 8, 14, 8, 0.0f);
        this.setRotateAngle(this.Cloth01a, (float)Math.PI / 90, 0.0f, 0.08726646f);
        this.Cloth04 = new ModelRenderer(this, 70, 21);
        this.Cloth04.setRotationPoint(0.0f, 2.5f, -4.7f);
        this.Cloth04.addBox(-6.5f, 0.0f, 0.0f, 13, 11, 0, 0.0f);
        this.setRotateAngle(this.Cloth04, -0.20943952f, 0.0f, -0.08726646f);
        this.EquipTubeR01 = new ModelRenderer(this, 0, 0);
        this.EquipTubeR01.setRotationPoint(-18.0f, 3.0f, 28.0f);
        this.EquipTubeR01.addBox(-4.0f, 0.0f, -4.0f, 8, 16, 8, 0.0f);
        this.setRotateAngle(this.EquipTubeR01, -0.34906584f, 0.13962634f, 0.13962634f);
        this.LegRight01 = new ModelRenderer(this, 0, 83);
        this.LegRight01.setRotationPoint(-4.4f, 5.5f, -2.6f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 12, 6, 0.0f);
        this.setRotateAngle(this.LegRight01, -0.13962634f, 0.0f, -0.10471976f);
        this.EquipBack01g = new ModelRenderer(this, 0, 0);
        this.EquipBack01g.setRotationPoint(0.0f, 0.0f, 16.0f);
        this.EquipBack01g.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipHead04 = new ModelRenderer(this, 0, 0);
        this.EquipHead04.setRotationPoint(0.0f, -5.2f, -2.8f);
        this.EquipHead04.addBox(0.0f, 0.0f, 0.0f, 16, 9, 16, 0.0f);
        this.setRotateAngle(this.EquipHead04, -0.5009095f, -0.7213446f, 0.34487706f);
        this.EquipTubeL01 = new ModelRenderer(this, 0, 0);
        this.EquipTubeL01.setRotationPoint(18.0f, 3.0f, 28.0f);
        this.EquipTubeL01.addBox(-4.0f, 0.0f, -4.0f, 8, 16, 8, 0.0f);
        this.setRotateAngle(this.EquipTubeL01, -0.34906584f, -0.13962634f, -0.13962634f);
        this.EquipBase = new ModelRenderer(this, 0, 0);
        this.EquipBase.setRotationPoint(0.0f, -4.5f, 7.5f);
        this.EquipBase.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipBase, 0.05235988f, 0.0f, 0.0f);
        this.EquipBack01zc = new ModelRenderer(this, 7, 13);
        this.EquipBack01zc.mirror = true;
        this.EquipBack01zc.setRotationPoint(-10.0f, 16.0f, 16.0f);
        this.EquipBack01zc.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.Cloth00d = new ModelRenderer(this, 88, 101);
        this.Cloth00d.setRotationPoint(-0.8f, 1.0f, 4.5f);
        this.Cloth00d.addBox(-2.5f, 0.0f, 0.0f, 5, 12, 0, 0.0f);
        this.setRotateAngle(this.Cloth00d, 0.34906584f, -0.13962634f, 0.31415927f);
        this.LegLeft02 = new ModelRenderer(this, 0, 83);
        this.LegLeft02.mirror = true;
        this.LegLeft02.setRotationPoint(-3.0f, 12.0f, -3.0f);
        this.LegLeft02.addBox(0.0f, 0.0f, 0.0f, 6, 13, 6, 0.0f);
        this.EquipBack01b = new ModelRenderer(this, 0, 0);
        this.EquipBack01b.mirror = true;
        this.EquipBack01b.setRotationPoint(-16.0f, -16.0f, 0.0f);
        this.EquipBack01b.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipTubeL03 = new ModelRenderer(this, 92, 0);
        this.EquipTubeL03.setRotationPoint(0.0f, 16.1f, -4.0f);
        this.EquipTubeL03.addBox(-4.5f, 0.0f, -4.5f, 9, 3, 9, 0.0f);
        this.EquipBack01e = new ModelRenderer(this, 0, 0);
        this.EquipBack01e.mirror = true;
        this.EquipBack01e.setRotationPoint(-10.0f, -6.0f, -4.0f);
        this.EquipBack01e.addBox(0.0f, 0.0f, 0.0f, 10, 16, 4, 0.0f);
        this.EquipTubeR03 = new ModelRenderer(this, 92, 0);
        this.EquipTubeR03.setRotationPoint(0.0f, 16.1f, -4.0f);
        this.EquipTubeR03.addBox(-4.5f, 0.0f, -4.5f, 9, 3, 9, 0.0f);
        this.EquipBack01h = new ModelRenderer(this, 0, 0);
        this.EquipBack01h.mirror = true;
        this.EquipBack01h.setRotationPoint(0.0f, -16.0f, 16.0f);
        this.EquipBack01h.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.EquipBack01s = new ModelRenderer(this, 0, 0);
        this.EquipBack01s.mirror = true;
        this.EquipBack01s.setRotationPoint(0.0f, 0.0f, 32.0f);
        this.EquipBack01s.addBox(0.0f, 0.0f, 0.0f, 10, 10, 6, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 2, 84);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(7.8f, -9.7f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 11, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, 0.0f, 0.0f, -0.20943952f);
        this.Cloth03 = new ModelRenderer(this, 58, 32);
        this.Cloth03.setRotationPoint(0.2f, 1.3f, -0.5f);
        this.Cloth03.addBox(-7.0f, 0.0f, -4.7f, 14, 4, 9, 0.0f);
        this.setRotateAngle(this.Cloth03, 0.17453292f, 0.0f, 0.08726646f);
        this.Cloth00a = new ModelRenderer(this, 19, 79);
        this.Cloth00a.mirror = true;
        this.Cloth00a.setRotationPoint(0.5f, 0.5f, 3.5f);
        this.Cloth00a.addBox(0.0f, -2.0f, 0.0f, 7, 4, 2, 0.0f);
        this.setRotateAngle(this.Cloth00a, -0.091106184f, -0.2617994f, -0.17453292f);
        this.EquipBack01r = new ModelRenderer(this, 0, 0);
        this.EquipBack01r.mirror = true;
        this.EquipBack01r.setRotationPoint(-22.0f, -10.0f, 16.0f);
        this.EquipBack01r.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipHead05 = new ModelRenderer(this, 0, 63);
        this.EquipHead05.setRotationPoint(0.0f, 7.3f, -12.0f);
        this.EquipHead05.addBox(-7.0f, 0.0f, 0.0f, 14, 5, 6, 0.0f);
        this.setRotateAngle(this.EquipHead05, 0.31415927f, 0.0f, 0.0f);
        this.ClothHead = new ModelRenderer(this, 48, 0);
        this.ClothHead.setRotationPoint(0.0f, -1.1f, 1.5f);
        this.ClothHead.addBox(-8.0f, 0.0f, 0.0f, 16, 10, 6, 0.0f);
        this.setRotateAngle(this.ClothHead, -0.06981317f, 0.0f, 0.0f);
        this.EquipHead06 = new ModelRenderer(this, 0, 0);
        this.EquipHead06.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipHead06.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.EquipBack01f = new ModelRenderer(this, 0, 0);
        this.EquipBack01f.setRotationPoint(0.0f, -6.0f, -4.0f);
        this.EquipBack01f.addBox(0.0f, 0.0f, 0.0f, 10, 16, 4, 0.0f);
        this.ClothLeg = new ModelRenderer(this, 30, 78);
        this.ClothLeg.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.ClothLeg.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.EquipBack01k = new ModelRenderer(this, 0, 0);
        this.EquipBack01k.mirror = true;
        this.EquipBack01k.setRotationPoint(16.0f, 0.0f, 6.0f);
        this.EquipBack01k.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.Ahoke = new ModelRenderer(this, 104, 29);
        this.Ahoke.setRotationPoint(0.0f, -7.0f, -4.5f);
        this.Ahoke.addBox(0.0f, -12.0f, -6.5f, 0, 12, 12, 0.0f);
        this.setRotateAngle(this.Ahoke, 1.2f, 0.6981317f, 0.0f);
        this.EquipBack01l = new ModelRenderer(this, 0, 11);
        this.EquipBack01l.mirror = true;
        this.EquipBack01l.setRotationPoint(16.0f, -10.0f, 6.0f);
        this.EquipBack01l.addBox(0.0f, 0.0f, 0.0f, 6, 10, 10, 0.0f);
        this.EquipHead02 = new ModelRenderer(this, 0, 0);
        this.EquipHead02.setRotationPoint(-4.0f, -3.0f, -12.0f);
        this.EquipHead02.addBox(-15.0f, 0.0f, 0.0f, 15, 9, 16, 0.0f);
        this.setRotateAngle(this.EquipHead02, 0.0f, 0.34906584f, -0.20943952f);
        this.ArmRight01 = new ModelRenderer(this, 2, 84);
        this.ArmRight01.setRotationPoint(-7.8f, -9.7f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 11, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, 0.20943952f, 0.0f, 0.20943952f);
        this.EquipBack01za = new ModelRenderer(this, 0, 16);
        this.EquipBack01za.setRotationPoint(0.0f, 16.0f, 6.0f);
        this.EquipBack01za.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.HairMain = new ModelRenderer(this, 47, 104);
        this.HairMain.setRotationPoint(0.0f, -14.8f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 11, 10, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 2, 84);
        this.ArmRight02.setRotationPoint(-3.0f, 10.0f, 2.5f);
        this.ArmRight02.addBox(0.0f, 0.0f, -5.0f, 5, 11, 5, 0.0f);
        this.EquipTubeR02 = new ModelRenderer(this, 10, 0);
        this.EquipTubeR02.setRotationPoint(0.0f, 16.0f, 4.0f);
        this.EquipTubeR02.addBox(-4.5f, 0.0f, -8.5f, 9, 16, 9, 0.0f);
        this.setRotateAngle(this.EquipTubeR02, -0.95609134f, 0.0f, 0.0f);
        this.BoobR = new ModelRenderer(this, 33, 101);
        this.BoobR.setRotationPoint(-4.1f, -8.5f, -3.7f);
        this.BoobR.addBox(-3.0f, 0.0f, 0.0f, 6, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobR, -0.6981317f, -0.0785f, -0.0785f);
        this.BoobL = new ModelRenderer(this, 33, 101);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(4.1f, -8.5f, -3.7f);
        this.BoobL.addBox(-3.0f, 0.0f, 0.0f, 6, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobL, -0.6981317f, 0.0785f, 0.0785f);
        this.Cloth2a = new ModelRenderer(this, 26, 89);
        this.Cloth2a.setRotationPoint(-1.2f, -0.5f, -0.7f);
        this.Cloth2a.addBox(0.0f, 0.0f, 0.0f, 5, 6, 6, 0.0f);
        this.setRotateAngle(this.Cloth2a, 0.0f, -0.0785f, -0.0785f);
        this.Cloth2b = new ModelRenderer(this, 26, 89);
        this.Cloth2b.mirror = true;
        this.Cloth2b.setRotationPoint(1.2f, -0.5f, -0.7f);
        this.Cloth2b.addBox(-5.0f, 0.0f, 0.0f, 5, 6, 6, 0.0f);
        this.setRotateAngle(this.Cloth2b, 0.0f, 0.0785f, 0.0785f);
        this.Cloth00c = new ModelRenderer(this, 88, 101);
        this.Cloth00c.mirror = true;
        this.Cloth00c.setRotationPoint(1.3f, 1.0f, 4.5f);
        this.Cloth00c.addBox(-2.5f, 0.0f, 0.0f, 5, 12, 0, 0.0f);
        this.setRotateAngle(this.Cloth00c, 0.31415927f, 0.13962634f, -0.34906584f);
        this.Hair = new ModelRenderer(this, 50, 81);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.4f);
        this.Hair.addBox(-8.0f, -8.0f, -7.4f, 16, 12, 8, 0.0f);
        this.EquipHead01 = new ModelRenderer(this, 0, 0);
        this.EquipHead01.setRotationPoint(4.0f, -3.0f, -12.0f);
        this.EquipHead01.addBox(0.0f, 0.0f, 0.0f, 15, 9, 16, 0.0f);
        this.setRotateAngle(this.EquipHead01, 0.0f, -0.34906584f, 0.20943952f);
        this.EquipBack01z = new ModelRenderer(this, 0, 0);
        this.EquipBack01z.setRotationPoint(-10.0f, -22.0f, 6.0f);
        this.EquipBack01z.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.EquipBack01zd = new ModelRenderer(this, 0, 6);
        this.EquipBack01zd.setRotationPoint(0.0f, 16.0f, 16.0f);
        this.EquipBack01zd.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.EquipBack01u = new ModelRenderer(this, 0, 0);
        this.EquipBack01u.setRotationPoint(-10.0f, -10.0f, 32.0f);
        this.EquipBack01u.addBox(0.0f, 0.0f, 0.0f, 10, 10, 6, 0.0f);
        this.EquipBack01y = new ModelRenderer(this, 0, 0);
        this.EquipBack01y.setRotationPoint(-10.0f, -22.0f, 16.0f);
        this.EquipBack01y.addBox(0.0f, 0.0f, 0.0f, 10, 6, 10, 0.0f);
        this.EquipBack01c = new ModelRenderer(this, 0, 0);
        this.EquipBack01c.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipBack01c.addBox(0.0f, 0.0f, 0.0f, 16, 16, 16, 0.0f);
        this.Cloth03.addChild(this.Cloth00b);
        this.EquipBase.addChild(this.EquipBack01t);
        this.EquipBase.addChild(this.EquipBack01m);
        this.Head.addChild(this.EquipHeadBase);
        this.EquipBase.addChild(this.EquipBack01v);
        this.BodyMain.addChild(this.Head);
        this.Hair.addChild(this.HairU01);
        this.BodyMain.addChild(this.Cloth01b);
        this.EquipBase.addChild(this.EquipBack01j);
        this.EquipBase.addChild(this.EquipBack01q);
        this.EquipBase.addChild(this.EquipBack01x);
        this.EquipBase.addChild(this.EquipBack01zb);
        this.LegRight01.addChild(this.LegRight02);
        this.EquipBase.addChild(this.EquipBack01n);
        this.EquipBase.addChild(this.EquipBack01a);
        this.EquipBase.addChild(this.EquipBack01p);
        this.EquipBase.addChild(this.EquipBack01i);
        this.EquipBase.addChild(this.EquipBack01d);
        this.EquipBase.addChild(this.EquipBack01w);
        this.HairMain.addChild(this.Hair01);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.EquipBase.addChild(this.EquipBack01o);
        this.EquipHeadBase.addChild(this.EquipHead03);
        this.EquipTubeL01.addChild(this.EquipTubeL02);
        this.BodyMain.addChild(this.Butt);
        this.Butt.addChild(this.LegLeft01);
        this.BodyMain.addChild(this.Cloth01a);
        this.Cloth03.addChild(this.Cloth04);
        this.EquipBase.addChild(this.EquipTubeR01);
        this.Butt.addChild(this.LegRight01);
        this.EquipBase.addChild(this.EquipBack01g);
        this.EquipHeadBase.addChild(this.EquipHead04);
        this.EquipBase.addChild(this.EquipTubeL01);
        this.BoobL.addChild(this.Cloth2a);
        this.BodyMain.addChild(this.EquipBase);
        this.EquipBase.addChild(this.EquipBack01zc);
        this.Cloth03.addChild(this.Cloth00d);
        this.LegLeft01.addChild(this.LegLeft02);
        this.EquipBase.addChild(this.EquipBack01b);
        this.EquipBase.addChild(this.EquipBack01e);
        this.EquipBase.addChild(this.EquipBack01h);
        this.EquipBase.addChild(this.EquipBack01s);
        this.BodyMain.addChild(this.ArmLeft01);
        this.BodyMain.addChild(this.Cloth03);
        this.Cloth03.addChild(this.Cloth00a);
        this.EquipBase.addChild(this.EquipBack01r);
        this.BodyMain.addChild(this.BoobL);
        this.EquipHeadBase.addChild(this.EquipHead05);
        this.HairMain.addChild(this.ClothHead);
        this.EquipHeadBase.addChild(this.EquipHead06);
        this.EquipBase.addChild(this.EquipBack01f);
        this.LegLeft01.addChild(this.ClothLeg);
        this.EquipBase.addChild(this.EquipBack01k);
        this.Hair.addChild(this.Ahoke);
        this.EquipBase.addChild(this.EquipBack01l);
        this.EquipHeadBase.addChild(this.EquipHead02);
        this.BodyMain.addChild(this.ArmRight01);
        this.EquipBase.addChild(this.EquipBack01za);
        this.Head.addChild(this.HairMain);
        this.ArmRight01.addChild(this.ArmRight02);
        this.EquipTubeR01.addChild(this.EquipTubeR02);
        this.BodyMain.addChild(this.BoobR);
        this.BoobR.addChild(this.Cloth2b);
        this.Cloth03.addChild(this.Cloth00c);
        this.Head.addChild(this.Hair);
        this.EquipHeadBase.addChild(this.EquipHead01);
        this.EquipBase.addChild(this.EquipBack01z);
        this.EquipBase.addChild(this.EquipBack01zd);
        this.EquipBase.addChild(this.EquipBack01u);
        this.EquipBase.addChild(this.EquipBack01y);
        this.EquipBase.addChild(this.EquipBack01c);
        this.GlowBodyMain = new ModelRenderer(this, 0, 105);
        this.GlowBodyMain.setRotationPoint(0.0f, -11.0f, -3.0f);
        this.GlowBodyMain2 = new ModelRenderer(this, 0, 105);
        this.GlowBodyMain2.setRotationPoint(0.0f, -11.0f, -3.0f);
        this.GlowHead = new ModelRenderer(this, 44, 101);
        this.GlowHead.setRotationPoint(0.0f, -11.8f, -1.0f);
        this.GlowEquipBase = new ModelRenderer(this, 0, 0);
        this.GlowEquipBase.setRotationPoint(0.0f, -4.5f, 7.5f);
        this.GlowEquipTubeL01 = new ModelRenderer(this, 0, 0);
        this.GlowEquipTubeL01.setRotationPoint(18.0f, 3.0f, 28.0f);
        this.GlowEquipTubeL02 = new ModelRenderer(this, 12, 0);
        this.GlowEquipTubeL02.setRotationPoint(0.0f, 16.0f, 4.0f);
        this.setRotateAngle(this.GlowEquipTubeL02, -0.95609134f, 0.0f, 0.0f);
        this.GlowEquipTubeR01 = new ModelRenderer(this, 0, 0);
        this.GlowEquipTubeR01.setRotationPoint(-18.0f, 3.0f, 28.0f);
        this.GlowEquipTubeR02 = new ModelRenderer(this, 10, 0);
        this.GlowEquipTubeR02.setRotationPoint(0.0f, 16.0f, 4.0f);
        this.setRotateAngle(this.GlowEquipTubeR02, -0.95609134f, 0.0f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.GlowBodyMain2.addChild(this.GlowEquipBase);
        this.GlowEquipBase.addChild(this.GlowEquipTubeL01);
        this.GlowEquipTubeL01.addChild(this.GlowEquipTubeL02);
        this.GlowEquipTubeL02.addChild(this.EquipTubeL03);
        this.GlowEquipBase.addChild(this.GlowEquipTubeR01);
        this.GlowEquipTubeR01.addChild(this.GlowEquipTubeR02);
        this.GlowEquipTubeR02.addChild(this.EquipTubeR03);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        this.GlowBodyMain2.render(f5);
        GlStateManager.enableLighting();
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
        boolean flag;
        int state = ent.getStateEmotion(0);
        this.EquipBase.isHidden = flag = !EmotionHelper.checkModelState(0, state);
        this.GlowEquipBase.isHidden = flag;
        flag = !EmotionHelper.checkModelState(1, state);
        if (flag) {
            this.EquipBase.isHidden = false;
            this.GlowEquipBase.isHidden = false;
            this.LegLeft01.isHidden = true;
            this.LegRight01.isHidden = true;
        } else {
            this.LegLeft01.isHidden = false;
            this.LegRight01.isHidden = false;
        }
        this.EquipHeadBase.isHidden = flag = !EmotionHelper.checkModelState(2, state);
        this.Ahoke.isHidden = !flag;
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowBodyMain2.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain2.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain2.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
        this.GlowEquipBase.rotateAngleX = this.EquipBase.rotateAngleX;
        this.GlowEquipBase.rotateAngleY = this.EquipBase.rotateAngleY;
        this.GlowEquipBase.rotateAngleZ = this.EquipBase.rotateAngleZ;
        this.GlowEquipBase.offsetY = this.EquipBase.offsetY;
        this.GlowEquipBase.offsetZ = this.EquipBase.offsetZ;
        this.GlowEquipTubeL01.rotateAngleX = this.EquipTubeL01.rotateAngleX;
        this.GlowEquipTubeL01.rotateAngleY = this.EquipTubeL01.rotateAngleY;
        this.GlowEquipTubeL01.rotateAngleZ = this.EquipTubeL01.rotateAngleZ;
        this.GlowEquipTubeR01.rotateAngleX = this.EquipTubeR01.rotateAngleX;
        this.GlowEquipTubeR01.rotateAngleY = this.EquipTubeR01.rotateAngleY;
        this.GlowEquipTubeR01.rotateAngleZ = this.EquipTubeR01.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.12f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = 0.3f;
        this.Head.rotateAngleY = 0.0f;
        this.BoobL.rotateAngleX = -0.75f;
        this.BoobR.rotateAngleX = -0.75f;
        this.Ahoke.rotateAngleY = 0.7f;
        this.BodyMain.rotateAngleX = 2.8f;
        this.Cloth03.rotateAngleX = 0.17f;
        this.Cloth04.rotateAngleX = -0.8f;
        this.Butt.rotateAngleX = -1.1f;
        this.Butt.offsetZ = 0.1f;
        this.ArmLeft01.rotateAngleX = -0.35f;
        this.ArmLeft01.rotateAngleZ = -2.6f;
        this.ArmRight01.rotateAngleX = -0.35f;
        this.ArmRight01.rotateAngleZ = 2.6f;
        this.LegLeft01.rotateAngleX = -0.24f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.1047f;
        this.LegRight01.rotateAngleX = -0.14f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.1047f;
        this.EquipBase.isHidden = false;
        this.EquipBase.offsetY = 0.45f;
        this.EquipBase.offsetZ = -0.85f;
        this.EquipBase.rotateAngleX = -3.1f;
        this.EquipTubeL01.rotateAngleX = -0.3f;
        this.EquipTubeR01.rotateAngleX = -0.3f;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float f6;
        boolean hideLeg;
        float angleX = MathHelper.cos(f2 * 0.08f + f * 0.25f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1;
        float addk1;
        float addk2;
        if (ent.getShipDepth(0) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 * 0.5f - 0.24f;
        addk2 = angleAdd2 * 0.5f - 0.14f;
        this.Head.rotateAngleX = f4 * 0.014f + 0.1047f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.BoobL.rotateAngleX = angleX * 0.05f - 0.75f;
        this.BoobR.rotateAngleX = angleX * 0.05f - 0.75f;
        this.Ahoke.rotateAngleY = angleX * 0.25f + 0.7f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.Butt.rotateAngleX = 0.3142f;
        this.Butt.offsetY = 0.0f;
        this.Butt.offsetZ = 0.0f;
        this.Cloth03.rotateAngleX = 0.1745f;
        this.Cloth04.rotateAngleX = angleX * 0.05f - 0.15f;
        this.ArmLeft01.rotateAngleX = angleAdd2 * 0.25f + 0.21f;
        this.ArmLeft01.rotateAngleZ = angleX * 0.03f - 0.21f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.25f + 0.05f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = -angleX * 0.03f + 0.21f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.1047f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.1047f;
        this.EquipBase.rotateAngleX = 0.05236f;
        this.EquipBase.offsetY = 0.0f;
        this.EquipBase.offsetZ = 0.0f;
        this.EquipTubeL01.rotateAngleX = angleX * 0.08f - 0.35f;
        this.EquipTubeR01.rotateAngleX = -angleX * 0.08f - 0.35f;
        hideLeg = !EmotionHelper.checkModelState(1, ent.getStateEmotion(0));
        if (hideLeg) {
            this.Cloth04.rotateAngleX += 0.23f;
            this.Butt.rotateAngleX = 0.7f;
            this.Butt.offsetY = -0.1f;
            this.Butt.offsetZ = -0.05f;
            this.ArmLeft01.rotateAngleX += 0.2f;
            this.ArmLeft01.rotateAngleZ -= 0.3f;
            this.ArmRight01.rotateAngleX += 0.2f;
            this.ArmRight01.rotateAngleZ += 0.3f;
            this.EquipBase.rotateAngleX = -0.4f;
            this.EquipTubeL01.rotateAngleX += 0.35f;
            this.EquipTubeR01.rotateAngleX += 0.35f;
        }
        if (ent.getIsSprinting() || f1 > 0.9f) {
            this.Head.rotateAngleX = (float)(this.Head.rotateAngleX - 0.2);
            this.BodyMain.rotateAngleX = 0.35f;
            this.Cloth04.rotateAngleX -= 0.4f;
            this.ArmLeft01.rotateAngleZ -= 0.2f + f1 * 0.25f;
            this.ArmRight01.rotateAngleZ += 0.2f + f1 * 0.25f;
            addk1 -= 0.45f;
            addk2 -= 0.45f;
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.05f, 0.0f);
            this.Head.rotateAngleX -= 1.0472f;
            this.BodyMain.rotateAngleX = 1.0472f;
            this.Butt.rotateAngleX = hideLeg ? 0.8f : -0.8378f;
            this.Cloth03.rotateAngleX -= 0.7f;
            this.Cloth04.rotateAngleX -= 0.45f;
            this.ArmLeft01.rotateAngleX = -0.7f;
            this.ArmLeft01.rotateAngleZ = 0.2618f;
            this.ArmRight01.rotateAngleX = -0.7f;
            this.ArmRight01.rotateAngleZ = -0.2618f;
        }
        if (ent.getIsSitting() || ent.getIsRiding()) {
            float ax = MathHelper.cos(f2 * 0.5f) * 0.5f;
            if (hideLeg) {
                if (ent.getStateEmotion(1) == 4) {
                    GlStateManager.translate(0.0f, 0.54f, 0.0f);
                    this.setFace(3);
                    this.Head.rotateAngleX = -0.9f;
                    this.Head.rotateAngleY = 0.0f;
                    this.Head.rotateAngleZ = 0.0f;
                    this.Ahoke.rotateAngleY = 0.5236f;
                    this.BodyMain.rotateAngleX = 1.4835f;
                    this.ArmLeft01.rotateAngleX = ax + 0.25f;
                    this.ArmLeft01.rotateAngleZ = -2.3f;
                    this.ArmRight01.rotateAngleX = -ax + 0.25f;
                    this.ArmRight01.rotateAngleZ = 2.3f;
                    this.LegLeft01.rotateAngleY = 0.0f;
                    this.LegLeft01.rotateAngleZ = 0.03f;
                    this.LegRight01.rotateAngleY = 0.0f;
                    this.LegRight01.rotateAngleZ = -0.03f;
                } else {
                    GlStateManager.translate(0.0f, -0.17f, 0.0f);
                    this.setFace(1);
                    this.Head.rotateAngleX = -0.7f;
                    this.Head.rotateAngleY = 0.0f;
                    this.Head.rotateAngleZ = 0.0f;
                    this.Ahoke.rotateAngleY = 0.5236f;
                    this.BodyMain.rotateAngleX = -1.7453f;
                    this.Cloth04.rotateAngleX = 0.4f;
                    this.ArmLeft01.rotateAngleX = 0.85f;
                    this.ArmLeft01.rotateAngleZ = -2.3f;
                    this.ArmRight01.rotateAngleX = 0.85f;
                    this.ArmRight01.rotateAngleZ = 2.3f;
                    this.LegLeft01.rotateAngleY = 0.0f;
                    this.LegLeft01.rotateAngleZ = 0.03f;
                    this.LegRight01.rotateAngleY = 0.0f;
                    this.LegRight01.rotateAngleZ = -0.03f;
                    this.EquipTubeL01.rotateAngleX = 1.3f;
                    this.EquipTubeR01.rotateAngleX = 1.3f;
                }
            } else if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 0.53f, 0.0f);
                this.setFace(3);
                this.Head.rotateAngleX = -0.7f;
                this.Head.rotateAngleY = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                this.Ahoke.rotateAngleY = 0.5236f;
                this.BodyMain.rotateAngleX = 1.4835f;
                this.ArmLeft01.rotateAngleX = ax + 0.25f;
                this.ArmLeft01.rotateAngleZ = -2.3f;
                this.ArmRight01.rotateAngleX = -ax + 0.25f;
                this.ArmRight01.rotateAngleZ = 2.3f;
                addk1 = -ax + 0.2f;
                addk2 = ax + 0.2f;
                this.LegLeft01.rotateAngleY = 0.0f;
                this.LegLeft01.rotateAngleZ = 0.03f;
                this.LegRight01.rotateAngleY = 0.0f;
                this.LegRight01.rotateAngleZ = -0.03f;
            } else {
                GlStateManager.translate(0.0f, 0.42f, 0.0f);
                this.Head.rotateAngleX -= 0.7f;
                this.BodyMain.rotateAngleX = 0.5236f;
                this.ArmLeft01.rotateAngleX = -0.5236f;
                this.ArmLeft01.rotateAngleZ = 0.3146f;
                this.ArmRight01.rotateAngleX = -0.5236f;
                this.ArmRight01.rotateAngleZ = -0.3146f;
                addk1 = -2.2689f;
                addk2 = -2.2689f;
                this.LegLeft01.rotateAngleY = -0.3491f;
                this.LegRight01.rotateAngleY = 0.3491f;
                this.EquipBase.rotateAngleX = -0.4f;
                this.EquipTubeL01.rotateAngleX = 0.9f;
                this.EquipTubeR01.rotateAngleX = 0.9f;
            }
        }
        if (ent.getAttackTick() > 40) {
            GlStateManager.translate(0.0f, 0.08f, 0.0f);
            this.Head.rotateAngleX -= 1.0472f;
            this.BodyMain.rotateAngleX = 1.7f;
            this.Butt.rotateAngleX = -0.8378f;
            this.Cloth03.rotateAngleX -= 0.7f;
            this.Cloth04.rotateAngleX -= 1.1f;
            this.ArmLeft01.rotateAngleX = -0.9f;
            this.ArmLeft01.rotateAngleZ = 0.2618f;
            this.ArmRight01.rotateAngleX = -1.9f;
            this.ArmRight01.rotateAngleZ = -0.2618f;
            this.EquipBase.rotateAngleX = -1.4f;
            addk1 -= 0.7f;
            addk2 -= 0.7f;
        }
        if ((f6 = ent.getSwingTime(f2 % 1.0f)) != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 0.2f;
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
        }
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }
}
