package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.BasicEntityMount;
import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelBattleshipHime
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer Butt;
    private final ModelRenderer Cloth01;
    private final ModelRenderer Head;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer HeadHL;
    private final ModelRenderer HeadHR;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairL01;
    private final ModelRenderer HairR01;
    private final ModelRenderer HairL02;
    private final ModelRenderer HairL03;
    private final ModelRenderer HairR02;
    private final ModelRenderer HairR03;
    private final ModelRenderer Hair01;
    private final ModelRenderer Hair02;
    private final ModelRenderer Hair03;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer LegRight02;
    private final ModelRenderer ClothR02;
    private final ModelRenderer ClothR03;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer ClothL02;
    private final ModelRenderer ClothL03;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;

    public ModelBattleshipHime() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.scale = 0.5f;
        this.offsetY = 0.0f;
        this.offsetItem = new float[]{0.08f, 0.43f, -0.08f};
        this.offsetBlock = new float[]{0.08f, 0.43f, -0.08f};
        this.setDefaultFaceModel();
        this.HairL02 = new ModelRenderer(this, 88, 100);
        this.HairL02.setRotationPoint(0.0f, 10.0f, 0.0f);
        this.HairL02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 3, 0.0f);
        this.setRotateAngle(this.HairL02, 0.05235988f, 0.0f, 0.08726646f);
        this.HairR02 = new ModelRenderer(this, 88, 100);
        this.HairR02.setRotationPoint(0.2f, 10.0f, 0.0f);
        this.HairR02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 3, 0.0f);
        this.setRotateAngle(this.HairR02, 0.08726646f, 0.0f, -0.05235988f);
        this.ClothR02 = new ModelRenderer(this, 10, 1);
        this.ClothR02.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.ClothR02.addBox(-3.6f, 0.0f, -3.7f, 8, 3, 9, 0.0f);
        this.setRotateAngle(this.ClothR02, 0.13962634f, 0.0f, 0.0f);
        this.ClothL02 = new ModelRenderer(this, 10, 1);
        this.ClothL02.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.ClothL02.addBox(-4.4f, 0.0f, -3.7f, 8, 3, 9, 0.0f);
        this.setRotateAngle(this.ClothL02, 0.13962634f, 0.0f, 0.0f);
        this.LegLeft01 = new ModelRenderer(this, 0, 84);
        this.LegLeft01.mirror = true;
        this.LegLeft01.setRotationPoint(4.5f, 9.5f, -2.7f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegLeft01, -0.20943952f, 0.0f, 0.05235988f);
        this.BoobR = new ModelRenderer(this, 33, 101);
        this.BoobR.setRotationPoint(-3.7f, -9.0f, -3.5f);
        this.BoobR.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobR, -0.6981317f, -0.13962634f, -0.08726646f);
        this.ArmLeft01 = new ModelRenderer(this, 15, 80);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, 0.0f, 0.0f, -0.20943952f);
        this.BoobL = new ModelRenderer(this, 33, 101);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.7f, -9.0f, -3.5f);
        this.BoobL.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobL, -0.6981317f, 0.13962634f, 0.08726646f);
        this.Hair02 = new ModelRenderer(this, 2, 47);
        this.Hair02.setRotationPoint(0.0f, 12.0f, 5.7f);
        this.Hair02.addBox(-8.0f, 0.0f, -5.0f, 16, 15, 8, 0.0f);
        this.setRotateAngle(this.Hair02, -0.05235988f, 0.0f, 0.0f);
        this.Hair = new ModelRenderer(this, 50, 75);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.0f);
        this.Hair.addBox(-8.0f, -8.0f, -7.2f, 16, 17, 8, 0.0f);
        this.HeadHL = new ModelRenderer(this, 120, 29);
        this.HeadHL.mirror = true;
        this.HeadHL.setRotationPoint(3.5f, -7.5f, -3.3f);
        this.HeadHL.addBox(-1.0f, -9.0f, -1.0f, 2, 5, 2, 0.0f);
        this.setRotateAngle(this.HeadHL, 0.6981317f, 0.0f, 0.13962634f);
        this.BodyMain = new ModelRenderer(this, 0, 104);
        this.BodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 17, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.05235988f, 0.0f, 0.0f);
        this.Hair03 = new ModelRenderer(this, 3, 24);
        this.Hair03.setRotationPoint(0.0f, 12.0f, 0.2f);
        this.Hair03.addBox(-8.0f, 0.0f, -5.5f, 16, 13, 8, 0.0f);
        this.setRotateAngle(this.Hair03, -0.08970992f, 0.0f, 0.016231563f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.ClothL03 = new ModelRenderer(this, 8, 0);
        this.ClothL03.setRotationPoint(0.0f, 1.5f, 0.1f);
        this.ClothL03.addBox(-4.5f, 0.0f, -3.8f, 9, 5, 10, 0.0f);
        this.setRotateAngle(this.ClothL03, 0.08726646f, 0.0f, 0.0f);
        this.Hair01 = new ModelRenderer(this, 50, 46);
        this.Hair01.setRotationPoint(0.0f, 9.0f, 1.0f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 17, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.17453292f, 0.0f, 0.0f);
        this.LegRight02 = new ModelRenderer(this, 24, 80);
        this.LegRight02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegRight02.addBox(-3.0f, 0.0f, 0.0f, 6, 15, 6, 0.0f);
        this.LegRight01 = new ModelRenderer(this, 0, 84);
        this.LegRight01.setRotationPoint(-4.5f, 9.5f, -2.7f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegRight01, -0.20943952f, 0.0f, -0.05235988f);
        this.HairR01 = new ModelRenderer(this, 88, 100);
        this.HairR01.setRotationPoint(-6.5f, 0.0f, -5.0f);
        this.HairR01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 3, 0.0f);
        this.setRotateAngle(this.HairR01, -0.13962634f, 0.17453292f, 0.13962634f);
        this.Butt = new ModelRenderer(this, 82, 13);
        this.Butt.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Butt.addBox(-7.5f, 4.0f, -5.5f, 15, 8, 8, 0.0f);
        this.setRotateAngle(this.Butt, 0.2617994f, 0.0f, 0.0f);
        this.HairMain = new ModelRenderer(this, 2, 0);
        this.HairMain.setRotationPoint(0.0f, -15.0f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 9, 10, 0.0f);
        this.LegLeft02 = new ModelRenderer(this, 24, 80);
        this.LegLeft02.mirror = true;
        this.LegLeft02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegLeft02.addBox(-3.0f, 0.0f, 0.0f, 6, 15, 6, 0.0f);
        this.HairL03 = new ModelRenderer(this, 88, 100);
        this.HairL03.setRotationPoint(0.0f, 11.0f, 0.0f);
        this.HairL03.addBox(-1.0f, 0.0f, 0.0f, 2, 13, 3, 0.0f);
        this.setRotateAngle(this.HairL03, 0.13962634f, 0.0f, 0.08726646f);
        this.ArmLeft02 = new ModelRenderer(this, 0, 71);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(3.0f, 11.0f, 2.5f);
        this.ArmLeft02.addBox(-5.0f, 0.0f, -5.0f, 5, 13, 5, 0.0f);
        this.HairR03 = new ModelRenderer(this, 88, 100);
        this.HairR03.setRotationPoint(0.0f, 11.0f, 0.0f);
        this.HairR03.addBox(-1.0f, 0.0f, 0.0f, 2, 13, 3, 0.0f);
        this.setRotateAngle(this.HairR03, 0.13962634f, 0.0f, -0.05235988f);
        this.Cloth01 = new ModelRenderer(this, 84, 0);
        this.Cloth01.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.Cloth01.addBox(-7.0f, 0.0f, -4.5f, 14, 5, 8, 0.0f);
        this.setRotateAngle(this.Cloth01, 0.13962634f, 0.0f, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 0, 71);
        this.ArmRight02.setRotationPoint(-3.0f, 11.0f, 2.5f);
        this.ArmRight02.addBox(0.0f, 0.0f, -5.0f, 5, 13, 5, 0.0f);
        this.Neck = new ModelRenderer(this, 44, 0);
        this.Neck.setRotationPoint(0.0f, -10.0f, -0.5f);
        this.Neck.addBox(-4.5f, -2.0f, -4.0f, 9, 1, 8, 0.0f);
        this.setRotateAngle(this.Neck, 0.05235988f, 0.0f, 0.0f);
        this.Ahoke = new ModelRenderer(this, 108, 41);
        this.Ahoke.setRotationPoint(0.0f, -5.3f, -7.2f);
        this.Ahoke.addBox(-2.0f, 0.0f, 0.0f, 10, 12, 0, 0.0f);
        this.setRotateAngle(this.Ahoke, -0.05235988f, 0.0f, (float)(-Math.PI) / 90);
        this.ClothR03 = new ModelRenderer(this, 8, 0);
        this.ClothR03.setRotationPoint(0.0f, 1.5f, 0.1f);
        this.ClothR03.addBox(-4.5f, 0.0f, -3.8f, 9, 5, 10, 0.0f);
        this.setRotateAngle(this.ClothR03, 0.08726646f, 0.0f, 0.0f);
        this.ArmRight01 = new ModelRenderer(this, 15, 80);
        this.ArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, 0.10471976f, 0.0f, 0.20943952f);
        this.HeadHR = new ModelRenderer(this, 120, 29);
        this.HeadHR.setRotationPoint(-3.5f, -7.5f, -3.3f);
        this.HeadHR.addBox(-1.0f, -9.0f, -1.0f, 2, 5, 2, 0.0f);
        this.setRotateAngle(this.HeadHR, 0.6981317f, 0.0f, -0.13962634f);
        this.HairL01 = new ModelRenderer(this, 88, 100);
        this.HairL01.setRotationPoint(6.5f, 0.0f, -5.0f);
        this.HairL01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 3, 0.0f);
        this.setRotateAngle(this.HairL01, -0.13962634f, -0.17453292f, -0.13962634f);
        this.HairL01.addChild(this.HairL02);
        this.HairR01.addChild(this.HairR02);
        this.LegRight01.addChild(this.ClothR02);
        this.LegLeft01.addChild(this.ClothL02);
        this.Butt.addChild(this.LegLeft01);
        this.BodyMain.addChild(this.BoobR);
        this.BodyMain.addChild(this.ArmLeft01);
        this.BodyMain.addChild(this.BoobL);
        this.Hair01.addChild(this.Hair02);
        this.Head.addChild(this.Hair);
        this.Head.addChild(this.HeadHL);
        this.Hair02.addChild(this.Hair03);
        this.Neck.addChild(this.Head);
        this.LegLeft01.addChild(this.ClothL03);
        this.HairMain.addChild(this.Hair01);
        this.LegRight01.addChild(this.LegRight02);
        this.Butt.addChild(this.LegRight01);
        this.Hair.addChild(this.HairR01);
        this.BodyMain.addChild(this.Butt);
        this.Head.addChild(this.HairMain);
        this.LegLeft01.addChild(this.LegLeft02);
        this.HairL02.addChild(this.HairL03);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.HairR02.addChild(this.HairR03);
        this.BodyMain.addChild(this.Cloth01);
        this.ArmRight01.addChild(this.ArmRight02);
        this.BodyMain.addChild(this.Neck);
        this.Hair.addChild(this.Ahoke);
        this.LegRight01.addChild(this.ClothR03);
        this.BodyMain.addChild(this.ArmRight01);
        this.Head.addChild(this.HeadHR);
        this.Hair.addChild(this.HairL01);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain, -0.05235988f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(0.0f, -10.0f, -0.5f);
        this.setRotateAngle(this.GlowNeck, 0.05235988f, 0.0f, 0.0f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        GlStateManager.enableLighting();
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowNeck.rotateAngleX = this.Neck.rotateAngleX;
        this.GlowNeck.rotateAngleY = this.Neck.rotateAngleY;
        this.GlowNeck.rotateAngleZ = this.Neck.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
    }

    @Override
    public void showEquip(IShipEmotion ent) {
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float addk1;
        float addk2;
        float headX;
        float headZ;
        GlStateManager.translate(0.0f, 1.05f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = 0.0f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.BoobL.rotateAngleX = -0.7f;
        this.BoobR.rotateAngleX = -0.7f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Hair01.rotateAngleX = 0.26f;
        this.Hair02.rotateAngleX = -0.08f;
        this.Hair03.rotateAngleX = -0.14f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.offsetX = 0.0f;
        this.ArmLeft02.offsetY = 0.0f;
        this.ArmLeft02.offsetZ = 0.0f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.offsetX = 0.0f;
        this.ArmRight02.offsetY = 0.0f;
        this.ArmRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.Head.rotateAngleX += 0.14f;
        this.BodyMain.rotateAngleX = 0.4f;
        this.Butt.rotateAngleX = -0.4f;
        this.Butt.offsetZ = 0.19f;
        this.BoobL.rotateAngleX -= 0.2f;
        this.BoobR.rotateAngleX -= 0.2f;
        this.ArmLeft01.rotateAngleX = -1.3f;
        this.ArmLeft01.rotateAngleZ = -0.1f;
        this.ArmLeft02.rotateAngleZ = 1.15f;
        this.ArmRight01.rotateAngleX = -1.3f;
        this.ArmRight01.rotateAngleZ = 0.1f;
        this.ArmRight02.rotateAngleZ = -1.4f;
        addk1 = -2.1232f;
        addk2 = -2.0708f;
        this.LegLeft01.rotateAngleZ = -0.2f;
        this.LegLeft02.rotateAngleX = 1.34f;
        this.LegRight01.rotateAngleZ = 0.2f;
        this.LegRight02.rotateAngleX = 1.13f;
        this.Hair01.rotateAngleX -= 0.2f;
        this.Hair02.rotateAngleX -= 0.2f;
        this.Hair03.rotateAngleX -= 0.1f;
        this.Hair01.rotateAngleZ = headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair02.rotateAngleZ = headZ;
        this.HairL01.rotateAngleZ = headZ - 0.0f;
        this.HairL02.rotateAngleZ = headZ + 0.087f;
        this.HairR01.rotateAngleZ = headZ + 0.0f;
        this.HairR02.rotateAngleZ = headZ - 0.052f;
        headX = this.Head.rotateAngleX * -0.5f;
        this.HairL01.rotateAngleX = headX - 0.1f;
        this.HairL02.rotateAngleX = headX - 0.3f;
        this.HairL03.rotateAngleX = headX - 0.0f;
        this.HairR01.rotateAngleX = headX - 0.1f;
        this.HairR02.rotateAngleX = headX - 0.3f;
        this.HairR03.rotateAngleX = headX - 0.0f;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float f6;
        float angleX = MathHelper.cos(f2 * 0.08f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.3f + f * 0.5f);
        float angleX2 = MathHelper.cos(f2 * 0.08f + 0.6f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1 * 0.7f;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1 * 0.7f;
        float addk1;
        float addk2;
        float headX;
        float headZ;
        GlStateManager.translate(0.0f, 0.5f, 0.0f);
        if (ent.getShipDepth(0) > 0.0 || ent.getShipDepth(1) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 - 0.122f;
        addk2 = angleAdd2 - 0.174f;
        this.Head.rotateAngleX = f4 * 0.014f + 0.05f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.BoobL.rotateAngleX = angleX * 0.06f - 0.7f;
        this.BoobR.rotateAngleX = angleX * 0.06f - 0.7f;
        this.Ahoke.rotateAngleZ = angleX * 0.02f - 0.02f;
        this.BodyMain.rotateAngleX = -0.1f;
        this.Butt.rotateAngleX = 0.2618f;
        this.Butt.offsetZ = 0.0f;
        this.Hair01.rotateAngleX = angleX * 0.03f + 0.15f;
        this.Hair02.rotateAngleX = -angleX1 * 0.04f - 0.05f;
        this.Hair03.rotateAngleX = -angleX2 * 0.07f - 0.08f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleX = angleX * 0.02f - 0.14f;
        this.HairL02.rotateAngleX = -angleX1 * 0.04f + 0.08f;
        this.HairL03.rotateAngleX = -angleX2 * 0.07f + 0.1f;
        this.HairR01.rotateAngleX = angleX * 0.02f - 0.14f;
        this.HairR02.rotateAngleX = -angleX1 * 0.04f + 0.08f;
        this.HairR03.rotateAngleX = -angleX2 * 0.07f + 0.1f;
        this.HairL01.rotateAngleZ = -0.14f;
        this.HairL02.rotateAngleZ = 0.087f;
        this.HairL03.rotateAngleZ = 0.087f;
        this.HairR01.rotateAngleZ = 0.14f;
        this.HairR02.rotateAngleZ = -0.06f;
        this.HairR03.rotateAngleZ = -0.06f;
        this.ArmLeft01.rotateAngleX = angleAdd2 * 0.8f;
        this.ArmLeft01.rotateAngleZ = angleX * 0.08f - 0.2f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.rotateAngleZ = 0.0f;
        this.ArmLeft02.offsetX = 0.0f;
        this.ArmLeft02.offsetY = 0.0f;
        this.ArmLeft02.offsetZ = 0.0f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.8f + 0.1745f;
        this.ArmRight01.rotateAngleZ = -angleX * 0.08f + 0.2f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.ArmRight02.offsetX = 0.0f;
        this.ArmRight02.offsetY = 0.0f;
        this.ArmRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.087f;
        this.LegLeft02.rotateAngleX = 0.0f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.087f;
        this.LegRight02.rotateAngleX = 0.0f;
        if (ent.getIsSprinting() || f1 > 0.9f) {
            // empty if block
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.08f, 0.0f);
            this.Head.rotateAngleX -= 0.6283f;
            this.BodyMain.rotateAngleX = 0.8727f;
            this.ArmLeft01.rotateAngleX = -0.35f;
            this.ArmLeft01.rotateAngleZ = 0.2618f;
            this.ArmRight01.rotateAngleX = -0.35f;
            this.ArmRight01.rotateAngleZ = -0.2618f;
            addk1 -= 0.88f;
            addk2 -= 0.88f;
            this.Hair01.rotateAngleX += 0.37f;
            this.Hair02.rotateAngleX += 0.23f;
            this.Hair03.rotateAngleX -= 0.1f;
        }
        if (ent.getIsSitting() && !ent.getIsRiding()) {
            if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 0.65f, 0.0f);
                this.Head.rotateAngleX = -1.2217f;
                this.Head.rotateAngleY *= 0.5f;
                this.BodyMain.rotateAngleX = 1.2217f;
                this.ArmLeft01.rotateAngleX = -1.9199f;
                this.ArmLeft01.rotateAngleZ = -0.1745f;
                this.ArmLeft02.rotateAngleX = -2.31f;
                this.ArmLeft02.offsetY = 0.22f;
                this.ArmLeft02.offsetZ = -0.21f;
                this.ArmRight01.rotateAngleX = -1.9199f;
                this.ArmRight01.rotateAngleZ = 0.1745f;
                this.ArmRight02.rotateAngleX = -2.31f;
                this.ArmRight02.offsetY = 0.22f;
                this.ArmRight02.offsetZ = -0.21f;
                addk1 = 0.0f;
                addk2 = 0.0f;
                this.LegLeft02.rotateAngleX = angleX * 0.4f + 1.0f;
                this.LegRight02.rotateAngleX = -angleX * 0.4f + 1.0f;
                this.Hair01.rotateAngleX += 0.1f;
                this.Hair02.rotateAngleX += 0.05f;
                this.HairL01.rotateAngleX -= 0.3f;
                this.HairR01.rotateAngleX -= 0.3f;
                this.HairL02.rotateAngleX += 0.3f;
                this.HairR02.rotateAngleX += 0.3f;
            } else {
                GlStateManager.translate(0.0f, 0.33f, 0.0f);
                this.Head.rotateAngleX += 0.14f;
                this.BodyMain.rotateAngleX = -0.4363f;
                this.BoobL.rotateAngleX -= 0.25f;
                this.BoobR.rotateAngleX -= 0.25f;
                this.ArmLeft01.rotateAngleX = -0.3142f;
                this.ArmLeft01.rotateAngleZ = 0.349f;
                this.ArmLeft02.rotateAngleZ = 1.15f;
                this.ArmRight01.rotateAngleX = -0.4363f;
                this.ArmRight01.rotateAngleZ = -0.2793f;
                this.ArmRight02.rotateAngleZ = -1.4f;
                addk1 = -1.309f;
                addk2 = -1.7f;
                this.LegLeft01.rotateAngleY = 0.3142f;
                this.LegLeft02.rotateAngleX = 1.0472f;
                this.LegRight01.rotateAngleY = -0.35f;
                this.LegRight01.rotateAngleZ = -0.2618f;
                this.LegRight02.rotateAngleX = 0.9f;
                this.Hair01.rotateAngleX += 0.12f;
                this.Hair02.rotateAngleX += 0.15f;
                this.Hair03.rotateAngleX += 0.25f;
            }
        }
        if (ent.getIsRiding()) {
            if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
                if (ent.getIsSitting()) {
                    if (ent.getStateEmotion(1) == 4) {
                        GlStateManager.translate(0.0f, 0.68f, -0.05f);
                        this.Head.rotateAngleX = -1.2217f;
                        this.Head.rotateAngleY /= 2.0f;
                        this.BodyMain.rotateAngleX = 1.2217f;
                        this.ArmLeft01.rotateAngleX = -1.9199f;
                        this.ArmLeft01.rotateAngleZ = -0.1745f;
                        this.ArmLeft02.rotateAngleX = -2.31f;
                        this.ArmLeft02.offsetY = 0.22f;
                        this.ArmLeft02.offsetZ = -0.21f;
                        this.ArmRight01.rotateAngleX = -1.9199f;
                        this.ArmRight01.rotateAngleZ = 0.1745f;
                        this.ArmRight02.rotateAngleX = -2.31f;
                        this.ArmRight02.offsetY = 0.22f;
                        this.ArmRight02.offsetZ = -0.21f;
                        addk1 = 0.0f;
                        addk2 = 0.0f;
                        this.LegLeft02.rotateAngleX = angleX * 0.4f + 1.0f;
                        this.LegRight02.rotateAngleX = -angleX * 0.4f + 1.0f;
                        this.Hair01.rotateAngleX += 0.1f;
                        this.Hair02.rotateAngleX += 0.05f;
                        this.HairL01.rotateAngleX -= 0.3f;
                        this.HairR01.rotateAngleX -= 0.3f;
                        this.HairL02.rotateAngleX += 0.3f;
                        this.HairR02.rotateAngleX += 0.3f;
                    } else {
                        GlStateManager.translate(0.0f, 0.51f, -0.05f);
                        this.Head.rotateAngleX += 0.14f;
                        this.BodyMain.rotateAngleX = -0.4363f;
                        this.BoobL.rotateAngleX -= 0.25f;
                        this.BoobR.rotateAngleX -= 0.25f;
                        this.ArmLeft01.rotateAngleX = -0.3142f;
                        this.ArmLeft01.rotateAngleZ = 0.349f;
                        this.ArmLeft02.rotateAngleZ = 1.15f;
                        this.ArmRight01.rotateAngleX = -0.4363f;
                        this.ArmRight01.rotateAngleZ = -0.2793f;
                        this.ArmRight02.rotateAngleZ = -1.4f;
                        addk1 = -1.309f;
                        addk2 = -1.7f;
                        this.LegLeft01.rotateAngleY = 0.3142f;
                        this.LegLeft02.rotateAngleX = 1.0472f;
                        this.LegRight01.rotateAngleY = -0.35f;
                        this.LegRight01.rotateAngleZ = -0.2618f;
                        this.LegRight02.rotateAngleX = 0.9f;
                        this.Hair01.rotateAngleX += 0.12f;
                        this.Hair02.rotateAngleX += 0.15f;
                        this.Hair03.rotateAngleX += 0.25f;
                    }
                } else {
                    GlStateManager.translate(0.0f, 0.17f, 0.0f);
                    this.Head.rotateAngleX += 0.1745f;
                    this.BodyMain.rotateAngleX = -0.35f;
                    this.ArmLeft01.rotateAngleX = -0.2f;
                    this.ArmLeft01.rotateAngleZ = 0.349f;
                    this.ArmLeft02.rotateAngleZ = 1.15f;
                    this.ArmRight01.rotateAngleX = -0.3f;
                    this.ArmRight01.rotateAngleZ = -0.2793f;
                    this.ArmRight02.rotateAngleZ = -1.4f;
                    addk1 = 0.1745f;
                    addk2 = -0.8727f;
                    this.LegLeft01.rotateAngleZ = -0.1f;
                    this.LegRight01.rotateAngleZ = 0.1f;
                    this.LegRight02.rotateAngleX = 1.0472f;
                    this.Hair01.rotateAngleX += 0.12f;
                    this.Hair02.rotateAngleX += 0.22f;
                    this.Hair03.rotateAngleX += 0.25f;
                }
            } else if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 1.3f, 0.0f);
                this.Head.rotateAngleX = -1.2217f;
                this.Head.rotateAngleY /= 2.0f;
                this.BodyMain.rotateAngleX = 1.2217f;
                this.ArmLeft01.rotateAngleX = -1.9199f;
                this.ArmLeft01.rotateAngleZ = -0.1745f;
                this.ArmLeft02.rotateAngleX = -2.31f;
                this.ArmLeft02.offsetY = 0.22f;
                this.ArmLeft02.offsetZ = -0.21f;
                this.ArmRight01.rotateAngleX = -1.9199f;
                this.ArmRight01.rotateAngleZ = 0.1745f;
                this.ArmRight02.rotateAngleX = -2.31f;
                this.ArmRight02.offsetY = 0.22f;
                this.ArmRight02.offsetZ = -0.21f;
                addk1 = 0.0f;
                addk2 = 0.0f;
                this.LegLeft02.rotateAngleX = angleX * 0.4f + 1.0f;
                this.LegRight02.rotateAngleX = -angleX * 0.4f + 1.0f;
                this.Hair01.rotateAngleX += 0.1f;
                this.Hair02.rotateAngleX += 0.05f;
                this.HairL01.rotateAngleX -= 0.3f;
                this.HairR01.rotateAngleX -= 0.3f;
                this.HairL02.rotateAngleX += 0.3f;
                this.HairR02.rotateAngleX += 0.3f;
            } else {
                GlStateManager.translate(0.0f, 0.8f, 0.0f);
                this.Head.rotateAngleX += 0.14f;
                this.BodyMain.rotateAngleX = -0.4363f;
                this.ArmLeft01.rotateAngleX = -0.3142f;
                this.ArmLeft01.rotateAngleZ = 0.349f;
                this.ArmLeft02.rotateAngleZ = 1.15f;
                this.ArmRight01.rotateAngleX = -0.4363f;
                this.ArmRight01.rotateAngleZ = -0.2793f;
                this.ArmRight02.rotateAngleZ = -1.4f;
                addk1 = -1.309f;
                addk2 = -1.7f;
                this.LegLeft01.rotateAngleY = 0.3142f;
                this.LegLeft02.rotateAngleX = 1.0472f;
                this.LegRight01.rotateAngleY = -0.35f;
                this.LegRight01.rotateAngleZ = -0.2618f;
                this.LegRight02.rotateAngleX = 0.9f;
                this.Hair01.rotateAngleX += 0.12f;
                this.Hair02.rotateAngleX += 0.15f;
                this.Hair03.rotateAngleX += 0.25f;
            }
        }
        if (ent.getAttackTick() > 20) {
            this.ArmLeft01.rotateAngleX = -1.6f;
            this.ArmLeft01.rotateAngleY = 0.0f;
            this.ArmLeft01.rotateAngleZ = 0.21f;
            this.ArmLeft02.rotateAngleX = 0.0f;
            this.ArmLeft02.rotateAngleZ = 0.0f;
        }
        if ((f6 = ent.getSwingTime(f2 - (int)f2)) != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX = -0.4f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = -0.2f;
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 0.2f;
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
            this.ArmRight02.rotateAngleX = 0.0f;
            this.ArmRight02.rotateAngleY = 0.0f;
            this.ArmRight02.rotateAngleZ = 0.0f;
        }
        headX = this.Head.rotateAngleX * -0.5f;
        headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair01.rotateAngleX += headX;
        this.Hair01.rotateAngleZ += headZ;
        this.Hair02.rotateAngleX += headX * 0.5f;
        this.Hair02.rotateAngleZ += headZ * 0.5f;
        this.Hair03.rotateAngleX += headX * 0.5f;
        this.Hair03.rotateAngleZ += headZ * 0.5f;
        this.HairL01.rotateAngleX += headX;
        this.HairL02.rotateAngleX += headX * 0.5f;
        this.HairL03.rotateAngleX += headX * 0.5f;
        this.HairR01.rotateAngleX += headX;
        this.HairR02.rotateAngleX += headX * 0.5f;
        this.HairR03.rotateAngleX += headX * 0.5f;
        this.HairL01.rotateAngleZ += headZ;
        this.HairL02.rotateAngleZ += headZ * 0.5f;
        this.HairL03.rotateAngleZ += headZ * 0.5f;
        this.HairR01.rotateAngleZ += headZ;
        this.HairR02.rotateAngleZ += headZ * 0.5f;
        this.HairR03.rotateAngleZ += headZ * 0.5f;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }
}
