package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.BasicEntityMount;
import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelSubmHime
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer Butt;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer EquipBack;
    private final ModelRenderer Head;
    private final ModelRenderer Collar01;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer Ahoke01;
    private final ModelRenderer Ahoke01a;
    private final ModelRenderer HairU01;
    private final ModelRenderer HairR01;
    private final ModelRenderer HairL01;
    private final ModelRenderer HairR02;
    private final ModelRenderer HairL02;
    private final ModelRenderer Hair01;
    private final ModelRenderer Hair02;
    private final ModelRenderer Hair03;
    private final ModelRenderer Ahoke02;
    private final ModelRenderer Ahoke03;
    private final ModelRenderer Ahoke04;
    private final ModelRenderer Ahoke05;
    private final ModelRenderer Ahoke06;
    private final ModelRenderer Ahoke02a;
    private final ModelRenderer Ahoke03a;
    private final ModelRenderer Ahoke04a;
    private final ModelRenderer Ahoke05a;
    private final ModelRenderer Ahoke06a;
    private final ModelRenderer Collar02;
    private final ModelRenderer Collar03;
    private final ModelRenderer Collar04;
    private final ModelRenderer Collar05;
    private final ModelRenderer Collar05a;
    private final ModelRenderer Collar05b;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer Skirt01;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer Skirt02;
    private final ModelRenderer LegRight02;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer EquipTube00;
    private final ModelRenderer EquipTube00_1;
    private final ModelRenderer EquipTube01;
    private final ModelRenderer EquipTube01a;
    private final ModelRenderer EquipTube02;
    private final ModelRenderer EquipTube02a;
    private final ModelRenderer EquipTube03;
    private final ModelRenderer EquipTube03a;
    private final ModelRenderer EquipTube04;
    private final ModelRenderer EquipTube04a;
    private final ModelRenderer EquipTube05;
    private final ModelRenderer EquipTube05a;
    private final ModelRenderer EquipTBase;
    private final ModelRenderer EquipT01;
    private final ModelRenderer EquipT02;
    private final ModelRenderer EquipT03;
    private final ModelRenderer EquipT04;
    private final ModelRenderer EquipT05;
    private final ModelRenderer EquipT06;
    private final ModelRenderer EquipT07;
    private final ModelRenderer EquipT02a;
    private final ModelRenderer EquipT02b;
    private final ModelRenderer EquipT02c;
    private final ModelRenderer EquipT02d;
    private final ModelRenderer EquipTJaw01;
    private final ModelRenderer EquipTJaw02;
    private final ModelRenderer EquipTEyeA;
    private final ModelRenderer EquipTEyeB;
    private final ModelRenderer EquipTube01_1;
    private final ModelRenderer EquipTube01a_1;
    private final ModelRenderer EquipTube02_1;
    private final ModelRenderer EquipTube02a_1;
    private final ModelRenderer EquipTube03_1;
    private final ModelRenderer EquipTube03a_1;
    private final ModelRenderer EquipTube04_1;
    private final ModelRenderer EquipTube04a_1;
    private final ModelRenderer EquipTube05_1;
    private final ModelRenderer EquipTube05a_1;
    private final ModelRenderer EquipTBase_1;
    private final ModelRenderer EquipT01_1;
    private final ModelRenderer EquipT03_1;
    private final ModelRenderer EquipT05_1;
    private final ModelRenderer EquipT06_1;
    private final ModelRenderer EquipT07_1;
    private final ModelRenderer EquipT02_1;
    private final ModelRenderer EquipT04_1;
    private final ModelRenderer EquipT02a_1;
    private final ModelRenderer EquipT02b_1;
    private final ModelRenderer EquipT02c_1;
    private final ModelRenderer EquipT02d_1;
    private final ModelRenderer EquipTJaw01_1;
    private final ModelRenderer EquipTJaw02_1;
    private final ModelRenderer EquipTEyeA_1;
    private final ModelRenderer EquipTEyeB_1;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;
    private final ModelRenderer GlowEquipBase;

    public ModelSubmHime() {
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.scale = 0.48f;
        this.offsetY = 1.62f;
        this.offsetItem = new float[]{0.08f, 1.02f, -0.07f};
        this.offsetBlock = new float[]{0.08f, 1.02f, -0.07f};
        this.setDefaultFaceModel();
        this.EquipTJaw01_1 = new ModelRenderer(this, 59, 25);
        this.EquipTJaw01_1.setRotationPoint(0.0f, 6.3f, 0.5f);
        this.EquipTJaw01_1.addBox(-3.5f, 0.0f, 0.0f, 7, 4, 3, 0.0f);
        this.setRotateAngle(this.EquipTJaw01_1, 0.2617994f, 0.0f, 0.0f);
        this.EquipT05_1 = new ModelRenderer(this, 0, 0);
        this.EquipT05_1.setRotationPoint(0.0f, 14.0f, 0.0f);
        this.EquipT05_1.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipTube05a = new ModelRenderer(this, 44, 67);
        this.EquipTube05a.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube05a.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.EquipTJaw02_1 = new ModelRenderer(this, 59, 25);
        this.EquipTJaw02_1.mirror = true;
        this.EquipTJaw02_1.setRotationPoint(0.0f, 4.6f, 1.0f);
        this.EquipTJaw02_1.addBox(-3.5f, 0.0f, -2.5f, 7, 4, 3, 0.0f);
        this.setRotateAngle(this.EquipTJaw02_1, 1.4835298f, 0.0f, (float)Math.PI);
        this.EquipT01 = new ModelRenderer(this, 0, 0);
        this.EquipT01.setRotationPoint(0.0f, -19.0f, 0.0f);
        this.EquipT01.addBox(-2.0f, 0.0f, -2.0f, 4, 3, 4, 0.0f);
        this.HairR02 = new ModelRenderer(this, 0, 18);
        this.HairR02.mirror = true;
        this.HairR02.setRotationPoint(0.2f, 10.0f, 0.0f);
        this.HairR02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 5, 0.0f);
        this.setRotateAngle(this.HairR02, 0.17453292f, 0.0f, -0.05235988f);
        this.Ahoke06a = new ModelRenderer(this, 42, 89);
        this.Ahoke06a.mirror = true;
        this.Ahoke06a.setRotationPoint(0.0f, 7.9f, 0.0f);
        this.Ahoke06a.addBox(-2.0f, 0.0f, 0.0f, 4, 7, 0, 0.0f);
        this.setRotateAngle(this.Ahoke06a, -0.5235988f, 0.08726646f, 0.0f);
        this.EquipT04_1 = new ModelRenderer(this, 0, 0);
        this.EquipT04_1.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.EquipT04_1.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipT02c = new ModelRenderer(this, 0, 0);
        this.EquipT02c.setRotationPoint(0.0f, 0.5f, 5.9f);
        this.EquipT02c.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.setRotateAngle(this.EquipT02c, 0.0f, 1.5707964f, 0.0f);
        this.EquipTEyeB_1 = new ModelRenderer(this, 0, 14);
        this.EquipTEyeB_1.setRotationPoint(-3.2f, 10.9f, 3.0f);
        this.EquipTEyeB_1.addBox(0.0f, 0.0f, 0.0f, 0, 2, 2, 0.0f);
        this.setRotateAngle(this.EquipTEyeB_1, -2.0943952f, 0.0f, 0.0f);
        this.EquipTube03a_1 = new ModelRenderer(this, 44, 67);
        this.EquipTube03a_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube03a_1.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.Skirt02 = new ModelRenderer(this, 128, 17);
        this.Skirt02.setRotationPoint(0.0f, 3.5f, -2.7f);
        this.Skirt02.addBox(-10.5f, 0.0f, -6.5f, 21, 5, 13, 0.0f);
        this.setRotateAngle(this.Skirt02, -0.08726646f, 0.0f, 0.0f);
        this.LegRight02 = new ModelRenderer(this, 0, 47);
        this.LegRight02.mirror = true;
        this.LegRight02.setRotationPoint(-3.0f, 14.0f, -3.0f);
        this.LegRight02.addBox(0.0f, 0.0f, 0.0f, 6, 15, 6, 0.0f);
        this.EquipTube02 = new ModelRenderer(this, 0, 0);
        this.EquipTube02.setRotationPoint(0.0f, 7.0f, -1.0f);
        this.EquipTube02.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube02, 0.5235988f, 0.0f, 0.0f);
        this.Ahoke05a = new ModelRenderer(this, 50, 77);
        this.Ahoke05a.setRotationPoint(0.0f, 7.9f, 0.0f);
        this.Ahoke05a.addBox(-2.0f, 0.0f, 0.0f, 4, 8, 0, 0.0f);
        this.setRotateAngle(this.Ahoke05a, -0.2617994f, 0.08726646f, 0.0f);
        this.Ahoke01a = new ModelRenderer(this, 50, 79);
        this.Ahoke01a.setRotationPoint(0.0f, -15.0f, -1.5f);
        this.Ahoke01a.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke01a, -2.268928f, -2.6179938f, 0.0f);
        this.EquipTBase_1 = new ModelRenderer(this, 0, 0);
        this.EquipTBase_1.setRotationPoint(0.0f, 26.0f, 1.0f);
        this.EquipTBase_1.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTBase_1, 0.0f, -0.61f, 0.0f);
        this.EquipT02a = new ModelRenderer(this, 0, 0);
        this.EquipT02a.setRotationPoint(2.9f, 0.5f, 0.0f);
        this.EquipT02a.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.EquipTube00_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube00_1.setRotationPoint(-0.5f, 3.0f, 1.4f);
        this.EquipTube00_1.addBox(-1.5f, 0.0f, -1.5f, 3, 5, 3, 0.0f);
        this.setRotateAngle(this.EquipTube00_1, 0.2617994f, -0.61f, 0.0f);
        this.LegLeft02 = new ModelRenderer(this, 0, 47);
        this.LegLeft02.setRotationPoint(3.0f, 14.0f, -3.0f);
        this.LegLeft02.addBox(-6.0f, 0.0f, 0.0f, 6, 15, 6, 0.0f);
        this.EquipTube05a_1 = new ModelRenderer(this, 44, 67);
        this.EquipTube05a_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube05a_1.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.EquipT02a_1 = new ModelRenderer(this, 0, 0);
        this.EquipT02a_1.setRotationPoint(2.9f, 0.5f, 0.0f);
        this.EquipT02a_1.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.Hair03 = new ModelRenderer(this, 26, 32);
        this.Hair03.setRotationPoint(0.0f, 12.5f, -0.1f);
        this.Hair03.addBox(-8.0f, 0.0f, -4.5f, 16, 15, 7, 0.0f);
        this.setRotateAngle(this.Hair03, -0.05235988f, 0.0f, 0.0f);
        this.EquipT07_1 = new ModelRenderer(this, 0, 0);
        this.EquipT07_1.setRotationPoint(0.0f, 24.7f, 0.0f);
        this.EquipT07_1.addBox(-2.0f, 0.0f, -2.0f, 4, 1, 4, 0.0f);
        this.EquipT01_1 = new ModelRenderer(this, 0, 0);
        this.EquipT01_1.setRotationPoint(0.0f, -19.0f, 0.0f);
        this.EquipT01_1.addBox(-2.0f, 0.0f, -2.0f, 4, 3, 4, 0.0f);
        this.EquipTEyeB = new ModelRenderer(this, 0, 14);
        this.EquipTEyeB.setRotationPoint(-3.2f, 10.9f, 3.0f);
        this.EquipTEyeB.addBox(0.0f, 0.0f, 0.0f, 0, 2, 2, 0.0f);
        this.setRotateAngle(this.EquipTEyeB, -2.0943952f, 0.0f, 0.0f);
        this.EquipT02b_1 = new ModelRenderer(this, 0, 0);
        this.EquipT02b_1.setRotationPoint(-2.9f, 0.5f, 0.0f);
        this.EquipT02b_1.addBox(-3.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.EquipT02_1 = new ModelRenderer(this, 0, 0);
        this.EquipT02_1.setRotationPoint(0.0f, -16.0f, 0.0f);
        this.EquipT02_1.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipTJaw01 = new ModelRenderer(this, 59, 25);
        this.EquipTJaw01.setRotationPoint(0.0f, 6.3f, 0.5f);
        this.EquipTJaw01.addBox(-3.5f, 0.0f, 0.0f, 7, 4, 3, 0.0f);
        this.setRotateAngle(this.EquipTJaw01, 0.2617994f, 0.0f, 0.0f);
        this.BoobR = new ModelRenderer(this, 0, 36);
        this.BoobR.setRotationPoint(-3.2f, -8.5f, -3.8f);
        this.BoobR.addBox(-3.0f, 0.0f, 0.0f, 6, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobR, -0.87266463f, 0.08726646f, 0.06981317f);
        this.ArmRight01 = new ModelRenderer(this, 24, 71);
        this.ArmRight01.mirror = true;
        this.ArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, 0.0f, 0.0f, 0.2617994f);
        this.EquipT02d = new ModelRenderer(this, 0, 0);
        this.EquipT02d.setRotationPoint(0.0f, 0.5f, -5.9f);
        this.EquipT02d.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.setRotateAngle(this.EquipT02d, 0.0f, -1.5707964f, 0.0f);
        this.Ahoke04a = new ModelRenderer(this, 50, 77);
        this.Ahoke04a.setRotationPoint(0.0f, 5.9f, 0.0f);
        this.Ahoke04a.addBox(-2.0f, 0.0f, 0.0f, 4, 8, 0, 0.0f);
        this.setRotateAngle(this.Ahoke04a, 0.4886922f, 0.05235988f, 0.0f);
        this.EquipTBase = new ModelRenderer(this, 0, 0);
        this.EquipTBase.setRotationPoint(0.0f, 26.0f, 1.0f);
        this.EquipTBase.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTBase, 0.0f, 0.61f, 0.0f);
        this.Collar05 = new ModelRenderer(this, 0, 0);
        this.Collar05.setRotationPoint(0.0f, 4.0f, -0.2f);
        this.Collar05.addBox(-2.5f, 0.0f, -1.0f, 5, 2, 2, 0.0f);
        this.EquipT07 = new ModelRenderer(this, 0, 0);
        this.EquipT07.setRotationPoint(0.0f, 24.7f, 0.0f);
        this.EquipT07.addBox(-2.0f, 0.0f, -2.0f, 4, 1, 4, 0.0f);
        this.Skirt01 = new ModelRenderer(this, 128, 0);
        this.Skirt01.setRotationPoint(0.0f, 3.0f, 1.5f);
        this.Skirt01.addBox(-8.5f, 0.0f, -8.5f, 17, 5, 11, 0.0f);
        this.setRotateAngle(this.Skirt01, -0.08726646f, 0.0f, 0.0f);
        this.HairR01 = new ModelRenderer(this, 0, 18);
        this.HairR01.mirror = true;
        this.HairR01.setRotationPoint(-7.0f, 3.0f, -5.5f);
        this.HairR01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 5, 0.0f);
        this.setRotateAngle(this.HairR01, -0.19198622f, 0.17453292f, 0.08726646f);
        this.ArmLeft02 = new ModelRenderer(this, 24, 54);
        this.ArmLeft02.setRotationPoint(3.0f, 11.0f, 2.5f);
        this.ArmLeft02.addBox(-5.0f, 0.0f, -5.0f, 5, 12, 5, 0.0f);
        this.EquipBack = new ModelRenderer(this, 17, 31);
        this.EquipBack.setRotationPoint(0.0f, -0.7f, 4.4f);
        this.EquipBack.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, 0.0f);
        this.setRotateAngle(this.EquipBack, -0.7853982f, 0.0f, 0.0f);
        this.EquipTube04a_1 = new ModelRenderer(this, 44, 67);
        this.EquipTube04a_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube04a_1.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.EquipT02 = new ModelRenderer(this, 0, 0);
        this.EquipT02.setRotationPoint(0.0f, -16.0f, 0.0f);
        this.EquipT02.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.Collar01 = new ModelRenderer(this, 0, 0);
        this.Collar01.setRotationPoint(0.0f, -1.1f, -1.2f);
        this.Collar01.addBox(-6.0f, -2.0f, -4.0f, 12, 3, 8, 0.0f);
        this.setRotateAngle(this.Collar01, (float)Math.PI / 90, 0.0f, 0.0f);
        this.EquipTube04 = new ModelRenderer(this, 0, 0);
        this.EquipTube04.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube04.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube04, 0.6981317f, 0.0f, 0.0f);
        this.EquipT03_1 = new ModelRenderer(this, 0, 0);
        this.EquipT03_1.setRotationPoint(0.0f, -6.0f, 0.0f);
        this.EquipT03_1.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipT02c_1 = new ModelRenderer(this, 0, 0);
        this.EquipT02c_1.setRotationPoint(0.0f, 0.5f, 5.9f);
        this.EquipT02c_1.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.setRotateAngle(this.EquipT02c_1, 0.0f, 1.5707964f, 0.0f);
        this.EquipTube01a_1 = new ModelRenderer(this, 44, 67);
        this.EquipTube01a_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube01a_1.addBox(-1.0f, 0.0f, -1.0f, 2, 7, 2, 0.0f);
        this.EquipTube03 = new ModelRenderer(this, 0, 0);
        this.EquipTube03.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube03.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube03, 0.61086524f, 0.0f, 0.0f);
        this.EquipTEyeA_1 = new ModelRenderer(this, 0, 14);
        this.EquipTEyeA_1.setRotationPoint(3.2f, 10.9f, 3.0f);
        this.EquipTEyeA_1.addBox(0.0f, 0.0f, 0.0f, 0, 2, 2, 0.0f);
        this.setRotateAngle(this.EquipTEyeA_1, -2.0943952f, 0.0f, 0.0f);
        this.EquipT06_1 = new ModelRenderer(this, 0, 0);
        this.EquipT06_1.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.EquipT06_1.addBox(-2.5f, 0.0f, -2.5f, 5, 1, 5, 0.0f);
        this.EquipTube00 = new ModelRenderer(this, 0, 0);
        this.EquipTube00.setRotationPoint(0.5f, 3.0f, 1.4f);
        this.EquipTube00.addBox(-1.5f, 0.0f, -1.5f, 3, 5, 3, 0.0f);
        this.setRotateAngle(this.EquipTube00, 0.2617994f, 0.61f, 0.0f);
        this.EquipT04 = new ModelRenderer(this, 0, 0);
        this.EquipT04.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.EquipT04.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipTube04_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube04_1.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube04_1.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube04_1, 0.6981317f, 0.0f, 0.0f);
        this.Collar04 = new ModelRenderer(this, 0, 0);
        this.Collar04.setRotationPoint(0.0f, 2.5f, 0.0f);
        this.Collar04.addBox(-0.5f, 0.0f, -1.0f, 1, 5, 2, 0.0f);
        this.setRotateAngle(this.Collar04, 0.4553564f, 0.0f, 0.0f);
        this.Butt = new ModelRenderer(this, 0, 88);
        this.Butt.setRotationPoint(0.0f, 4.0f, 1.3f);
        this.Butt.addBox(-7.5f, 0.0f, -5.7f, 15, 8, 8, 0.0f);
        this.setRotateAngle(this.Butt, 0.34906584f, 0.0f, 0.0f);
        this.EquipTube01a = new ModelRenderer(this, 44, 67);
        this.EquipTube01a.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube01a.addBox(-1.0f, 0.0f, -1.0f, 2, 7, 2, 0.0f);
        this.Ahoke06 = new ModelRenderer(this, 42, 90);
        this.Ahoke06.setRotationPoint(0.0f, 5.9f, 0.0f);
        this.Ahoke06.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke06, -0.43633232f, 0.08726646f, 0.0f);
        this.Ahoke03a = new ModelRenderer(this, 50, 79);
        this.Ahoke03a.setRotationPoint(0.0f, 5.9f, 0.0f);
        this.Ahoke03a.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke03a, 1.0471976f, 0.05235988f, 0.0f);
        this.EquipTube03_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube03_1.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube03_1.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube03_1, 0.61086524f, 0.0f, 0.0f);
        this.Ahoke04 = new ModelRenderer(this, 50, 77);
        this.Ahoke04.setRotationPoint(0.0f, 5.9f, 0.0f);
        this.Ahoke04.addBox(-2.0f, 0.0f, 0.0f, 4, 8, 0, 0.0f);
        this.setRotateAngle(this.Ahoke04, 0.43633232f, 0.05235988f, 0.0f);
        this.BodyMain = new ModelRenderer(this, 0, 104);
        this.BodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 17, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.10471976f, 0.0f, 0.0f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.0f, -0.7f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.HairMain = new ModelRenderer(this, 46, 104);
        this.HairMain.setRotationPoint(0.0f, -14.8f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 11, 10, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 24, 71);
        this.ArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, 0.20943952f, 0.0f, -0.2617994f);
        this.EquipTube03a = new ModelRenderer(this, 44, 67);
        this.EquipTube03a.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube03a.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.EquipT02b = new ModelRenderer(this, 0, 0);
        this.EquipT02b.setRotationPoint(-2.9f, 0.5f, 0.0f);
        this.EquipT02b.addBox(-3.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.EquipTJaw02 = new ModelRenderer(this, 59, 25);
        this.EquipTJaw02.mirror = true;
        this.EquipTJaw02.setRotationPoint(0.0f, 4.6f, 1.0f);
        this.EquipTJaw02.addBox(-3.5f, 0.0f, -2.5f, 7, 4, 3, 0.0f);
        this.setRotateAngle(this.EquipTJaw02, 1.4835298f, 0.0f, (float)Math.PI);
        this.Neck = new ModelRenderer(this, 24, 63);
        this.Neck.setRotationPoint(0.0f, -9.6f, 0.5f);
        this.Neck.addBox(-2.5f, -3.0f, -2.9f, 5, 3, 5, 0.0f);
        this.setRotateAngle(this.Neck, 0.10471976f, 0.0f, 0.0f);
        this.HairL02 = new ModelRenderer(this, 0, 18);
        this.HairL02.setRotationPoint(0.0f, 10.0f, 0.0f);
        this.HairL02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 5, 0.0f);
        this.setRotateAngle(this.HairL02, 0.17453292f, 0.0f, 0.08726646f);
        this.Ahoke03 = new ModelRenderer(this, 50, 79);
        this.Ahoke03.setRotationPoint(0.0f, 7.9f, 0.0f);
        this.Ahoke03.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke03, 0.7853982f, 0.05235988f, 0.0f);
        this.Ahoke05 = new ModelRenderer(this, 50, 79);
        this.Ahoke05.setRotationPoint(0.0f, 7.9f, 0.0f);
        this.Ahoke05.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke05, -0.17453292f, 0.08726646f, 0.0f);
        this.Collar03 = new ModelRenderer(this, 0, 0);
        this.Collar03.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Collar03.addBox(-1.0f, 0.0f, -1.0f, 2, 3, 2, 0.0f);
        this.setRotateAngle(this.Collar03, 0.2617994f, 0.0f, 0.0f);
        this.Collar05a = new ModelRenderer(this, 0, 0);
        this.Collar05a.setRotationPoint(2.5f, 2.0f, 0.0f);
        this.Collar05a.addBox(0.0f, -2.0f, -0.5f, 3, 2, 1, 0.0f);
        this.setRotateAngle(this.Collar05a, 0.0f, -0.08726646f, -0.34906584f);
        this.EquipT06 = new ModelRenderer(this, 0, 0);
        this.EquipT06.setRotationPoint(0.0f, 24.0f, 0.0f);
        this.EquipT06.addBox(-2.5f, 0.0f, -2.5f, 5, 1, 5, 0.0f);
        this.Ahoke02 = new ModelRenderer(this, 50, 77);
        this.Ahoke02.setRotationPoint(0.0f, 7.9f, 0.0f);
        this.Ahoke02.addBox(-2.0f, 0.0f, 0.0f, 4, 8, 0, 0.0f);
        this.setRotateAngle(this.Ahoke02, 1.0471976f, -0.05235988f, 0.0f);
        this.Hair02 = new ModelRenderer(this, 72, 29);
        this.Hair02.setRotationPoint(0.0f, 13.5f, 5.5f);
        this.Hair02.addBox(-8.0f, 0.0f, -5.0f, 16, 16, 8, 0.0f);
        this.setRotateAngle(this.Hair02, -0.08726646f, 0.0f, 0.0f);
        this.EquipTube05_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube05_1.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube05_1.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube05_1, 0.61086524f, 0.0f, 0.0f);
        this.Ahoke02a = new ModelRenderer(this, 50, 79);
        this.Ahoke02a.setRotationPoint(0.0f, 5.9f, 0.0f);
        this.Ahoke02a.addBox(-2.0f, 0.0f, 0.0f, 4, 6, 0, 0.0f);
        this.setRotateAngle(this.Ahoke02a, 0.7853982f, -0.05235988f, 0.0f);
        this.LegRight01 = new ModelRenderer(this, 0, 68);
        this.LegRight01.mirror = true;
        this.LegRight01.setRotationPoint(-4.8f, 5.5f, -2.6f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegRight01, -0.19198622f, 0.0f, -0.08726646f);
        this.HairL01 = new ModelRenderer(this, 0, 18);
        this.HairL01.setRotationPoint(7.0f, 3.0f, -5.5f);
        this.HairL01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 5, 0.0f);
        this.setRotateAngle(this.HairL01, -0.19198622f, -0.17453292f, -0.08726646f);
        this.EquipTube01_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube01_1.setRotationPoint(0.0f, 4.5f, 0.0f);
        this.EquipTube01_1.addBox(-1.0f, 0.0f, -1.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube01_1, 0.34906584f, 0.0f, 0.0f);
        this.EquipTube02a = new ModelRenderer(this, 44, 67);
        this.EquipTube02a.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube02a.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.EquipTube05 = new ModelRenderer(this, 0, 0);
        this.EquipTube05.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.EquipTube05.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube05, 0.61086524f, 0.0f, 0.0f);
        this.EquipTEyeA = new ModelRenderer(this, 0, 14);
        this.EquipTEyeA.setRotationPoint(3.2f, 10.9f, 3.0f);
        this.EquipTEyeA.addBox(0.0f, 0.0f, 0.0f, 0, 2, 2, 0.0f);
        this.setRotateAngle(this.EquipTEyeA, -2.0943952f, 0.0f, 0.0f);
        this.EquipTube04a = new ModelRenderer(this, 44, 67);
        this.EquipTube04a.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube04a.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.Hair = new ModelRenderer(this, 50, 77);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.1f);
        this.Hair.addBox(-8.0f, -8.0f, -7.4f, 16, 16, 8, 0.0f);
        this.EquipT03 = new ModelRenderer(this, 0, 0);
        this.EquipT03.setRotationPoint(0.0f, -6.0f, 0.0f);
        this.EquipT03.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 24, 54);
        this.ArmRight02.mirror = true;
        this.ArmRight02.setRotationPoint(-3.0f, 11.0f, 2.5f);
        this.ArmRight02.addBox(0.0f, 0.0f, -5.0f, 5, 12, 5, 0.0f);
        this.Collar02 = new ModelRenderer(this, 0, 0);
        this.Collar02.setRotationPoint(0.0f, -0.6f, -3.2f);
        this.Collar02.addBox(-1.0f, 0.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.Collar02, -0.6981317f, 0.0f, 0.0f);
        this.EquipTube02a_1 = new ModelRenderer(this, 44, 67);
        this.EquipTube02a_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipTube02a_1.addBox(-1.0f, 0.0f, 0.0f, 2, 7, 2, 0.0f);
        this.Hair01 = new ModelRenderer(this, 80, 0);
        this.Hair01.setRotationPoint(0.0f, 9.0f, 1.0f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 17, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.2617994f, 0.0f, 0.0f);
        this.HairU01 = new ModelRenderer(this, 52, 56);
        this.HairU01.setRotationPoint(0.0f, -6.0f, -7.0f);
        this.HairU01.addBox(-8.5f, 0.0f, 0.0f, 17, 15, 6, 0.0f);
        this.BoobL = new ModelRenderer(this, 0, 36);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.2f, -8.5f, -3.7f);
        this.BoobL.addBox(-3.0f, 0.0f, 0.0f, 6, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobL, -0.87266463f, -0.08726646f, -0.06981317f);
        this.EquipT02d_1 = new ModelRenderer(this, 0, 0);
        this.EquipT02d_1.setRotationPoint(0.0f, 0.5f, -5.9f);
        this.EquipT02d_1.addBox(0.0f, 0.0f, -0.5f, 3, 7, 1, 0.0f);
        this.setRotateAngle(this.EquipT02d_1, 0.0f, -1.5707964f, 0.0f);
        this.EquipTube01 = new ModelRenderer(this, 0, 0);
        this.EquipTube01.setRotationPoint(0.0f, 4.5f, 0.0f);
        this.EquipTube01.addBox(-1.0f, 0.0f, -1.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube01, 0.34906584f, 0.0f, 0.0f);
        this.Collar05b = new ModelRenderer(this, 0, 0);
        this.Collar05b.setRotationPoint(-2.5f, 2.0f, 0.0f);
        this.Collar05b.addBox(-3.0f, -2.0f, -0.5f, 3, 2, 1, 0.0f);
        this.setRotateAngle(this.Collar05b, 0.0f, 0.08726646f, 0.34906584f);
        this.LegLeft01 = new ModelRenderer(this, 0, 68);
        this.LegLeft01.setRotationPoint(4.8f, 5.5f, -2.6f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegLeft01, -0.29670596f, 0.0f, 0.08726646f);
        this.EquipT05 = new ModelRenderer(this, 0, 0);
        this.EquipT05.setRotationPoint(0.0f, 14.0f, 0.0f);
        this.EquipT05.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.EquipTube02_1 = new ModelRenderer(this, 0, 0);
        this.EquipTube02_1.setRotationPoint(0.0f, 7.0f, -1.0f);
        this.EquipTube02_1.addBox(-1.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.setRotateAngle(this.EquipTube02_1, 0.5235988f, 0.0f, 0.0f);
        this.Ahoke01 = new ModelRenderer(this, 50, 77);
        this.Ahoke01.setRotationPoint(-1.0f, -15.0f, 0.0f);
        this.Ahoke01.addBox(-2.0f, 0.0f, 0.0f, 4, 8, 0, 0.0f);
        this.setRotateAngle(this.Ahoke01, -2.0071287f, 0.5235988f, 0.0f);
        this.EquipT04_1.addChild(this.EquipTJaw01_1);
        this.EquipTBase_1.addChild(this.EquipT05_1);
        this.EquipTube05.addChild(this.EquipTube05a);
        this.EquipT04_1.addChild(this.EquipTJaw02_1);
        this.EquipTBase.addChild(this.EquipT01);
        this.HairR01.addChild(this.HairR02);
        this.Ahoke05a.addChild(this.Ahoke06a);
        this.EquipTBase_1.addChild(this.EquipT04_1);
        this.EquipT02.addChild(this.EquipT02c);
        this.EquipT04_1.addChild(this.EquipTEyeB_1);
        this.EquipTube03_1.addChild(this.EquipTube03a_1);
        this.Skirt01.addChild(this.Skirt02);
        this.LegRight01.addChild(this.LegRight02);
        this.EquipTube01.addChild(this.EquipTube02);
        this.Ahoke04a.addChild(this.Ahoke05a);
        this.Head.addChild(this.Ahoke01a);
        this.EquipTube05a_1.addChild(this.EquipTBase_1);
        this.EquipT02.addChild(this.EquipT02a);
        this.LegLeft01.addChild(this.LegLeft02);
        this.EquipTube05_1.addChild(this.EquipTube05a_1);
        this.EquipT02_1.addChild(this.EquipT02a_1);
        this.Hair02.addChild(this.Hair03);
        this.EquipTBase_1.addChild(this.EquipT07_1);
        this.EquipTBase_1.addChild(this.EquipT01_1);
        this.EquipT04.addChild(this.EquipTEyeB);
        this.EquipT02_1.addChild(this.EquipT02b_1);
        this.EquipTBase_1.addChild(this.EquipT02_1);
        this.EquipT04.addChild(this.EquipTJaw01);
        this.BodyMain.addChild(this.BoobR);
        this.BodyMain.addChild(this.ArmRight01);
        this.EquipT02.addChild(this.EquipT02d);
        this.Ahoke03a.addChild(this.Ahoke04a);
        this.EquipTube05a.addChild(this.EquipTBase);
        this.Collar04.addChild(this.Collar05);
        this.EquipTBase.addChild(this.EquipT07);
        this.Butt.addChild(this.Skirt01);
        this.Hair.addChild(this.HairR01);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.EquipTube04_1.addChild(this.EquipTube04a_1);
        this.EquipTBase.addChild(this.EquipT02);
        this.Neck.addChild(this.Collar01);
        this.EquipTube03.addChild(this.EquipTube04);
        this.EquipTBase_1.addChild(this.EquipT03_1);
        this.EquipT02_1.addChild(this.EquipT02c_1);
        this.EquipTube01_1.addChild(this.EquipTube01a_1);
        this.EquipTube02.addChild(this.EquipTube03);
        this.EquipT04_1.addChild(this.EquipTEyeA_1);
        this.EquipTBase_1.addChild(this.EquipT06_1);
        this.EquipTBase.addChild(this.EquipT04);
        this.EquipTube03_1.addChild(this.EquipTube04_1);
        this.Collar03.addChild(this.Collar04);
        this.BodyMain.addChild(this.Butt);
        this.EquipTube01.addChild(this.EquipTube01a);
        this.Ahoke05.addChild(this.Ahoke06);
        this.Ahoke02a.addChild(this.Ahoke03a);
        this.EquipTube02_1.addChild(this.EquipTube03_1);
        this.Ahoke03.addChild(this.Ahoke04);
        this.Neck.addChild(this.Head);
        this.Head.addChild(this.HairMain);
        this.BodyMain.addChild(this.ArmLeft01);
        this.EquipTube03.addChild(this.EquipTube03a);
        this.EquipT02.addChild(this.EquipT02b);
        this.EquipT04.addChild(this.EquipTJaw02);
        this.BodyMain.addChild(this.Neck);
        this.HairL01.addChild(this.HairL02);
        this.Ahoke02.addChild(this.Ahoke03);
        this.Ahoke04.addChild(this.Ahoke05);
        this.Collar02.addChild(this.Collar03);
        this.Collar05.addChild(this.Collar05a);
        this.EquipTBase.addChild(this.EquipT06);
        this.Ahoke01.addChild(this.Ahoke02);
        this.Hair01.addChild(this.Hair02);
        this.EquipTube04_1.addChild(this.EquipTube05_1);
        this.Ahoke01a.addChild(this.Ahoke02a);
        this.Butt.addChild(this.LegRight01);
        this.Hair.addChild(this.HairL01);
        this.EquipTube00_1.addChild(this.EquipTube01_1);
        this.EquipTube02.addChild(this.EquipTube02a);
        this.EquipTube04.addChild(this.EquipTube05);
        this.EquipT04.addChild(this.EquipTEyeA);
        this.EquipTube04.addChild(this.EquipTube04a);
        this.Head.addChild(this.Hair);
        this.EquipTBase.addChild(this.EquipT03);
        this.ArmRight01.addChild(this.ArmRight02);
        this.Collar01.addChild(this.Collar02);
        this.EquipTube02_1.addChild(this.EquipTube02a_1);
        this.HairMain.addChild(this.Hair01);
        this.Hair.addChild(this.HairU01);
        this.BodyMain.addChild(this.BoobL);
        this.EquipT02_1.addChild(this.EquipT02d_1);
        this.EquipTube00.addChild(this.EquipTube01);
        this.Collar05.addChild(this.Collar05b);
        this.Butt.addChild(this.LegLeft01);
        this.EquipTBase.addChild(this.EquipT05);
        this.EquipTube01_1.addChild(this.EquipTube02_1);
        this.Head.addChild(this.Ahoke01);
        this.GlowBodyMain = new ModelRenderer(this, 0, 104);
        this.GlowBodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain, -0.10471976f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 24, 63);
        this.GlowNeck.setRotationPoint(0.0f, -9.6f, 0.5f);
        this.setRotateAngle(this.GlowNeck, 0.10471976f, 0.0f, 0.0f);
        this.GlowHead = new ModelRenderer(this, 44, 101);
        this.GlowHead.setRotationPoint(0.0f, -1.0f, -0.7f);
        this.GlowEquipBase = new ModelRenderer(this, 0, 0);
        this.GlowEquipBase.setRotationPoint(0.0f, 8.0f, 3.0f);
        this.GlowEquipBase.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.GlowBodyMain.addChild(this.EquipBack);
        this.GlowBodyMain.addChild(this.GlowEquipBase);
        this.GlowEquipBase.addChild(this.EquipTube00);
        this.GlowEquipBase.addChild(this.EquipTube00_1);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(0.46f, 0.46f, 0.46f);
        GlStateManager.translate(0.0f, 1.77f, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        GlStateManager.enableLighting();
        int j = entity.getBrightnessForRender();
        int k = j % 65536;
        int l = j / 65536;
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, k, l);
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
        int state = ent.getStateEmotion(0);
        this.Collar01.isHidden = !EmotionHelper.checkModelState(1, state);
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowNeck.rotateAngleX = this.Neck.rotateAngleX;
        this.GlowNeck.rotateAngleY = this.Neck.rotateAngleY;
        this.GlowNeck.rotateAngleZ = this.Neck.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.62f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = -0.15f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.BoobL.rotateAngleX = -0.76f;
        this.BoobR.rotateAngleX = -0.76f;
        this.BodyMain.rotateAngleX = 1.6f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = 1.2f;
        this.Butt.offsetY = -0.2f;
        this.Butt.offsetZ = -0.14f;
        this.Skirt01.rotateAngleX = -0.94f;
        this.Skirt01.offsetY = 0.09f;
        this.Skirt01.offsetZ = -0.03f;
        this.Skirt02.rotateAngleX = -0.3f;
        this.Hair01.rotateAngleX = 0.35f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -0.2f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -0.35f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleX = -0.14f;
        this.HairL02.rotateAngleX = 0.17f;
        this.HairR01.rotateAngleX = -0.14f;
        this.HairR02.rotateAngleX = 0.17f;
        this.ArmLeft01.rotateAngleX = -2.9f;
        this.ArmLeft01.rotateAngleY = -0.6981f;
        this.ArmLeft01.rotateAngleZ = 0.08f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.rotateAngleY = 0.0f;
        this.ArmLeft02.rotateAngleZ = 0.0f;
        this.ArmRight01.rotateAngleX = -2.9f;
        this.ArmRight01.rotateAngleY = 0.6981f;
        this.ArmRight01.rotateAngleZ = -0.08f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.LegLeft01.rotateAngleX = -1.9f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.05f;
        this.LegLeft02.rotateAngleX = 0.64f;
        this.LegLeft02.offsetY = 0.0f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegRight01.rotateAngleX = -1.9f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.05f;
        this.LegRight02.rotateAngleX = 0.64f;
        this.LegRight02.offsetY = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        this.GlowEquipBase.isHidden = true;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float angleX = MathHelper.cos(f2 * 0.08f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.4f + f * 0.5f);
        float angleX2 = MathHelper.cos(f2 * 0.08f + 0.8f + f * 0.5f);
        float angleX3 = MathHelper.cos(f2 * 0.08f + 1.2f + f * 0.5f);
        float angleX4 = MathHelper.cos(f2 * 0.08f + 1.6f + f * 0.5f);
        float angleX5 = MathHelper.cos(f2 * 0.08f + 2.0f + f * 0.5f);
        float angleX6 = MathHelper.cos(f2 * 0.08f + 2.4f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1 * 0.5f;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1 * 0.5f;
        float addk1;
        float addk2;
        float headX;
        float headZ;
        float addHL1 = 0.0f;
        float addHR1 = 0.0f;
        float addHL2 = 0.0f;
        float addHR2 = 0.0f;
        int state = ent.getStateEmotion(0);
        boolean collar = EmotionHelper.checkModelState(1, state);
        boolean tails = EmotionHelper.checkModelState(2, state);
        if (ent.getShipDepth(0) > 0.0 || ent.getShipDepth(1) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.025f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 * 0.6f - 0.3f;
        addk2 = angleAdd2 * 0.6f - 0.2f;
        this.Head.rotateAngleX = f4 * 0.014f;
        this.Head.rotateAngleY = f3 * 0.006f;
        this.Head.rotateAngleZ = 0.0f;
        headX = this.Head.rotateAngleX * -0.5f;
        this.Ahoke01.rotateAngleX = angleX1 * 0.07f - 2.01f;
        this.Ahoke01.rotateAngleY = 0.52f;
        this.Ahoke01.rotateAngleZ = 0.0f;
        this.Ahoke02.rotateAngleX = -angleX2 * 0.09f + 1.04f;
        this.Ahoke03.rotateAngleX = angleX3 * 0.15f + 0.78f;
        this.Ahoke04.rotateAngleX = -angleX4 * 0.1f + 0.44f;
        this.Ahoke05.rotateAngleX = -angleX5 * 0.15f - 0.17f;
        this.Ahoke06.rotateAngleX = angleX6 * 0.18f - 0.31f;
        this.Ahoke01a.rotateAngleX = angleX1 * 0.07f - 2.27f;
        this.Ahoke01a.rotateAngleY = -2.62f;
        this.Ahoke01a.rotateAngleZ = 0.0f;
        this.Ahoke02a.rotateAngleX = -angleX2 * 0.09f + 0.79f;
        this.Ahoke03a.rotateAngleX = angleX3 * 0.15f + 1.05f;
        this.Ahoke04a.rotateAngleX = -angleX4 * 0.1f + 0.41f;
        this.Ahoke05a.rotateAngleX = -angleX5 * 0.15f - 0.3f;
        this.Ahoke06a.rotateAngleX = angleX6 * 0.18f - 0.25f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = 0.35f;
        this.Butt.offsetY = 0.0f;
        this.Butt.offsetZ = 0.0f;
        this.BoobL.rotateAngleX = angleX * 0.06f - 0.76f;
        this.BoobL.rotateAngleY = -0.087f;
        this.BoobL.rotateAngleZ = -0.07f;
        this.BoobR.rotateAngleX = angleX * 0.06f - 0.76f;
        this.BoobR.rotateAngleY = 0.087f;
        this.BoobR.rotateAngleZ = 0.07f;
        if (collar) {
            this.BoobL.offsetX = 0.0f;
            this.BoobR.offsetX = 0.0f;
        } else {
            this.BoobL.offsetX = -0.05f;
            this.BoobR.offsetX = 0.05f;
        }
        this.Collar01.rotateAngleX = 0.035f;
        this.Collar03.rotateAngleX = angleX * 0.08f + 0.26f;
        this.Collar04.rotateAngleX = -angleX * 0.08f + 0.45f;
        this.Skirt01.rotateAngleX = -0.087f;
        this.Skirt01.offsetY = 0.0f;
        this.Skirt01.offsetZ = 0.0f;
        this.Skirt02.rotateAngleX = -0.087f;
        this.Skirt02.offsetY = 0.0f;
        this.Skirt02.offsetZ = 0.0f;
        this.Hair01.rotateAngleX = angleX * 0.03f + 0.26f + headX;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -angleX1 * 0.04f - 0.087f + headX;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -angleX2 * 0.07f - 0.052f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = angleAdd2 * 0.8f - 0.05f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft01.rotateAngleZ = angleX * 0.025f - 0.3f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.rotateAngleY = 0.0f;
        this.ArmLeft02.rotateAngleZ = 0.0f;
        this.ArmLeft02.offsetX = 0.0f;
        this.ArmLeft02.offsetZ = 0.0f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.8f + 0.26f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = -angleX * 0.025f + 0.3f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.ArmRight02.offsetX = 0.0f;
        this.ArmRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.087f;
        this.LegLeft02.rotateAngleX = 0.0f;
        this.LegLeft02.rotateAngleY = 0.0f;
        this.LegLeft02.rotateAngleZ = 0.0f;
        this.LegLeft02.offsetX = 0.0f;
        this.LegLeft02.offsetY = 0.0f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.087f;
        this.LegRight02.rotateAngleX = 0.0f;
        this.LegRight02.rotateAngleY = 0.0f;
        this.LegRight02.rotateAngleZ = 0.0f;
        this.LegRight02.offsetX = 0.0f;
        this.LegRight02.offsetY = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        if (tails) {
            this.EquipTBase.isHidden = true;
            this.EquipTBase_1.isHidden = true;
            this.GlowEquipBase.rotateAngleX = 0.3f;
            this.EquipTube00.rotateAngleX = 0.2618f;
            this.EquipTube00.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 0.7f) * 0.1f + 0.61f;
            this.EquipTube00.rotateAngleZ = this.EquipTube00.rotateAngleY * 0.125f;
            this.EquipTube01.rotateAngleX = 0.35f;
            this.EquipTube01.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 1.4f) * 0.125f;
            this.EquipTube01.rotateAngleZ = this.EquipTube01.rotateAngleY * 0.125f;
            this.EquipTube02.rotateAngleX = 0.5235f;
            this.EquipTube02.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 2.1f) * 0.15f;
            this.EquipTube02.rotateAngleZ = this.EquipTube02.rotateAngleY * 0.125f;
            this.EquipTube03.rotateAngleX = 0.61f;
            this.EquipTube03.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 2.8f) * 0.175f;
            this.EquipTube03.rotateAngleZ = this.EquipTube03.rotateAngleY * 0.125f;
            this.EquipTube04.rotateAngleX = 0.6981f;
            this.EquipTube04.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 3.5f) * 0.2f;
            this.EquipTube04.rotateAngleZ = this.EquipTube04.rotateAngleY * 0.125f;
            this.EquipTube05.rotateAngleX = 0.61f;
            this.EquipTube05.rotateAngleY = MathHelper.cos(-f2 * 0.1f + 4.2f) * 0.175f;
            this.EquipTube05.rotateAngleZ = this.EquipTube05.rotateAngleY * 0.125f;
            this.EquipTube00_1.rotateAngleX = this.EquipTube00.rotateAngleX;
            this.EquipTube00_1.rotateAngleY = -this.EquipTube00.rotateAngleY;
            this.EquipTube00_1.rotateAngleZ = this.EquipTube00.rotateAngleZ;
            this.EquipTube01_1.rotateAngleX = this.EquipTube01.rotateAngleX;
            this.EquipTube01_1.rotateAngleY = this.EquipTube01.rotateAngleY;
            this.EquipTube01_1.rotateAngleZ = this.EquipTube01.rotateAngleZ;
            this.EquipTube02_1.rotateAngleX = this.EquipTube02.rotateAngleX;
            this.EquipTube02_1.rotateAngleY = this.EquipTube02.rotateAngleY;
            this.EquipTube02_1.rotateAngleZ = this.EquipTube02.rotateAngleZ;
            this.EquipTube03_1.rotateAngleX = this.EquipTube03.rotateAngleX;
            this.EquipTube03_1.rotateAngleY = this.EquipTube03.rotateAngleY;
            this.EquipTube03_1.rotateAngleZ = this.EquipTube03.rotateAngleZ;
            this.EquipTube04_1.rotateAngleX = this.EquipTube04.rotateAngleX;
            this.EquipTube04_1.rotateAngleY = this.EquipTube04.rotateAngleY;
            this.EquipTube04_1.rotateAngleZ = this.EquipTube04.rotateAngleZ;
            this.EquipTube05_1.rotateAngleX = this.EquipTube05.rotateAngleX;
            this.EquipTube05_1.rotateAngleY = this.EquipTube05.rotateAngleY;
            this.EquipTube05_1.rotateAngleZ = this.EquipTube05.rotateAngleZ;
        }
        if (ent.getIsSprinting() || f1 > 0.9f) {
            if (ent.getIsRiding()) {
                if (f1 > 0.5f) {
                    this.Head.rotateAngleX += 0.4f;
                    this.Hair01.rotateAngleX += 0.1f;
                    this.Hair02.rotateAngleX -= 0.2f;
                    this.Hair03.rotateAngleX -= 0.2f;
                }
            } else {
                GlStateManager.translate(0.0f, 0.06f, 0.0f);
                this.Head.rotateAngleX -= 1.1f;
                this.Hair01.rotateAngleX += 0.6f;
                this.Hair02.rotateAngleX += 0.5f;
                this.Hair03.rotateAngleX += 0.2f;
                this.Ahoke01.rotateAngleX += 0.38f;
                this.Ahoke01.rotateAngleY = 0.7f;
                this.Ahoke01.rotateAngleZ = 0.4f;
                this.Ahoke01a.rotateAngleY = -2.5f;
                this.Ahoke01a.rotateAngleZ = -0.2f;
            }
            this.BodyMain.rotateAngleX = 1.2566f;
            this.BoobL.rotateAngleX = angleAdd2 * 0.1f - 0.83f;
            this.BoobL.rotateAngleZ = -0.07f;
            this.BoobR.rotateAngleX = angleAdd2 * 0.1f - 0.83f;
            this.BoobR.rotateAngleZ = 0.07f;
            this.Collar03.rotateAngleX += angleAdd2 * 0.1f;
            this.Collar04.rotateAngleX += angleAdd2 * 0.1f;
            this.ArmLeft01.rotateAngleX = -2.7f;
            this.ArmLeft01.rotateAngleZ = -0.22f;
            this.ArmRight01.rotateAngleX = -2.7f;
            this.ArmRight01.rotateAngleZ = 0.22f;
            this.LegLeft01.rotateAngleZ = 0.05f;
            this.LegRight01.rotateAngleZ = -0.05f;
            if (tails) {
                this.EquipTBase.isHidden = true;
                this.EquipTBase_1.isHidden = true;
                this.GlowEquipBase.rotateAngleX = 0.3f;
                this.EquipTube00.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 0.7f) * 0.1f + 0.4f;
                this.EquipTube00.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 0.7f) * 0.1f + 0.9f;
                this.EquipTube00.rotateAngleZ = this.EquipTube00.rotateAngleY * 0.125f;
                this.EquipTube01.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 1.4f) * 0.125f;
                this.EquipTube01.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 1.4f) * 0.125f;
                this.EquipTube01.rotateAngleZ = this.EquipTube01.rotateAngleY * 0.125f;
                this.EquipTube02.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 2.1f) * 0.15f;
                this.EquipTube02.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 2.1f) * 0.15f;
                this.EquipTube02.rotateAngleZ = this.EquipTube02.rotateAngleY * 0.125f;
                this.EquipTube03.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 2.8f) * 0.175f;
                this.EquipTube03.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 2.8f) * 0.175f;
                this.EquipTube03.rotateAngleZ = this.EquipTube03.rotateAngleY * 0.125f;
                this.EquipTube04.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 3.5f) * 0.2f;
                this.EquipTube04.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 3.5f) * 0.2f;
                this.EquipTube04.rotateAngleZ = this.EquipTube04.rotateAngleY * 0.125f;
                this.EquipTube05.rotateAngleX = MathHelper.cos(-f2 * 0.4f + 4.2f) * 0.175f;
                this.EquipTube05.rotateAngleY = MathHelper.cos(-f2 * 0.4f + 4.2f) * 0.175f;
                this.EquipTube05.rotateAngleZ = this.EquipTube05.rotateAngleY * 0.125f;
                this.EquipTube00_1.rotateAngleX = this.EquipTube00.rotateAngleX;
                this.EquipTube00_1.rotateAngleY = -this.EquipTube00.rotateAngleY;
                this.EquipTube00_1.rotateAngleZ = -this.EquipTube00.rotateAngleZ;
                this.EquipTube01_1.rotateAngleX = this.EquipTube01.rotateAngleX;
                this.EquipTube01_1.rotateAngleY = this.EquipTube01.rotateAngleY;
                this.EquipTube01_1.rotateAngleZ = this.EquipTube01.rotateAngleZ;
                this.EquipTube02_1.rotateAngleX = this.EquipTube02.rotateAngleX;
                this.EquipTube02_1.rotateAngleY = this.EquipTube02.rotateAngleY;
                this.EquipTube02_1.rotateAngleZ = this.EquipTube02.rotateAngleZ;
                this.EquipTube03_1.rotateAngleX = this.EquipTube03.rotateAngleX;
                this.EquipTube03_1.rotateAngleY = this.EquipTube03.rotateAngleY;
                this.EquipTube03_1.rotateAngleZ = this.EquipTube03.rotateAngleZ;
                this.EquipTube04_1.rotateAngleX = this.EquipTube04.rotateAngleX;
                this.EquipTube04_1.rotateAngleY = this.EquipTube04.rotateAngleY;
                this.EquipTube04_1.rotateAngleZ = this.EquipTube04.rotateAngleZ;
                this.EquipTube05_1.rotateAngleX = this.EquipTube05.rotateAngleX;
                this.EquipTube05_1.rotateAngleY = this.EquipTube05.rotateAngleY;
                this.EquipTube05_1.rotateAngleZ = this.EquipTube05.rotateAngleZ;
            }
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.09f, 0.0f);
            this.Head.rotateAngleX -= 0.6283f;
            this.BodyMain.rotateAngleX = 0.8727f;
            this.Skirt01.rotateAngleX = -0.34f;
            this.Skirt01.offsetY = -0.2f;
            this.Skirt01.offsetZ = 0.03f;
            this.Skirt02.rotateAngleX = -0.27f;
            this.Collar01.rotateAngleX -= 0.35f;
            this.Collar03.rotateAngleX -= 0.3f;
            this.Collar04.rotateAngleX -= 0.35f;
            this.BoobL.rotateAngleX -= 0.2f;
            this.BoobL.rotateAngleZ = -0.04f;
            this.BoobR.rotateAngleX -= 0.2f;
            this.BoobR.rotateAngleZ = 0.04f;
            this.ArmLeft01.rotateAngleX = -0.35f;
            this.ArmLeft01.rotateAngleZ = 0.2618f;
            this.ArmRight01.rotateAngleX = -0.35f;
            this.ArmRight01.rotateAngleZ = -0.2618f;
            addk1 -= 0.94f;
            addk2 -= 0.94f;
            this.LegLeft01.rotateAngleZ = 0.2f;
            this.LegRight01.rotateAngleZ = -0.2f;
            this.Hair01.rotateAngleX = this.Hair01.rotateAngleX * 0.5f + 0.4f;
            this.Hair02.rotateAngleX = this.Hair02.rotateAngleX * 0.75f + 0.25f;
            this.Hair03.rotateAngleX -= 0.1f;
            this.GlowEquipBase.rotateAngleX = -0.2f;
        }
        if (ent.getIsSitting() && !ent.getIsRiding()) {
            if (ent.getTickExisted() % 512 > 256) {
                this.setFaceDamaged(ent);
                GlStateManager.translate(0.0f, -angleX * 0.05f + 0.1f, 0.0f);
                this.Head.rotateAngleX *= 0.5f;
                this.Head.rotateAngleY *= 0.75f;
                this.Head.rotateAngleX += 0.5f;
                this.BodyMain.rotateAngleX = 1.6f;
                this.Skirt01.rotateAngleX = -0.33f;
                this.Skirt01.offsetY = -0.23f;
                this.Skirt02.rotateAngleX = -0.12f;
                this.Skirt02.offsetY = -0.16f;
                this.Ahoke01.rotateAngleX += 0.38f;
                this.Ahoke01.rotateAngleY = 0.8f;
                this.Ahoke01.rotateAngleZ = 0.4f;
                this.Hair01.rotateAngleX -= 0.2f;
                this.Hair02.rotateAngleX -= 0.25f;
                this.Hair03.rotateAngleX -= 0.3f;
                this.ArmLeft01.rotateAngleX = -1.5f;
                this.ArmLeft01.rotateAngleZ = -2.3f;
                this.ArmRight01.rotateAngleX = -1.5f;
                this.ArmRight01.rotateAngleZ = 2.3f;
                addk1 = -1.8f;
                addk2 = -1.8f;
                this.LegLeft01.rotateAngleY = -0.1f - angleX * 0.02f;
                this.LegRight01.rotateAngleY = 0.1f + angleX * 0.02f;
            } else if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 0.52f, 0.0f);
                this.setFaceDamaged(ent);
                this.Head.rotateAngleX = 0.4f;
                this.Skirt01.rotateAngleX = -0.64f;
                this.Skirt01.offsetY = -0.17f;
                this.Skirt01.offsetZ = 0.0f;
                this.Skirt02.rotateAngleX = 0.29f;
                this.Skirt02.offsetY = -0.04f;
                this.Skirt02.offsetZ = 0.02f;
                this.Hair01.rotateAngleX -= 0.2f;
                this.Hair02.rotateAngleX -= 0.15f;
                this.Hair03.rotateAngleX -= 0.1f;
                this.Ahoke01.rotateAngleX -= 0.1f;
                this.ArmLeft01.rotateAngleX = 0.4f;
                this.ArmLeft01.rotateAngleY = -2.9670596f;
                this.ArmLeft01.rotateAngleZ = -2.62f;
                this.ArmLeft02.rotateAngleX = 0.0f;
                this.ArmLeft02.rotateAngleY = 0.0f;
                this.ArmLeft02.rotateAngleZ = 1.0f;
                this.ArmLeft02.offsetX = 0.0f;
                this.ArmLeft02.offsetZ = 0.0f;
                this.ArmRight01.rotateAngleX = 0.5235988f;
                this.ArmRight01.rotateAngleY = 2.9670596f;
                this.ArmRight01.rotateAngleZ = 2.62f;
                this.ArmRight02.rotateAngleX = 0.0f;
                this.ArmRight02.rotateAngleY = 0.0f;
                this.ArmRight02.rotateAngleZ = -1.0f;
                this.ArmRight02.offsetX = 0.0f;
                this.ArmRight02.offsetZ = 0.0f;
                addk1 = -2.4130921f;
                addk2 = -2.268928f;
                this.LegLeft01.rotateAngleY = 0.0f;
                this.LegLeft01.rotateAngleZ = -0.27314404f;
                this.LegLeft02.rotateAngleX = 1.4570009f;
                this.LegLeft02.rotateAngleY = 0.0f;
                this.LegLeft02.rotateAngleZ = 0.0f;
                this.LegRight01.rotateAngleY = 0.0f;
                this.LegRight01.rotateAngleZ = 0.22759093f;
                this.LegRight02.rotateAngleX = 1.0471976f;
                this.LegRight02.rotateAngleY = 0.0f;
                this.LegRight02.rotateAngleZ = 0.0f;
            } else {
                GlStateManager.translate(0.0f, 0.495f, 0.0f);
                this.Head.rotateAngleX -= 0.7f;
                this.BodyMain.rotateAngleX = 0.35f;
                this.Hair01.rotateAngleX += 0.3f;
                this.Hair02.rotateAngleX += 0.3f;
                this.Hair03.rotateAngleX += 0.3f;
                this.Skirt01.rotateAngleX = -0.32f;
                this.Skirt01.offsetY = -0.05f;
                this.Skirt02.rotateAngleX = -0.21f;
                this.Collar01.rotateAngleX += 0.1f;
                this.Collar03.rotateAngleX += 0.1f;
                this.ArmLeft01.rotateAngleX = -0.5235988f;
                this.ArmLeft01.rotateAngleY = 0.0f;
                this.ArmLeft01.rotateAngleZ = 0.34906584f;
                this.ArmLeft02.rotateAngleX = 0.0f;
                this.ArmLeft02.rotateAngleZ = 0.0f;
                this.ArmLeft02.offsetX = 0.0f;
                this.ArmLeft02.offsetZ = 0.0f;
                this.ArmRight01.rotateAngleX = -0.5235988f;
                this.ArmRight01.rotateAngleY = 0.0f;
                this.ArmRight01.rotateAngleZ = -0.34906584f;
                this.ArmRight02.rotateAngleX = 0.0f;
                this.ArmRight02.rotateAngleZ = 0.0f;
                this.ArmRight02.offsetX = 0.0f;
                this.ArmRight02.offsetZ = 0.0f;
                addk1 = -1.4486233f;
                addk2 = -1.4486233f;
                this.LegLeft01.rotateAngleY = -0.5235988f;
                this.LegLeft01.rotateAngleZ = -1.3962634f;
                this.LegLeft02.rotateAngleX = 2.1816616f;
                this.LegLeft02.rotateAngleY = 0.0f;
                this.LegLeft02.rotateAngleZ = 0.0f;
                this.LegLeft02.offsetX = 0.0f;
                this.LegLeft02.offsetZ = 0.37f;
                this.LegRight01.rotateAngleY = 0.5235988f;
                this.LegRight01.rotateAngleZ = 1.3962634f;
                this.LegRight02.rotateAngleX = 2.1816616f;
                this.LegRight02.rotateAngleY = 0.0f;
                this.LegRight02.rotateAngleZ = 0.0f;
                this.LegRight02.offsetX = 0.0f;
                this.LegRight02.offsetZ = 0.37f;
            }
        }
        if (ent.getIsRiding()) {
            if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
                if (ent.getIsSitting()) {
                    GlStateManager.translate(0.0f, 0.4f, 0.0f);
                    this.Head.rotateAngleX -= 0.7f;
                    this.BodyMain.rotateAngleX = 0.35f;
                    this.Hair01.rotateAngleX += 0.3f;
                    this.Hair02.rotateAngleX += 0.3f;
                    this.Hair03.rotateAngleX += 0.3f;
                    this.Skirt01.rotateAngleX = -0.32f;
                    this.Skirt01.offsetY = -0.05f;
                    this.Skirt02.rotateAngleX = -0.21f;
                    this.Collar01.rotateAngleX += 0.1f;
                    this.Collar03.rotateAngleX += 0.1f;
                    this.ArmLeft01.rotateAngleX = -0.8f;
                    this.ArmLeft01.rotateAngleY = 0.0f;
                    this.ArmLeft01.rotateAngleZ = -0.2f;
                    this.ArmLeft02.rotateAngleX = 0.0f;
                    this.ArmLeft02.rotateAngleZ = 0.0f;
                    this.ArmLeft02.offsetX = 0.0f;
                    this.ArmLeft02.offsetZ = 0.0f;
                    this.ArmRight01.rotateAngleX = -0.8f;
                    this.ArmRight01.rotateAngleY = 0.0f;
                    this.ArmRight01.rotateAngleZ = 0.2f;
                    this.ArmRight02.rotateAngleX = 0.0f;
                    this.ArmRight02.rotateAngleZ = 0.0f;
                    this.ArmRight02.offsetX = 0.0f;
                    this.ArmRight02.offsetZ = 0.0f;
                    addk1 = -1.4486233f;
                    addk2 = -1.4486233f;
                    this.LegLeft01.rotateAngleY = -0.5235988f;
                    this.LegLeft01.rotateAngleZ = -0.2f;
                    this.LegLeft02.rotateAngleX = 0.8f;
                    this.LegRight01.rotateAngleY = 0.5235988f;
                    this.LegRight01.rotateAngleZ = 0.2f;
                    this.LegRight02.rotateAngleX = 0.8f;
                } else {
                    GlStateManager.translate(0.0f, 0.22f, 0.0f);
                    this.Head.rotateAngleX *= 0.5f;
                    this.Head.rotateAngleY *= 0.75f;
                    this.Head.rotateAngleX -= 1.0f;
                    this.BodyMain.rotateAngleX = 1.0f;
                    this.Skirt01.rotateAngleX = -0.33f;
                    this.Skirt01.offsetY = -0.23f;
                    this.Skirt02.rotateAngleX = -0.12f;
                    this.Skirt02.offsetY = -0.16f;
                    this.Collar01.rotateAngleX -= 0.5f;
                    this.Collar03.rotateAngleX -= 0.5f;
                    this.Collar04.rotateAngleX -= 0.5f;
                    this.Ahoke01.rotateAngleX += 0.38f;
                    this.Ahoke01.rotateAngleY = 0.8f;
                    this.Ahoke01.rotateAngleZ = 0.4f;
                    this.Hair01.rotateAngleX += 0.5f;
                    this.Hair02.rotateAngleX += 0.65f;
                    this.Hair03.rotateAngleX += 0.5f;
                    addHL1 = -0.6f;
                    addHR1 = -0.6f;
                    addHL2 = -0.5f;
                    addHR2 = -0.5f;
                    this.ArmLeft01.rotateAngleX = -1.4f;
                    this.ArmLeft01.rotateAngleY = -0.0f;
                    this.ArmRight01.rotateAngleX = -1.4f;
                    this.ArmRight01.rotateAngleY = 0.0f;
                    addk1 = -1.7f;
                    addk2 = -1.7f;
                    this.LegLeft01.rotateAngleY = -0.2f;
                    this.LegRight01.rotateAngleY = 0.2f;
                }
            } else if (ent.getIsSitting()) {
                if (ent.getStateEmotion(1) == 4) {
                    this.setFaceDamaged(ent);
                    GlStateManager.translate(0.0f, -angleX * 0.05f + 0.1f, 0.0f);
                    this.Head.rotateAngleX *= 0.5f;
                    this.Head.rotateAngleY *= 0.75f;
                    this.Head.rotateAngleX += 0.5f;
                    this.BodyMain.rotateAngleX = 1.6f;
                    this.Skirt01.rotateAngleX = -0.33f;
                    this.Skirt01.offsetY = -0.23f;
                    this.Skirt02.rotateAngleX = -0.12f;
                    this.Skirt02.offsetY = -0.16f;
                    this.Ahoke01.rotateAngleX += 0.38f;
                    this.Ahoke01.rotateAngleY = 0.8f;
                    this.Ahoke01.rotateAngleZ = 0.4f;
                    this.Hair01.rotateAngleX -= 0.2f;
                    this.Hair02.rotateAngleX -= 0.25f;
                    this.Hair03.rotateAngleX -= 0.3f;
                    this.ArmLeft01.rotateAngleX = -1.5f;
                    this.ArmLeft01.rotateAngleZ = -2.3f;
                    this.ArmRight01.rotateAngleX = -1.5f;
                    this.ArmRight01.rotateAngleZ = 2.3f;
                    addk1 = -1.8f;
                    addk2 = -1.8f;
                    this.LegLeft01.rotateAngleY = -0.1f - angleX * 0.02f;
                    this.LegRight01.rotateAngleY = 0.1f + angleX * 0.02f;
                } else {
                    GlStateManager.translate(0.0f, 0.52f, 0.0f);
                    this.setFaceDamaged(ent);
                    this.Head.rotateAngleX = 0.4f;
                    this.Skirt01.rotateAngleX = -0.64f;
                    this.Skirt01.offsetY = -0.17f;
                    this.Skirt01.offsetZ = 0.0f;
                    this.Skirt02.rotateAngleX = 0.29f;
                    this.Skirt02.offsetY = -0.04f;
                    this.Skirt02.offsetZ = 0.02f;
                    this.Hair01.rotateAngleX -= 0.2f;
                    this.Hair02.rotateAngleX -= 0.15f;
                    this.Hair03.rotateAngleX -= 0.1f;
                    this.Ahoke01.rotateAngleX -= 0.1f;
                    this.ArmLeft01.rotateAngleX = 0.4f;
                    this.ArmLeft01.rotateAngleY = -2.9670596f;
                    this.ArmLeft01.rotateAngleZ = -2.62f;
                    this.ArmLeft02.rotateAngleX = 0.0f;
                    this.ArmLeft02.rotateAngleY = 0.0f;
                    this.ArmLeft02.rotateAngleZ = 1.0f;
                    this.ArmLeft02.offsetX = 0.0f;
                    this.ArmLeft02.offsetZ = 0.0f;
                    this.ArmRight01.rotateAngleX = 0.5235988f;
                    this.ArmRight01.rotateAngleY = 2.9670596f;
                    this.ArmRight01.rotateAngleZ = 2.62f;
                    this.ArmRight02.rotateAngleX = 0.0f;
                    this.ArmRight02.rotateAngleY = 0.0f;
                    this.ArmRight02.rotateAngleZ = -1.0f;
                    this.ArmRight02.offsetX = 0.0f;
                    this.ArmRight02.offsetZ = 0.0f;
                    addk1 = -2.4130921f;
                    addk2 = -2.268928f;
                    this.LegLeft01.rotateAngleY = 0.0f;
                    this.LegLeft01.rotateAngleZ = -0.27314404f;
                    this.LegLeft02.rotateAngleX = 1.4570009f;
                    this.LegLeft02.rotateAngleY = 0.0f;
                    this.LegLeft02.rotateAngleZ = 0.0f;
                    this.LegRight01.rotateAngleY = 0.0f;
                    this.LegRight01.rotateAngleZ = 0.22759093f;
                    this.LegRight02.rotateAngleX = 1.0471976f;
                    this.LegRight02.rotateAngleY = 0.0f;
                    this.LegRight02.rotateAngleZ = 0.0f;
                }
            } else {
                GlStateManager.translate(0.0f, 0.495f, 0.0f);
                this.Head.rotateAngleX -= 0.7f;
                this.BodyMain.rotateAngleX = 0.35f;
                this.Hair01.rotateAngleX += 0.3f;
                this.Hair02.rotateAngleX += 0.3f;
                this.Hair03.rotateAngleX += 0.3f;
                this.Skirt01.rotateAngleX = -0.32f;
                this.Skirt01.offsetY = -0.05f;
                this.Skirt02.rotateAngleX = -0.21f;
                this.Collar01.rotateAngleX += 0.1f;
                this.Collar03.rotateAngleX += 0.1f;
                this.ArmLeft01.rotateAngleX = -0.5235988f;
                this.ArmLeft01.rotateAngleY = 0.0f;
                this.ArmLeft01.rotateAngleZ = 0.34906584f;
                this.ArmLeft02.rotateAngleX = 0.0f;
                this.ArmLeft02.rotateAngleZ = 0.0f;
                this.ArmLeft02.offsetX = 0.0f;
                this.ArmLeft02.offsetZ = 0.0f;
                this.ArmRight01.rotateAngleX = -0.5235988f;
                this.ArmRight01.rotateAngleY = 0.0f;
                this.ArmRight01.rotateAngleZ = -0.34906584f;
                this.ArmRight02.rotateAngleX = 0.0f;
                this.ArmRight02.rotateAngleZ = 0.0f;
                this.ArmRight02.offsetX = 0.0f;
                this.ArmRight02.offsetZ = 0.0f;
                addk1 = -1.4486233f;
                addk2 = -1.4486233f;
                this.LegLeft01.rotateAngleY = -0.5235988f;
                this.LegLeft01.rotateAngleZ = -1.3962634f;
                this.LegLeft02.rotateAngleX = 2.1816616f;
                this.LegLeft02.rotateAngleY = 0.0f;
                this.LegLeft02.rotateAngleZ = 0.0f;
                this.LegLeft02.offsetX = 0.0f;
                this.LegLeft02.offsetZ = 0.37f;
                this.LegRight01.rotateAngleY = 0.5235988f;
                this.LegRight01.rotateAngleZ = 1.3962634f;
                this.LegRight02.rotateAngleX = 2.1816616f;
                this.LegRight02.rotateAngleY = 0.0f;
                this.LegRight02.rotateAngleZ = 0.0f;
                this.LegRight02.offsetX = 0.0f;
                this.LegRight02.offsetZ = 0.37f;
            }
        }
        if (ent.getAttackTick() > 0 && ent.getAttackTick() > 14) {
            if (ent.getIsRiding()) {
                GlStateManager.translate(0.0f, 0.02f, 0.0f);
                this.Head.rotateAngleX *= 0.5f;
                this.Head.rotateAngleY *= 0.75f;
                this.Head.rotateAngleX -= 0.5f;
                this.BodyMain.rotateAngleX = 1.1f;
                this.Collar01.rotateAngleX -= 0.2f;
                this.Ahoke01.rotateAngleX += 0.38f;
                this.Ahoke01.rotateAngleY = 0.8f;
                this.Ahoke01.rotateAngleZ = 0.4f;
                this.Hair01.rotateAngleX += 0.2f;
                this.Hair02.rotateAngleX += -0.1f;
                this.Hair03.rotateAngleX += -0.1f;
                addHL1 = -0.6f;
                addHR1 = -0.6f;
                addHL2 = -0.5f;
                addHR2 = -0.5f;
                addk1 = -1.8f;
                addk2 = -1.8f;
                this.LegLeft01.rotateAngleY = -0.1f;
                this.LegRight01.rotateAngleY = 0.1f;
                this.GlowEquipBase.rotateAngleX = 0.5f;
            } else {
                GlStateManager.translate(0.0f, 0.22f, 0.0f);
                this.Head.rotateAngleX *= 0.5f;
                this.Head.rotateAngleY *= 0.75f;
                this.Head.rotateAngleX -= 1.6f;
                this.BodyMain.rotateAngleX = 1.6f;
                this.Collar01.rotateAngleX -= 0.5f;
                this.Collar03.rotateAngleX -= 0.5f;
                this.Collar04.rotateAngleX -= 0.5f;
                this.Ahoke01.rotateAngleX += 0.38f;
                this.Ahoke01.rotateAngleY = 0.8f;
                this.Ahoke01.rotateAngleZ = 0.4f;
                this.Hair01.rotateAngleX += 1.0f;
                this.Hair02.rotateAngleX += 0.6f;
                this.Hair03.rotateAngleX += 0.7f;
                addHL1 = -0.6f;
                addHR1 = -0.6f;
                addHL2 = -0.5f;
                addHR2 = -0.5f;
                addk1 = -2.2f;
                addk2 = -2.2f;
                this.LegLeft01.rotateAngleY = -0.1f;
                this.LegRight01.rotateAngleY = 0.1f;
                this.GlowEquipBase.rotateAngleX = 0.0f;
            }
            this.Skirt01.rotateAngleX = -0.33f;
            this.Skirt01.offsetY = -0.23f;
            this.Skirt02.rotateAngleX = -0.12f;
            this.Skirt02.offsetY = -0.16f;
            this.ArmLeft01.rotateAngleX = -1.6f;
            this.ArmLeft01.rotateAngleY = -0.2f;
            this.ArmRight01.rotateAngleX = -1.2f;
            this.ArmRight01.rotateAngleY = 1.2f;
        }
        this.setTorpedo(ent.getAttackTick(), tails);
        float f6 = ent.getSwingTime(f2 % 1.0f);
        if (f6 != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX = -0.3f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = -0.1f;
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
            this.ArmRight02.rotateAngleX = 0.0f;
            this.ArmRight02.rotateAngleZ = 0.0f;
        }
        headX = this.Head.rotateAngleX * -0.5f;
        this.HairL01.rotateAngleX = angleX * 0.02f + headX - 0.19f + addHL1;
        this.HairL02.rotateAngleX = -angleX1 * 0.04f + headX + 0.17f + addHL2;
        this.HairR01.rotateAngleX = angleX * 0.02f + headX - 0.19f + addHR1;
        this.HairR02.rotateAngleX = -angleX1 * 0.04f + headX + 0.17f + addHR2;
        this.Hair01.rotateAngleZ = headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair02.rotateAngleZ = headZ;
        this.Hair03.rotateAngleZ = headZ;
        this.HairL01.rotateAngleZ = headZ - 0.087f;
        this.HairL02.rotateAngleZ = headZ + 0.087f;
        this.HairR01.rotateAngleZ = headZ + 0.087f;
        this.HairR02.rotateAngleZ = headZ - 0.052f;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }

    private void setTorpedo(int attackTime, boolean showTails) {
        if (attackTime <= 14) {
            this.GlowEquipBase.isHidden = !showTails;
            this.EquipTBase.isHidden = true;
            this.EquipTBase_1.isHidden = true;
            return;
        }
        this.EquipTube00.rotateAngleX = 0.2618f;
        this.EquipTube00.rotateAngleY = 0.61f;
        this.EquipTube00.rotateAngleZ = 0.0f;
        this.EquipTube01.rotateAngleX = 0.35f;
        this.EquipTube01.rotateAngleY = 0.0f;
        this.EquipTube01.rotateAngleZ = 0.0f;
        this.EquipTube02.rotateAngleX = 0.5235f;
        this.EquipTube02.rotateAngleY = 0.0f;
        this.EquipTube02.rotateAngleZ = 0.0f;
        this.EquipTube03.rotateAngleX = 0.61f;
        this.EquipTube03.rotateAngleY = 0.0f;
        this.EquipTube03.rotateAngleZ = 0.0f;
        this.EquipTube04.rotateAngleX = 0.6981f;
        this.EquipTube04.rotateAngleY = 0.0f;
        this.EquipTube04.rotateAngleZ = 0.0f;
        this.EquipTube05.rotateAngleX = 0.61f;
        this.EquipTube05.rotateAngleY = 0.0f;
        this.EquipTube05.rotateAngleZ = 0.0f;
        this.EquipTube00_1.rotateAngleX = 0.2618f;
        this.EquipTube00_1.rotateAngleY = -0.61f;
        this.EquipTube00_1.rotateAngleZ = 0.0f;
        this.EquipTube01_1.rotateAngleX = 0.35f;
        this.EquipTube01_1.rotateAngleY = 0.0f;
        this.EquipTube01_1.rotateAngleZ = 0.0f;
        this.EquipTube02_1.rotateAngleX = 0.5235f;
        this.EquipTube02_1.rotateAngleY = 0.0f;
        this.EquipTube02_1.rotateAngleZ = 0.0f;
        this.EquipTube03_1.rotateAngleX = 0.61f;
        this.EquipTube03_1.rotateAngleY = 0.0f;
        this.EquipTube03_1.rotateAngleZ = 0.0f;
        this.EquipTube04_1.rotateAngleX = 0.6981f;
        this.EquipTube04_1.rotateAngleY = 0.0f;
        this.EquipTube04_1.rotateAngleZ = 0.0f;
        this.EquipTube05_1.rotateAngleX = 0.61f;
        this.EquipTube05_1.rotateAngleY = 0.0f;
        this.EquipTube05_1.rotateAngleZ = 0.0f;
        this.EquipTBase.isHidden = false;
        this.EquipTBase_1.isHidden = false;
        this.GlowEquipBase.isHidden = false;
        switch (attackTime) {
            case 50: {
                this.EquipTBase.offsetY = -2.73f;
                this.EquipTBase_1.offsetY = -2.73f;
                break;
            }
            case 49: {
                this.EquipTBase.offsetY = -2.71f;
                this.EquipTBase_1.offsetY = -2.71f;
                break;
            }
            case 48: {
                this.EquipTBase.offsetY = -2.69f;
                this.EquipTBase_1.offsetY = -2.69f;
                break;
            }
            case 47: {
                this.EquipTBase.offsetY = -2.375f;
                this.EquipTBase_1.offsetY = -2.375f;
                break;
            }
            case 46: {
                this.EquipTBase.offsetY = -2.06f;
                this.EquipTBase_1.offsetY = -2.06f;
                break;
            }
            case 45: {
                this.EquipTBase.offsetY = -1.75f;
                this.EquipTBase_1.offsetY = -1.75f;
                break;
            }
            case 44: {
                this.EquipTBase.offsetY = -1.44f;
                this.EquipTBase_1.offsetY = -1.44f;
                break;
            }
            case 43: {
                this.EquipTBase.offsetY = -1.125f;
                this.EquipTBase_1.offsetY = -1.125f;
                break;
            }
            case 42: {
                this.EquipTBase.offsetY = -0.81f;
                this.EquipTBase_1.offsetY = -0.81f;
                break;
            }
            case 41: {
                this.EquipTBase.offsetY = -0.5f;
                this.EquipTBase_1.offsetY = -0.5f;
                break;
            }
            case 40: {
                this.EquipTBase.offsetY = -0.19f;
                this.EquipTBase_1.offsetY = -0.19f;
                break;
            }
            case 39: {
                this.EquipTBase.offsetY = -0.095f;
                this.EquipTBase_1.offsetY = -0.095f;
                break;
            }
            default: {
                this.EquipTBase.offsetY = 0.0f;
                this.EquipTBase_1.offsetY = 0.0f;
            }
        }
        switch (attackTime) {
            case 49: 
            case 50: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = true;
                this.EquipT06_1.isHidden = true;
                this.EquipT05.isHidden = true;
                this.EquipT05_1.isHidden = true;
                this.EquipT04.isHidden = true;
                this.EquipT04_1.isHidden = true;
                this.EquipT03.isHidden = true;
                this.EquipT03_1.isHidden = true;
                this.EquipT02.isHidden = true;
                this.EquipT02_1.isHidden = true;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            case 47: 
            case 48: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = true;
                this.EquipT05_1.isHidden = true;
                this.EquipT04.isHidden = true;
                this.EquipT04_1.isHidden = true;
                this.EquipT03.isHidden = true;
                this.EquipT03_1.isHidden = true;
                this.EquipT02.isHidden = true;
                this.EquipT02_1.isHidden = true;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            case 45: 
            case 46: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = false;
                this.EquipT05_1.isHidden = false;
                this.EquipT04.isHidden = true;
                this.EquipT04_1.isHidden = true;
                this.EquipT03.isHidden = true;
                this.EquipT03_1.isHidden = true;
                this.EquipT02.isHidden = true;
                this.EquipT02_1.isHidden = true;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            case 43: 
            case 44: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = false;
                this.EquipT05_1.isHidden = false;
                this.EquipT04.isHidden = false;
                this.EquipT04_1.isHidden = false;
                this.EquipT03.isHidden = true;
                this.EquipT03_1.isHidden = true;
                this.EquipT02.isHidden = true;
                this.EquipT02_1.isHidden = true;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            case 41: 
            case 42: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = false;
                this.EquipT05_1.isHidden = false;
                this.EquipT04.isHidden = false;
                this.EquipT04_1.isHidden = false;
                this.EquipT03.isHidden = false;
                this.EquipT03_1.isHidden = false;
                this.EquipT02.isHidden = true;
                this.EquipT02_1.isHidden = true;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            case 39: 
            case 40: {
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = false;
                this.EquipT05_1.isHidden = false;
                this.EquipT04.isHidden = false;
                this.EquipT04_1.isHidden = false;
                this.EquipT03.isHidden = false;
                this.EquipT03_1.isHidden = false;
                this.EquipT02.isHidden = false;
                this.EquipT02_1.isHidden = false;
                this.EquipT01.isHidden = true;
                this.EquipT01_1.isHidden = true;
                break;
            }
            default: {
                if (attackTime >= 39) break;
                this.EquipT07.isHidden = false;
                this.EquipT07_1.isHidden = false;
                this.EquipT06.isHidden = false;
                this.EquipT06_1.isHidden = false;
                this.EquipT05.isHidden = false;
                this.EquipT05_1.isHidden = false;
                this.EquipT04.isHidden = false;
                this.EquipT04_1.isHidden = false;
                this.EquipT03.isHidden = false;
                this.EquipT03_1.isHidden = false;
                this.EquipT02.isHidden = false;
                this.EquipT02_1.isHidden = false;
                this.EquipT01.isHidden = false;
                this.EquipT01_1.isHidden = false;
            }
        }
    }
}
