package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.BasicEntityMount;
import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelCarrierHime
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer Butt;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer Cloth01;
    private final ModelRenderer Cloth02;
    private final ModelRenderer Head;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairL01;
    private final ModelRenderer HairR01;
    private final ModelRenderer HairL02;
    private final ModelRenderer HairR02;
    private final ModelRenderer Hair01;
    private final ModelRenderer Hair04;
    private final ModelRenderer Hair02;
    private final ModelRenderer Hair03;
    private final ModelRenderer Hair05;
    private final ModelRenderer Hair06;
    private final ModelRenderer Hair07;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer Skirt01;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer LegLeft01a;
    private final ModelRenderer LegLeft01b;
    private final ModelRenderer ShoesL01;
    private final ModelRenderer ShoesL02;
    private final ModelRenderer ShoesL03;
    private final ModelRenderer ShoesL04;
    private final ModelRenderer Skirt02;
    private final ModelRenderer LegRight01a;
    private final ModelRenderer LegRight01b;
    private final ModelRenderer LegRight02;
    private final ModelRenderer ShoesR01;
    private final ModelRenderer ShoesR02;
    private final ModelRenderer ShoesR03;
    private final ModelRenderer ShoesR04;
    private final ModelRenderer ArmRight01a;
    private final ModelRenderer ArmRight01b;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer EquipSR01;
    private final ModelRenderer EquipSR02;
    private final ModelRenderer EquipSR04;
    private final ModelRenderer EquipSR03;
    private final ModelRenderer EquipSR05;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmLeft01a;
    private final ModelRenderer ArmLeft01b;
    private final ModelRenderer EquipSL01;
    private final ModelRenderer EquipSL02;
    private final ModelRenderer EquipSL04;
    private final ModelRenderer EquipSL03;
    private final ModelRenderer EquipSL05;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowBodyMain2;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;
    private final ModelRenderer GlowArmLeft01;
    private final ModelRenderer GlowArmLeft02;
    private final ModelRenderer GlowArmRight01;
    private final ModelRenderer GlowArmRight02;

    public ModelCarrierHime() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.scale = 0.47f;
        this.offsetY = 1.7f;
        this.offsetItem = new float[]{0.06f, 0.98f, -0.06f};
        this.offsetBlock = new float[]{0.06f, 0.98f, -0.06f};
        this.setDefaultFaceModel();
        this.LegLeft02 = new ModelRenderer(this, 92, 2);
        this.LegLeft02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegLeft02.addBox(-3.0f, 0.0f, 0.0f, 6, 3, 6, 0.0f);
        this.ShoesL03 = new ModelRenderer(this, 95, 0);
        this.ShoesL03.setRotationPoint(0.0f, 2.4f, -0.7f);
        this.ShoesL03.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.ShoesL03, -0.13962634f, 0.0f, 0.0f);
        this.Butt = new ModelRenderer(this, 52, 61);
        this.Butt.setRotationPoint(0.0f, 4.0f, 1.3f);
        this.Butt.addBox(-7.5f, 0.0f, -5.7f, 15, 8, 8, 0.0f);
        this.setRotateAngle(this.Butt, 0.34906584f, 0.0f, 0.0f);
        this.LegRight02 = new ModelRenderer(this, 103, 0);
        this.LegRight02.mirror = true;
        this.LegRight02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegRight02.addBox(-3.0f, 0.0f, 0.0f, 6, 3, 6, 0.0f);
        this.Hair = new ModelRenderer(this, 50, 77);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.0f);
        this.Hair.addBox(-8.0f, -8.0f, -7.2f, 16, 16, 8, 0.0f);
        this.ArmLeft01b = new ModelRenderer(this, 90, 6);
        this.ArmLeft01b.mirror = true;
        this.ArmLeft01b.setRotationPoint(0.5f, 9.0f, -0.1f);
        this.ArmLeft01b.addBox(-3.0f, 0.0f, -3.0f, 6, 4, 6, 0.0f);
        this.setRotateAngle(this.ArmLeft01b, 0.20943952f, 0.0f, 0.0f);
        this.ShoesR04 = new ModelRenderer(this, 104, 13);
        this.ShoesR04.mirror = true;
        this.ShoesR04.setRotationPoint(0.0f, 2.2f, -0.3f);
        this.ShoesR04.addBox(-3.0f, 0.0f, -3.0f, 6, 6, 6, 0.0f);
        this.setRotateAngle(this.ShoesR04, -0.20943952f, 0.0f, 0.0f);
        this.LegRight01 = new ModelRenderer(this, 0, 83);
        this.LegRight01.mirror = true;
        this.LegRight01.setRotationPoint(-4.8f, 5.5f, -2.6f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegRight01, -0.17453292f, 0.0f, -0.10471976f);
        this.LegLeft01a = new ModelRenderer(this, 92, 2);
        this.LegLeft01a.setRotationPoint(0.0f, 8.6f, -0.2f);
        this.LegLeft01a.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.LegLeft01a, 0.20943952f, 0.0f, 0.0f);
        this.ShoesL04 = new ModelRenderer(this, 104, 13);
        this.ShoesL04.setRotationPoint(0.0f, 2.2f, -0.3f);
        this.ShoesL04.addBox(-3.0f, 0.0f, -3.0f, 6, 6, 6, 0.0f);
        this.setRotateAngle(this.ShoesL04, -0.20943952f, 0.0f, 0.0f);
        this.Skirt01 = new ModelRenderer(this, 46, 34);
        this.Skirt01.setRotationPoint(0.0f, 2.9f, 0.0f);
        this.Skirt01.addBox(-8.5f, 0.0f, -6.0f, 17, 4, 9, 0.0f);
        this.setRotateAngle(this.Skirt01, -0.13962634f, 0.0f, 0.0f);
        this.Ahoke = new ModelRenderer(this, 106, 31);
        this.Ahoke.setRotationPoint(0.0f, -7.0f, -6.0f);
        this.Ahoke.addBox(0.0f, -6.0f, -10.5f, 0, 11, 11, 0.0f);
        this.setRotateAngle(this.Ahoke, 0.20943952f, 0.6981317f, 0.0f);
        this.EquipSR03 = new ModelRenderer(this, 0, 0);
        this.EquipSR03.setRotationPoint(0.0f, 16.0f, 0.0f);
        this.EquipSR03.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.EquipSL01 = new ModelRenderer(this, 0, 0);
        this.EquipSL01.setRotationPoint(-3.0f, 10.5f, -6.0f);
        this.EquipSL01.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.setRotateAngle(this.EquipSL01, -1.5707964f, 0.0f, 1.5707964f);
        this.BodyMain = new ModelRenderer(this, 0, 104);
        this.BodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 17, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.10471976f, 0.0f, 0.0f);
        this.Cloth01 = new ModelRenderer(this, 0, 22);
        this.Cloth01.setRotationPoint(0.0f, -11.5f, -0.3f);
        this.Cloth01.addBox(-7.0f, 0.0f, -4.0f, 14, 5, 8, 0.0f);
        this.HairR02 = new ModelRenderer(this, 86, 101);
        this.HairR02.mirror = true;
        this.HairR02.setRotationPoint(0.2f, 7.0f, 0.0f);
        this.HairR02.addBox(-1.0f, 0.0f, 0.0f, 2, 9, 4, 0.0f);
        this.setRotateAngle(this.HairR02, 0.17453292f, 0.0f, -0.05235988f);
        this.ShoesL01 = new ModelRenderer(this, 97, 2);
        this.ShoesL01.setRotationPoint(0.0f, 2.0f, 3.0f);
        this.ShoesL01.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.setRotateAngle(this.ShoesL01, 0.13962634f, 0.0f, 0.0f);
        this.BoobL = new ModelRenderer(this, 33, 101);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.5f, -8.1f, -3.7f);
        this.BoobL.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobL, -0.6981317f, 0.08726646f, 0.08726646f);
        this.EquipSR04 = new ModelRenderer(this, 107, 0);
        this.EquipSR04.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipSR04.addBox(-0.5f, -9.0f, -0.5f, 1, 9, 1, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 4, 85);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 8, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, 0.34906584f, 0.0f, -0.2617994f);
        this.ArmRight02 = new ModelRenderer(this, 93, 0);
        this.ArmRight02.mirror = true;
        this.ArmRight02.setRotationPoint(-3.0f, 12.0f, 2.5f);
        this.ArmRight02.addBox(0.0f, 0.0f, -5.0f, 5, 12, 5, 0.0f);
        this.HairMain = new ModelRenderer(this, 0, 57);
        this.HairMain.setRotationPoint(0.0f, -15.0f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 12, 10, 0.0f);
        this.Cloth02 = new ModelRenderer(this, 36, 93);
        this.Cloth02.setRotationPoint(0.3f, -4.5f, -6.5f);
        this.Cloth02.addBox(-3.5f, 0.0f, 0.0f, 7, 8, 0, 0.0f);
        this.Skirt02 = new ModelRenderer(this, 42, 47);
        this.Skirt02.setRotationPoint(0.0f, 2.8f, -0.5f);
        this.Skirt02.addBox(-9.0f, 0.0f, -6.0f, 18, 4, 10, 0.0f);
        this.setRotateAngle(this.Skirt02, -0.08726646f, 0.0f, 0.0f);
        this.HairR01 = new ModelRenderer(this, 86, 101);
        this.HairR01.mirror = true;
        this.HairR01.setRotationPoint(-7.0f, 3.0f, -5.5f);
        this.HairR01.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 4, 0.0f);
        this.setRotateAngle(this.HairR01, -0.13962634f, 0.17453292f, 0.08726646f);
        this.Hair02 = new ModelRenderer(this, 0, 58);
        this.Hair02.setRotationPoint(0.0f, 13.5f, 5.5f);
        this.Hair02.addBox(-8.0f, 0.0f, -5.0f, 16, 16, 8, 0.0f);
        this.setRotateAngle(this.Hair02, -0.08726646f, 0.0f, 0.0f);
        this.ShoesR01 = new ModelRenderer(this, 100, 0);
        this.ShoesR01.mirror = true;
        this.ShoesR01.setRotationPoint(0.0f, 2.0f, 3.0f);
        this.ShoesR01.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.setRotateAngle(this.ShoesR01, 0.13962634f, 0.0f, 0.0f);
        this.EquipSR01 = new ModelRenderer(this, 0, 0);
        this.EquipSR01.setRotationPoint(3.0f, 10.5f, -6.0f);
        this.EquipSR01.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.setRotateAngle(this.EquipSR01, -1.5707964f, 0.0f, 1.5707964f);
        this.Hair06 = new ModelRenderer(this, 109, 28);
        this.Hair06.setRotationPoint(2.5f, 4.0f, 0.0f);
        this.Hair06.addBox(-2.0f, 0.0f, -2.5f, 4, 7, 5, 0.0f);
        this.setRotateAngle(this.Hair06, 0.20943952f, 0.0f, 0.13962634f);
        this.Hair03 = new ModelRenderer(this, 0, 35);
        this.Hair03.setRotationPoint(0.0f, 12.5f, -0.1f);
        this.Hair03.addBox(-8.0f, 0.0f, -4.5f, 16, 15, 7, 0.0f);
        this.setRotateAngle(this.Hair03, -0.13962634f, 0.0f, 0.0f);
        this.LegRight01a = new ModelRenderer(this, 95, 0);
        this.LegRight01a.mirror = true;
        this.LegRight01a.setRotationPoint(0.0f, 8.6f, -0.2f);
        this.LegRight01a.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.LegRight01a, 0.20943952f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer(this, 100, 2);
        this.Neck.setRotationPoint(0.0f, -10.3f, 0.5f);
        this.Neck.addBox(-3.0f, -2.0f, -3.5f, 6, 2, 6, 0.0f);
        this.setRotateAngle(this.Neck, 0.10471976f, 0.0f, 0.0f);
        this.ShoesR02 = new ModelRenderer(this, 90, 0);
        this.ShoesR02.mirror = true;
        this.ShoesR02.setRotationPoint(0.0f, 2.5f, -0.7f);
        this.ShoesR02.addBox(-4.0f, 0.0f, -4.0f, 8, 3, 9, 0.0f);
        this.setRotateAngle(this.ShoesR02, 0.20943952f, 0.0f, 0.0f);
        this.EquipSL02 = new ModelRenderer(this, 0, 0);
        this.EquipSL02.setRotationPoint(0.0f, 16.0f, 0.0f);
        this.EquipSL02.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.HairL01 = new ModelRenderer(this, 86, 101);
        this.HairL01.setRotationPoint(7.0f, 3.0f, -5.5f);
        this.HairL01.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 4, 0.0f);
        this.setRotateAngle(this.HairL01, -0.13962634f, -0.17453292f, -0.08726646f);
        this.EquipSR05 = new ModelRenderer(this, 100, 0);
        this.EquipSR05.setRotationPoint(0.0f, -9.0f, 0.0f);
        this.EquipSR05.addBox(-1.0f, -2.0f, -1.0f, 2, 2, 2, 0.0f);
        this.ArmLeft02 = new ModelRenderer(this, 96, 2);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(3.0f, 12.0f, 2.5f);
        this.ArmLeft02.addBox(-5.0f, 0.0f, -5.0f, 5, 12, 5, 0.0f);
        this.LegLeft01 = new ModelRenderer(this, 0, 83);
        this.LegLeft01.setRotationPoint(4.8f, 5.5f, -2.6f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegLeft01, -0.34906584f, 0.0f, 0.10471976f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.0f, -0.7f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.HairL02 = new ModelRenderer(this, 86, 101);
        this.HairL02.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.HairL02.addBox(-1.0f, 0.0f, 0.0f, 2, 9, 4, 0.0f);
        this.setRotateAngle(this.HairL02, 0.17453292f, 0.0f, 0.08726646f);
        this.Hair01 = new ModelRenderer(this, 0, 57);
        this.Hair01.setRotationPoint(0.0f, 9.0f, 1.0f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 17, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.20943952f, 0.0f, 0.0f);
        this.EquipSL04 = new ModelRenderer(this, 109, 0);
        this.EquipSL04.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.EquipSL04.addBox(-0.5f, -9.0f, -0.5f, 1, 9, 1, 0.0f);
        this.Hair05 = new ModelRenderer(this, 108, 28);
        this.Hair05.setRotationPoint(1.5f, -1.0f, 0.0f);
        this.Hair05.addBox(0.0f, -2.5f, -2.5f, 5, 9, 5, 0.0f);
        this.setRotateAngle(this.Hair05, 0.10471976f, -0.08726646f, -0.17453292f);
        this.ArmLeft01a = new ModelRenderer(this, 90, 9);
        this.ArmLeft01a.mirror = true;
        this.ArmLeft01a.setRotationPoint(0.5f, 5.5f, -0.2f);
        this.ArmLeft01a.addBox(-3.0f, 0.0f, -3.0f, 6, 4, 6, 0.0f);
        this.setRotateAngle(this.ArmLeft01a, 0.20943952f, 0.0f, 0.0f);
        this.LegLeft01b = new ModelRenderer(this, 93, 3);
        this.LegLeft01b.setRotationPoint(0.0f, 11.6f, -0.1f);
        this.LegLeft01b.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.LegLeft01b, 0.20943952f, 0.0f, 0.0f);
        this.ShoesR03 = new ModelRenderer(this, 100, 3);
        this.ShoesR03.mirror = true;
        this.ShoesR03.setRotationPoint(0.0f, 2.4f, -0.7f);
        this.ShoesR03.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.ShoesR03, -0.13962634f, 0.0f, 0.0f);
        this.EquipSR02 = new ModelRenderer(this, 0, 0);
        this.EquipSR02.setRotationPoint(0.0f, 16.0f, 0.0f);
        this.EquipSR02.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.EquipSL05 = new ModelRenderer(this, 100, 0);
        this.EquipSL05.setRotationPoint(0.0f, -9.0f, 0.0f);
        this.EquipSL05.addBox(-1.0f, -2.0f, -1.0f, 2, 2, 2, 0.0f);
        this.EquipSL03 = new ModelRenderer(this, 0, 0);
        this.EquipSL03.setRotationPoint(0.0f, 16.0f, 0.0f);
        this.EquipSL03.addBox(-4.5f, 0.0f, -0.5f, 9, 16, 1, 0.0f);
        this.ShoesL02 = new ModelRenderer(this, 90, 0);
        this.ShoesL02.setRotationPoint(0.0f, 2.5f, -0.7f);
        this.ShoesL02.addBox(-4.0f, 0.0f, -4.0f, 8, 3, 9, 0.0f);
        this.setRotateAngle(this.ShoesL02, 0.20943952f, 0.0f, 0.0f);
        this.ArmRight01 = new ModelRenderer(this, 0, 85);
        this.ArmRight01.mirror = true;
        this.ArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 8, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, 0.0f, 0.0f, 0.2617994f);
        this.Hair07 = new ModelRenderer(this, 110, 29);
        this.Hair07.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.Hair07.addBox(-2.0f, 0.0f, -2.0f, 4, 7, 4, 0.0f);
        this.setRotateAngle(this.Hair07, -0.2617994f, 0.0f, 0.13962634f);
        this.BoobR = new ModelRenderer(this, 33, 101);
        this.BoobR.setRotationPoint(-3.5f, -8.1f, -3.7f);
        this.BoobR.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobR, -0.6981317f, -0.08726646f, -0.08726646f);
        this.Hair04 = new ModelRenderer(this, 108, 0);
        this.Hair04.setRotationPoint(6.5f, 3.5f, 6.0f);
        this.Hair04.addBox(0.0f, -2.0f, -2.0f, 2, 4, 4, 0.0f);
        this.setRotateAngle(this.Hair04, 0.0f, -0.08726646f, -0.08726646f);
        this.LegRight01b = new ModelRenderer(this, 96, 2);
        this.LegRight01b.mirror = true;
        this.LegRight01b.setRotationPoint(0.0f, 11.6f, -0.1f);
        this.LegRight01b.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.LegRight01b, 0.20943952f, 0.0f, 0.0f);
        this.ArmRight01a = new ModelRenderer(this, 92, 3);
        this.ArmRight01a.setRotationPoint(-0.5f, 5.5f, -0.2f);
        this.ArmRight01a.addBox(-3.0f, 0.0f, -3.0f, 6, 4, 6, 0.0f);
        this.setRotateAngle(this.ArmRight01a, 0.20943952f, 0.0f, 0.0f);
        this.ArmRight01b = new ModelRenderer(this, 92, 0);
        this.ArmRight01b.setRotationPoint(-0.5f, 9.0f, -0.1f);
        this.ArmRight01b.addBox(-3.0f, 0.0f, -3.0f, 6, 4, 6, 0.0f);
        this.setRotateAngle(this.ArmRight01b, 0.20943952f, 0.0f, 0.0f);
        this.LegLeft01.addChild(this.LegLeft02);
        this.ShoesL02.addChild(this.ShoesL03);
        this.BodyMain.addChild(this.Butt);
        this.LegRight01.addChild(this.LegRight02);
        this.Head.addChild(this.Hair);
        this.ArmLeft01.addChild(this.ArmLeft01b);
        this.ShoesR03.addChild(this.ShoesR04);
        this.Butt.addChild(this.LegRight01);
        this.LegLeft01.addChild(this.LegLeft01a);
        this.ShoesL03.addChild(this.ShoesL04);
        this.Butt.addChild(this.Skirt01);
        this.Hair.addChild(this.Ahoke);
        this.BodyMain.addChild(this.Cloth01);
        this.HairR01.addChild(this.HairR02);
        this.LegLeft02.addChild(this.ShoesL01);
        this.BodyMain.addChild(this.BoobL);
        this.BodyMain.addChild(this.ArmLeft01);
        this.ArmRight01.addChild(this.ArmRight02);
        this.Head.addChild(this.HairMain);
        this.BodyMain.addChild(this.Cloth02);
        this.Skirt01.addChild(this.Skirt02);
        this.Hair.addChild(this.HairR01);
        this.Hair01.addChild(this.Hair02);
        this.LegRight02.addChild(this.ShoesR01);
        this.Hair05.addChild(this.Hair06);
        this.Hair02.addChild(this.Hair03);
        this.LegRight01.addChild(this.LegRight01a);
        this.BodyMain.addChild(this.Neck);
        this.ShoesR01.addChild(this.ShoesR02);
        this.Hair.addChild(this.HairL01);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.Butt.addChild(this.LegLeft01);
        this.Neck.addChild(this.Head);
        this.HairL01.addChild(this.HairL02);
        this.HairMain.addChild(this.Hair01);
        this.Hair04.addChild(this.Hair05);
        this.ArmLeft01.addChild(this.ArmLeft01a);
        this.LegLeft01.addChild(this.LegLeft01b);
        this.ShoesR02.addChild(this.ShoesR03);
        this.ShoesL01.addChild(this.ShoesL02);
        this.BodyMain.addChild(this.ArmRight01);
        this.Hair06.addChild(this.Hair07);
        this.BodyMain.addChild(this.BoobR);
        this.HairMain.addChild(this.Hair04);
        this.LegRight01.addChild(this.LegRight01b);
        this.ArmRight01.addChild(this.ArmRight01a);
        this.ArmRight01.addChild(this.ArmRight01b);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain, -0.10471976f, 0.0f, 0.0f);
        this.GlowBodyMain2 = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain2.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain2, -0.10471976f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(0.0f, -10.3f, 0.5f);
        this.setRotateAngle(this.GlowNeck, 0.10471976f, 0.0f, 0.0f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -1.0f, -0.7f);
        this.GlowArmLeft01 = new ModelRenderer(this, 0, 0);
        this.GlowArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.setRotateAngle(this.GlowArmLeft01, 0.34906584f, 0.0f, -0.2617994f);
        this.GlowArmLeft02 = new ModelRenderer(this, 0, 0);
        this.GlowArmLeft02.setRotationPoint(3.0f, 12.0f, 2.5f);
        this.GlowArmRight01 = new ModelRenderer(this, 0, 0);
        this.GlowArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.setRotateAngle(this.GlowArmRight01, 0.0f, 0.0f, 0.2617994f);
        this.GlowArmRight02 = new ModelRenderer(this, 0, 0);
        this.GlowArmRight02.setRotationPoint(-3.0f, 12.0f, 2.5f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.GlowBodyMain2.addChild(this.GlowArmLeft01);
        this.GlowArmLeft01.addChild(this.GlowArmLeft02);
        this.GlowArmLeft02.addChild(this.EquipSL01);
        this.EquipSL01.addChild(this.EquipSL02);
        this.EquipSL02.addChild(this.EquipSL03);
        this.EquipSL01.addChild(this.EquipSL04);
        this.EquipSL04.addChild(this.EquipSL05);
        this.GlowBodyMain2.addChild(this.GlowArmRight01);
        this.GlowArmRight01.addChild(this.GlowArmRight02);
        this.GlowArmRight02.addChild(this.EquipSR01);
        this.EquipSR01.addChild(this.EquipSR02);
        this.EquipSR02.addChild(this.EquipSR03);
        this.EquipSR01.addChild(this.EquipSR04);
        this.EquipSR04.addChild(this.EquipSR05);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        float light = 80.0f + MathHelper.cos(f2 * 0.075f) * 80.0f;
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, light, light);
        this.GlowBodyMain2.render(f5);
        GlStateManager.enableLighting();
        int j = entity.getBrightnessForRender();
        int k = j % 65536;
        int l = j / 65536;
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, k, l);
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
        int state = ent.getStateEmotion(0);
        boolean f1 = EmotionHelper.checkModelState(1, state);
        boolean f2 = EmotionHelper.checkModelState(2, state);
        if (f1 || f2) {
            this.GlowBodyMain2.isHidden = false;
            this.GlowArmLeft01.isHidden = !f1;
            this.GlowArmRight01.isHidden = !f2;
        } else {
            this.GlowBodyMain2.isHidden = true;
        }
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowBodyMain2.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain2.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain2.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
        this.GlowArmLeft01.rotateAngleX = this.ArmLeft01.rotateAngleX;
        this.GlowArmLeft01.rotateAngleY = this.ArmLeft01.rotateAngleY;
        this.GlowArmLeft01.rotateAngleZ = this.ArmLeft01.rotateAngleZ;
        this.GlowArmLeft02.rotateAngleX = this.ArmLeft02.rotateAngleX;
        this.GlowArmLeft02.rotateAngleY = this.ArmLeft02.rotateAngleY;
        this.GlowArmLeft02.rotateAngleZ = this.ArmLeft02.rotateAngleZ;
        this.GlowArmRight01.rotateAngleX = this.ArmRight01.rotateAngleX;
        this.GlowArmRight01.rotateAngleY = this.ArmRight01.rotateAngleY;
        this.GlowArmRight01.rotateAngleZ = this.ArmRight01.rotateAngleZ;
        this.GlowArmRight02.rotateAngleX = this.ArmRight02.rotateAngleX;
        this.GlowArmRight02.rotateAngleY = this.ArmRight02.rotateAngleY;
        this.GlowArmRight02.rotateAngleZ = this.ArmRight02.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.49f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = 0.65f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.BoobL.rotateAngleX = -0.75f;
        this.BoobR.rotateAngleX = -0.75f;
        this.Ahoke.rotateAngleY = 0.7f;
        this.BodyMain.rotateAngleX = -0.2f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = -0.14f;
        this.Skirt01.rotateAngleX = -0.1745f;
        this.Skirt01.offsetY = 0.0f;
        this.Skirt02.rotateAngleX = -0.2618f;
        this.Skirt02.offsetY = 0.0f;
        this.Hair01.rotateAngleX = -0.1f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -0.2f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -0.14f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.Hair05.rotateAngleX = -0.4f;
        this.Hair05.rotateAngleZ = 0.0f;
        this.Hair06.rotateAngleX = 0.14f;
        this.Hair06.rotateAngleZ = 0.0f;
        this.Hair07.rotateAngleX = -0.2f;
        this.Hair07.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleX = -0.14f;
        this.HairL01.rotateAngleZ = 0.0f;
        this.HairL02.rotateAngleX = 0.17f;
        this.HairL02.rotateAngleZ = 0.0f;
        this.HairR01.rotateAngleX = -0.14f;
        this.HairR01.rotateAngleZ = 0.0f;
        this.HairR02.rotateAngleX = 0.17f;
        this.HairR02.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = 0.2f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft01.rotateAngleZ = -0.2618f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.offsetY = 0.0f;
        this.ArmLeft02.offsetZ = 0.0f;
        this.ArmRight01.rotateAngleX = 0.2f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = 0.2618f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.offsetY = 0.0f;
        this.ArmRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleX = -0.9f;
        this.LegLeft01.rotateAngleZ = -0.14f;
        this.LegLeft02.rotateAngleX = 1.2217f;
        this.LegLeft02.rotateAngleY = 1.2217f;
        this.LegLeft02.rotateAngleZ = -1.0472f;
        this.LegLeft02.offsetX = 0.22f;
        this.LegLeft02.offsetY = -0.03f;
        this.LegLeft02.offsetZ = 0.2f;
        this.LegRight01.rotateAngleX = -0.9f;
        this.LegRight01.rotateAngleZ = 0.14f;
        this.LegRight02.rotateAngleX = 1.2217f;
        this.LegRight02.rotateAngleY = -1.2217f;
        this.LegRight02.rotateAngleZ = 1.0472f;
        this.LegRight02.offsetX = -0.22f;
        this.LegRight02.offsetY = -0.03f;
        this.LegRight02.offsetZ = 0.2f;
        this.GlowBodyMain2.isHidden = true;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleZ = 0.087f;
        this.HairL02.rotateAngleZ = 0.087f;
        this.HairR01.rotateAngleZ = 0.087f;
        this.HairR02.rotateAngleZ = -0.052f;
        this.HairL01.rotateAngleX = -0.65f;
        this.HairL02.rotateAngleX = 0.17f;
        this.HairR01.rotateAngleX = -0.65f;
        this.HairR02.rotateAngleX = 0.17f;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float angleX = MathHelper.cos(f2 * 0.08f + f * 0.25f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.3f + f * 0.5f);
        float angleX2 = MathHelper.cos(f2 * 0.08f + 0.6f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1;
        float addk1;
        float addk2;
        float headX;
        float headZ;
        if (ent.getShipDepth(0) > 0.0 || ent.getShipDepth(1) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 * 0.5f - 0.35f;
        addk2 = angleAdd2 * 0.5f - 0.1745f;
        this.Head.rotateAngleX = f4 * 0.014f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.BoobL.rotateAngleX = angleX * 0.06f - 0.75f;
        this.BoobR.rotateAngleX = angleX * 0.06f - 0.75f;
        this.Ahoke.rotateAngleY = angleX * 0.2f + 0.7f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = 0.35f;
        this.Skirt01.rotateAngleX = -0.14f;
        this.Skirt01.offsetY = 0.0f;
        this.Skirt02.rotateAngleX = -0.087f;
        this.Skirt02.offsetY = 0.0f;
        this.Hair01.rotateAngleX = angleX * 0.03f + 0.21f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -angleX1 * 0.04f - 0.087f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -angleX2 * 0.07f - 0.14f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.Hair05.rotateAngleX = angleX * 0.06f + 0.1f;
        this.Hair05.rotateAngleZ = 0.0f;
        this.Hair06.rotateAngleX = -angleX1 * 0.08f + 0.14f;
        this.Hair06.rotateAngleZ = 0.0f;
        this.Hair07.rotateAngleX = -angleX2 * 0.1f - 0.2f;
        this.Hair07.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleX = angleX * 0.04f - 0.14f;
        this.HairL01.rotateAngleZ = 0.0f;
        this.HairL02.rotateAngleX = -angleX1 * 0.06f + 0.17f;
        this.HairL02.rotateAngleZ = 0.0f;
        this.HairR01.rotateAngleX = angleX * 0.04f - 0.14f;
        this.HairR01.rotateAngleZ = 0.0f;
        this.HairR02.rotateAngleX = -angleX1 * 0.06f + 0.17f;
        this.HairR02.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = angleAdd2 * 0.25f + 0.35f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft01.rotateAngleZ = angleX * 0.03f - 0.26f;
        this.ArmLeft02.rotateAngleX = 0.0f;
        this.ArmLeft02.offsetY = 0.0f;
        this.ArmLeft02.offsetZ = 0.0f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.25f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = -angleX * 0.03f + 0.26f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.offsetY = 0.0f;
        this.ArmRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.1f;
        this.LegLeft02.rotateAngleX = 0.0f;
        this.LegLeft02.rotateAngleY = 0.0f;
        this.LegLeft02.rotateAngleZ = 0.0f;
        this.LegLeft02.offsetX = 0.0f;
        this.LegLeft02.offsetY = 0.0f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegRight01.rotateAngleZ = -0.1f;
        this.LegRight02.rotateAngleX = 0.0f;
        this.LegRight02.rotateAngleY = 0.0f;
        this.LegRight02.rotateAngleZ = 0.0f;
        this.LegRight02.offsetX = 0.0f;
        this.LegRight02.offsetY = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        this.EquipSL01.rotateAngleX = -1.57f;
        this.EquipSL01.rotateAngleY = 0.0f;
        this.EquipSL01.rotateAngleZ = 1.57f;
        this.EquipSL01.offsetX = 0.0f;
        this.EquipSL01.offsetY = 0.0f;
        this.EquipSL01.offsetZ = 0.0f;
        this.EquipSR01.rotateAngleX = -1.57f;
        this.EquipSR01.rotateAngleY = 0.0f;
        this.EquipSR01.rotateAngleZ = 1.57f;
        this.EquipSR01.offsetX = 0.0f;
        this.EquipSR01.offsetY = 0.0f;
        this.EquipSR01.offsetZ = 0.0f;
        if (ent.getIsSprinting() || f1 > 0.95f) {
            GlStateManager.translate(0.0f, 0.05f, 0.0f);
            this.Head.rotateAngleX -= 0.4f;
            this.BodyMain.rotateAngleX = 0.7f;
            this.Butt.rotateAngleX -= 0.7f;
            this.Skirt01.rotateAngleX = -0.15f;
            this.Skirt02.rotateAngleX = -0.32f;
            this.Hair01.rotateAngleX += 0.3f;
            this.ArmLeft01.rotateAngleX = 0.4f;
            this.ArmLeft01.rotateAngleY = -0.5f;
            this.ArmLeft01.rotateAngleZ = -0.7f;
            this.ArmRight01.rotateAngleX = 0.4f;
            this.ArmRight01.rotateAngleY = 0.5f;
            this.ArmRight01.rotateAngleZ = 0.7f;
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.05f, 0.0f);
            this.Head.rotateAngleX -= 1.0472f;
            this.BodyMain.rotateAngleX = 1.0472f;
            this.Butt.rotateAngleX = -0.4f;
            this.Skirt01.rotateAngleX = -0.12f;
            this.Skirt02.rotateAngleX = -0.16f;
            this.Skirt02.offsetY = -0.1f;
            this.Hair02.rotateAngleX -= 0.3f;
            this.Hair03.rotateAngleX -= 0.3f;
            int state = ent.getStateEmotion(0);
            boolean fs1 = EmotionHelper.checkModelState(1, state);
            boolean fs2 = EmotionHelper.checkModelState(2, state);
            if (fs1 || fs2) {
                this.ArmLeft01.rotateAngleX = angleAdd2 * 0.25f - 0.1f;
                this.ArmLeft01.rotateAngleY = -0.7f;
                this.ArmLeft01.rotateAngleZ = -0.3f;
                this.ArmRight01.rotateAngleX = angleAdd1 * 0.25f - 0.1f;
                this.ArmRight01.rotateAngleY = 0.7f;
                this.ArmRight01.rotateAngleZ = 0.3f;
            } else {
                this.ArmLeft01.rotateAngleX = -0.6f;
                this.ArmLeft01.rotateAngleZ = 0.2618f;
                this.ArmRight01.rotateAngleX = -0.6f;
                this.ArmRight01.rotateAngleZ = -0.2618f;
            }
            addk1 -= 0.4f;
            addk2 -= 0.4f;
        }
        if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
            if (ent.getIsSitting()) {
                if (ent.getStateEmotion(1) == 4) {
                    GlStateManager.translate(0.0f, 0.65f, -0.27f);
                    this.Head.rotateAngleX = -1.2217f;
                    this.Head.rotateAngleY = 0.0f;
                    this.Head.rotateAngleZ = 0.0f;
                    this.BodyMain.rotateAngleX = 1.2217f;
                    this.Hair02.rotateAngleX += 0.2f;
                    this.Hair03.rotateAngleX += 0.2f;
                    this.Hair05.rotateAngleX -= 0.6f;
                    this.Hair06.rotateAngleX -= 0.5f;
                    this.ArmLeft01.rotateAngleX = -2.0f;
                    this.ArmLeft01.rotateAngleY = -0.1f;
                    this.ArmLeft01.rotateAngleZ = -0.1f;
                    this.ArmLeft02.rotateAngleX = -2.5f;
                    this.ArmLeft02.offsetY = 0.1f;
                    this.ArmLeft02.offsetZ = -0.3f;
                    this.ArmRight01.rotateAngleX = -2.0f;
                    this.ArmRight01.rotateAngleY = 0.1f;
                    this.ArmRight01.rotateAngleZ = 0.1f;
                    this.ArmRight02.rotateAngleX = -2.5f;
                    this.ArmRight02.offsetY = 0.1f;
                    this.ArmRight02.offsetZ = -0.3f;
                    addk1 = 0.0f;
                    addk2 = 0.0f;
                    this.LegLeft02.rotateAngleX = angleX * 0.4f + 0.8f;
                    this.LegRight02.rotateAngleX = -angleX * 0.4f + 0.8f;
                    this.GlowBodyMain2.isHidden = true;
                } else {
                    GlStateManager.translate(0.0f, 0.51f, 0.0f);
                    this.Head.rotateAngleY -= 0.4f;
                    this.Head.rotateAngleZ += 0.2f;
                    this.BodyMain.rotateAngleX = -0.25f;
                    this.Butt.rotateAngleX = -0.2f;
                    this.Skirt01.rotateAngleX = -0.13f;
                    this.Skirt01.offsetY = -0.05f;
                    this.Skirt02.rotateAngleX = -0.13f;
                    this.Skirt02.offsetY = -0.05f;
                    this.ArmLeft01.rotateAngleX = 0.35f;
                    this.ArmLeft01.rotateAngleZ = -0.2618f;
                    this.ArmRight01.rotateAngleX = -0.4f;
                    this.ArmRight01.rotateAngleZ = 0.4f;
                    addk1 = -0.9f;
                    addk2 = -0.9f;
                    this.LegLeft01.rotateAngleZ = -0.14f;
                    this.LegLeft02.rotateAngleX = 1.2217f;
                    this.LegLeft02.rotateAngleY = 1.2217f;
                    this.LegLeft02.rotateAngleZ = -1.0472f;
                    this.LegLeft02.offsetX = 0.22f;
                    this.LegLeft02.offsetY = -0.03f;
                    this.LegLeft02.offsetZ = 0.2f;
                    this.LegRight01.rotateAngleZ = 0.14f;
                    this.LegRight02.rotateAngleX = 1.2217f;
                    this.LegRight02.rotateAngleY = -1.2217f;
                    this.LegRight02.rotateAngleZ = 1.0472f;
                    this.LegRight02.offsetX = -0.22f;
                    this.LegRight02.offsetY = -0.03f;
                    this.LegRight02.offsetZ = 0.2f;
                    this.EquipSL01.rotateAngleX -= 0.06f;
                    this.EquipSL01.rotateAngleZ -= 1.2f;
                    this.EquipSR01.rotateAngleX -= 1.2f;
                }
            } else {
                GlStateManager.translate(0.0f, 0.56f, 0.0f);
                this.BodyMain.rotateAngleX = -0.45f;
                this.Butt.rotateAngleX = -0.2f;
                this.Skirt01.rotateAngleX = -0.13f;
                this.Skirt01.offsetY = -0.05f;
                this.Skirt02.rotateAngleX = -0.13f;
                this.Skirt02.offsetY = -0.05f;
                this.ArmLeft01.rotateAngleX = 0.2f;
                this.ArmLeft01.rotateAngleZ = -1.1f;
                this.ArmRight01.rotateAngleX = 0.2f;
                this.ArmRight01.rotateAngleZ = 1.1f;
                addk1 = -0.8f;
                addk2 = -1.2f;
                this.LegLeft01.rotateAngleZ = -0.14f;
                this.LegLeft02.rotateAngleX = 1.2217f;
                this.LegLeft02.rotateAngleY = 1.2217f;
                this.LegLeft02.rotateAngleZ = -1.0472f;
                this.LegLeft02.offsetX = 0.22f;
                this.LegLeft02.offsetY = -0.03f;
                this.LegLeft02.offsetZ = 0.2f;
                this.LegRight01.rotateAngleZ = 0.14f;
                this.LegRight02.rotateAngleX = 0.9f;
                this.EquipSL01.rotateAngleX = -1.2f;
                this.EquipSL01.rotateAngleY = 0.1f;
                this.EquipSL01.rotateAngleZ = 1.0f;
                this.EquipSL01.offsetX = 0.24f;
                this.EquipSL01.offsetY = -0.5f;
                this.EquipSL01.offsetZ = 1.0f;
                this.EquipSR01.rotateAngleX = -1.2f;
                this.EquipSR01.rotateAngleY = -0.1f;
                this.EquipSR01.rotateAngleZ = -1.0f;
                this.EquipSR01.offsetX = -0.24f;
                this.EquipSR01.offsetY = -0.5f;
                this.EquipSR01.offsetZ = 1.0f;
            }
        } else if (ent.getIsSitting() || ent.getIsRiding()) {
            if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 0.65f, 0.0f);
                this.Head.rotateAngleX = -1.2217f;
                this.Head.rotateAngleY = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                this.BodyMain.rotateAngleX = 1.2217f;
                this.Hair02.rotateAngleX += 0.2f;
                this.Hair03.rotateAngleX += 0.2f;
                this.Hair05.rotateAngleX -= 0.6f;
                this.Hair06.rotateAngleX -= 0.5f;
                this.ArmLeft01.rotateAngleX = -2.0f;
                this.ArmLeft01.rotateAngleY = -0.1f;
                this.ArmLeft01.rotateAngleZ = -0.1f;
                this.ArmLeft02.rotateAngleX = -2.5f;
                this.ArmLeft02.offsetY = 0.1f;
                this.ArmLeft02.offsetZ = -0.3f;
                this.ArmRight01.rotateAngleX = -2.0f;
                this.ArmRight01.rotateAngleY = 0.1f;
                this.ArmRight01.rotateAngleZ = 0.1f;
                this.ArmRight02.rotateAngleX = -2.5f;
                this.ArmRight02.offsetY = 0.1f;
                this.ArmRight02.offsetZ = -0.3f;
                addk1 = 0.0f;
                addk2 = 0.0f;
                this.LegLeft02.rotateAngleX = angleX * 0.4f + 0.8f;
                this.LegRight02.rotateAngleX = -angleX * 0.4f + 0.8f;
                this.GlowBodyMain2.isHidden = true;
            } else {
                GlStateManager.translate(0.0f, 0.51f, 0.0f);
                this.Head.rotateAngleY -= 0.4f;
                this.Head.rotateAngleZ += 0.2f;
                this.BodyMain.rotateAngleX = -0.25f;
                this.Butt.rotateAngleX = -0.2f;
                this.Skirt01.rotateAngleX = -0.13f;
                this.Skirt01.offsetY = -0.05f;
                this.Skirt02.rotateAngleX = -0.13f;
                this.Skirt02.offsetY = -0.05f;
                this.ArmLeft01.rotateAngleX = 0.35f;
                this.ArmLeft01.rotateAngleZ = -0.2618f;
                this.ArmRight01.rotateAngleX = -0.4f;
                this.ArmRight01.rotateAngleZ = 0.4f;
                addk1 = -0.9f;
                addk2 = -0.9f;
                this.LegLeft01.rotateAngleZ = -0.14f;
                this.LegLeft02.rotateAngleX = 1.2217f;
                this.LegLeft02.rotateAngleY = 1.2217f;
                this.LegLeft02.rotateAngleZ = -1.0472f;
                this.LegLeft02.offsetX = 0.22f;
                this.LegLeft02.offsetY = -0.03f;
                this.LegLeft02.offsetZ = 0.2f;
                this.LegRight01.rotateAngleZ = 0.14f;
                this.LegRight02.rotateAngleX = 1.2217f;
                this.LegRight02.rotateAngleY = -1.2217f;
                this.LegRight02.rotateAngleZ = 1.0472f;
                this.LegRight02.offsetX = -0.22f;
                this.LegRight02.offsetY = -0.03f;
                this.LegRight02.offsetZ = 0.2f;
                this.EquipSL01.rotateAngleX -= 0.06f;
                this.EquipSL01.rotateAngleZ -= 1.2f;
                this.EquipSR01.rotateAngleX -= 1.2f;
            }
        }
        if (!(((Entity)ent).getRidingEntity() instanceof BasicEntityMount)) {
            float f6;
            float fb;
            int atktime = ent.getAttackTick();
            if (atktime > 41) {
                this.setFaceAttack(ent);
                float ft = (50 - ent.getAttackTick()) + (f2 - (int)f2);
                float fa = MathHelper.cos((ft *= 0.125f) * ft * (float)Math.PI);
                fb = MathHelper.cos(MathHelper.sqrt(ft) * (float)Math.PI);
                this.ArmLeft01.rotateAngleX += -fb * 120.0f * ((float)Math.PI / 180) - 1.5f;
                this.ArmLeft01.rotateAngleY += fa * 20.0f * ((float)Math.PI / 180);
                this.ArmLeft01.rotateAngleZ += fb * 20.0f * ((float)Math.PI / 180) + 0.26f;
            }
            if (atktime > 36 && atktime < 45) {
                this.setFaceAttack(ent);
                float ft = (45 - ent.getAttackTick()) + (f2 - (int)f2);
                float fa = MathHelper.cos((ft *= 0.125f) * ft * (float)Math.PI);
                fb = MathHelper.cos(MathHelper.sqrt(ft) * (float)Math.PI);
                this.ArmRight01.rotateAngleX += -fb * 120.0f * ((float)Math.PI / 180) - 1.5f;
                this.ArmRight01.rotateAngleY += -fa * 20.0f * ((float)Math.PI / 180);
                this.ArmRight01.rotateAngleZ += -fb * 20.0f * ((float)Math.PI / 180) - 0.26f;
            }
            if ((f6 = ent.getSwingTime(f2 - (int)f2)) != 0.0f) {
                float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
                float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
                this.ArmRight01.rotateAngleX += -f8 * 95.0f * ((float)Math.PI / 180);
                this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 0.2f;
                this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
            }
        }
        headX = this.Head.rotateAngleX * -0.5f;
        headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair01.rotateAngleX += headX;
        this.Hair01.rotateAngleZ += headZ;
        this.Hair02.rotateAngleX += headX * 0.5f;
        this.Hair02.rotateAngleZ += headZ * 0.5f;
        this.Hair03.rotateAngleX += headX * 0.5f;
        this.Hair03.rotateAngleZ += headZ * 0.5f;
        this.Hair05.rotateAngleX += headX;
        this.Hair05.rotateAngleZ += headZ;
        this.Hair06.rotateAngleX += headX;
        this.Hair06.rotateAngleZ += headZ;
        this.HairL01.rotateAngleZ += headZ;
        this.HairL02.rotateAngleZ += headZ;
        this.HairR01.rotateAngleZ += headZ;
        this.HairR02.rotateAngleZ += headZ;
        this.HairL01.rotateAngleX += headX;
        this.HairL02.rotateAngleX += headX;
        this.HairR01.rotateAngleX += headX;
        this.HairR02.rotateAngleX += headX;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }
}
