package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelBattleshipNagato
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer Butt;
    private final ModelRenderer Cloth;
    private final ModelRenderer Head;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer HeadEquip;
    private final ModelRenderer HeadEquip05;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairMidL01;
    private final ModelRenderer HairMidL02;
    private final ModelRenderer HeadEquip01;
    private final ModelRenderer HeadEquip03;
    private final ModelRenderer HeadEquip02;
    private final ModelRenderer HeadEquip04;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer LegRight;
    private final ModelRenderer LegLeft;
    private final ModelRenderer Skirt;
    private final ModelRenderer ShoesR;
    private final ModelRenderer ShoesL;
    private final ModelRenderer SkirtEquip;
    private final ModelRenderer EquipBase;
    private final ModelRenderer EquipL01;
    private final ModelRenderer EquipR01;
    private final ModelRenderer EquipBaseM01;
    private final ModelRenderer EquipBaseM02;
    private final ModelRenderer EquipBaseM03;
    private final ModelRenderer EquipL02;
    private final ModelRenderer EquipL03;
    private final ModelRenderer EquipR04;
    private final ModelRenderer EquipLCBase01;
    private final ModelRenderer EquipLC2Base01;
    private final ModelRenderer EquipLC2Base02;
    private final ModelRenderer EquipLC201;
    private final ModelRenderer EquipLC203;
    private final ModelRenderer EquipLC202;
    private final ModelRenderer EquipLC204;
    private final ModelRenderer EquipLCBase02;
    private final ModelRenderer EquipLC01;
    private final ModelRenderer EquipLC03;
    private final ModelRenderer EquipLCRadar;
    private final ModelRenderer EquipLC02;
    private final ModelRenderer EquipLC04;
    private final ModelRenderer EquipR02;
    private final ModelRenderer EquipR03;
    private final ModelRenderer EquipRCBase01;
    private final ModelRenderer EquipR04_1;
    private final ModelRenderer EquipRCBase02;
    private final ModelRenderer EquipRC01;
    private final ModelRenderer EquipRC03;
    private final ModelRenderer EquipRCRadar;
    private final ModelRenderer EquipRC02;
    private final ModelRenderer EquipRC04;
    private final ModelRenderer EquipRC2Base01;
    private final ModelRenderer EquipRC2Base02;
    private final ModelRenderer EquipRC201;
    private final ModelRenderer EquipRC203;
    private final ModelRenderer EquipRC202;
    private final ModelRenderer EquipRC204;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;

    public ModelBattleshipNagato() {
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.offsetItem = new float[]{0.0f, 0.92f, 0.0f};
        this.offsetBlock = new float[]{0.0f, 0.92f, 0.0f};
        this.setDefaultFaceModel();
        this.LegRight = new ModelRenderer(this, 0, 80);
        this.LegRight.setRotationPoint(-4.5f, 9.5f, -3.0f);
        this.LegRight.addBox(-3.0f, 0.0f, -3.0f, 6, 19, 6, 0.0f);
        this.setRotateAngle(this.LegRight, -0.2618f, 0.0f, -0.05235988f);
        this.Cloth = new ModelRenderer(this, 96, 16);
        this.Cloth.setRotationPoint(0.0f, -11.5f, -5.0f);
        this.Cloth.addBox(-5.5f, 0.0f, 0.0f, 11, 2, 9, 0.0f);
        this.EquipL02 = new ModelRenderer(this, 128, 0);
        this.EquipL02.setRotationPoint(11.5f, 0.0f, 0.6f);
        this.EquipL02.addBox(0.0f, 0.0f, 0.0f, 10, 12, 5, 0.0f);
        this.setRotateAngle(this.EquipL02, 0.0f, 0.5235988f, 0.0f);
        this.Neck = new ModelRenderer(this, 46, 14);
        this.Neck.setRotationPoint(0.0f, -10.0f, 0.0f);
        this.Neck.addBox(-7.0f, -0.5f, -4.5f, 14, 12, 8, 0.0f);
        this.Hair = new ModelRenderer(this, 50, 75);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.0f);
        this.Hair.addBox(-8.0f, -8.0f, -7.2f, 16, 16, 8, 0.0f);
        this.EquipBaseM01 = new ModelRenderer(this, 128, 0);
        this.EquipBaseM01.setRotationPoint(0.0f, 0.0f, 12.0f);
        this.EquipBaseM01.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 8, 0.0f);
        this.setRotateAngle(this.EquipBaseM01, -0.6981317f, 0.0f, 0.0f);
        this.EquipRC03 = new ModelRenderer(this, 128, 117);
        this.EquipRC03.setRotationPoint(-4.0f, 2.0f, -4.0f);
        this.EquipRC03.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipRC03, 0.0f, 0.20943952f, 0.0f);
        this.BoobR = new ModelRenderer(this, 0, 70);
        this.BoobR.setRotationPoint(-3.7f, -9.0f, -3.5f);
        this.BoobR.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 4, 0.0f);
        this.setRotateAngle(this.BoobR, -0.7853982f, -0.13962634f, -0.08726646f);
        this.ShoesR = new ModelRenderer(this, 22, 70);
        this.ShoesR.setRotationPoint(0.0f, 19.0f, -0.2f);
        this.ShoesR.addBox(-3.5f, 0.0f, -3.5f, 7, 9, 7, 0.0f);
        this.EquipL03 = new ModelRenderer(this, 128, 26);
        this.EquipL03.setRotationPoint(5.3f, 0.0f, 1.3f);
        this.EquipL03.addBox(0.0f, 0.0f, -14.0f, 6, 18, 14, 0.0f);
        this.setRotateAngle(this.EquipL03, 0.0f, -0.6981317f, 0.0f);
        this.EquipRCBase01 = new ModelRenderer(this, 128, 0);
        this.EquipRCBase01.setRotationPoint(0.0f, 1.0f, -7.0f);
        this.EquipRCBase01.addBox(-7.0f, -5.5f, -10.0f, 7, 11, 10, 0.0f);
        this.setRotateAngle(this.EquipRCBase01, 0.0f, -0.08726646f, 0.0f);
        this.EquipLC04 = new ModelRenderer(this, 132, 113);
        this.EquipLC04.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipLC04.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.HairMain = new ModelRenderer(this, 48, 56);
        this.HairMain.setRotationPoint(0.0f, -15.0f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 9, 10, 0.0f);
        this.BoobL = new ModelRenderer(this, 0, 70);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.7f, -9.0f, -3.5f);
        this.BoobL.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 4, 0.0f);
        this.setRotateAngle(this.BoobL, -0.7853982f, 0.13962634f, 0.08726646f);
        this.EquipRC2Base01 = new ModelRenderer(this, 128, 0);
        this.EquipRC2Base01.setRotationPoint(-3.0f, -1.0f, -10.0f);
        this.EquipRC2Base01.addBox(-4.5f, 0.0f, -10.0f, 9, 10, 10, 0.0f);
        this.EquipRC204 = new ModelRenderer(this, 132, 113);
        this.EquipRC204.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipRC204.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.Skirt = new ModelRenderer(this, 0, 0);
        this.Skirt.setRotationPoint(0.0f, 7.0f, -2.0f);
        this.Skirt.addBox(-8.5f, 0.0f, -4.5f, 17, 6, 9, 0.0f);
        this.setRotateAngle(this.Skirt, -0.13665928f, 0.0f, 0.0f);
        this.SkirtEquip = new ModelRenderer(this, 71, 0);
        this.SkirtEquip.setRotationPoint(0.0f, -3.0f, 0.2f);
        this.SkirtEquip.addBox(-9.0f, 0.0f, -5.0f, 18, 3, 10, 0.0f);
        this.HeadEquip03 = new ModelRenderer(this, 128, 0);
        this.HeadEquip03.setRotationPoint(-7.5f, 0.0f, 9.0f);
        this.HeadEquip03.addBox(-4.0f, 0.0f, -2.0f, 4, 4, 4, 0.0f);
        this.setRotateAngle(this.HeadEquip03, 0.0f, 0.7853982f, 0.17453292f);
        this.EquipRC04 = new ModelRenderer(this, 132, 113);
        this.EquipRC04.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipRC04.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.HairMidL02 = new ModelRenderer(this, 0, 32);
        this.HairMidL02.setRotationPoint(0.0f, 9.0f, 1.8f);
        this.HairMidL02.addBox(-7.0f, 0.0f, 0.0f, 14, 14, 7, 0.0f);
        this.setRotateAngle(this.HairMidL02, -0.17453292f, 0.0f, 0.0f);
        this.HeadEquip04 = new ModelRenderer(this, 92, 30);
        this.HeadEquip04.setRotationPoint(-4.0f, 1.0f, 0.0f);
        this.HeadEquip04.addBox(-10.0f, -1.0f, -1.0f, 10, 2, 2, 0.0f);
        this.setRotateAngle(this.HeadEquip04, 0.0f, 0.0f, 0.08726646f);
        this.EquipR02 = new ModelRenderer(this, 128, 0);
        this.EquipR02.setRotationPoint(-11.5f, 0.0f, 0.6f);
        this.EquipR02.addBox(-10.0f, 0.0f, 0.0f, 10, 12, 5, 0.0f);
        this.setRotateAngle(this.EquipR02, 0.0f, -0.5235988f, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 24, 53);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(8.5f, -10.0f, 0.0f);
        this.ArmLeft01.addBox(-2.5f, 0.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, 0.0f, 0.0f, -0.15707964f);
        this.LegLeft = new ModelRenderer(this, 0, 80);
        this.LegLeft.mirror = true;
        this.LegLeft.setRotationPoint(4.5f, 9.5f, -3.0f);
        this.LegLeft.addBox(-3.0f, 0.0f, -3.0f, 6, 19, 6, 0.0f);
        this.setRotateAngle(this.LegLeft, -0.2618f, 0.0f, 0.05235988f);
        this.ShoesL = new ModelRenderer(this, 22, 70);
        this.ShoesL.mirror = true;
        this.ShoesL.setRotationPoint(0.0f, 19.0f, -0.2f);
        this.ShoesL.addBox(-3.5f, 0.0f, -3.5f, 7, 9, 7, 0.0f);
        this.EquipBaseM03 = new ModelRenderer(this, 128, 92);
        this.EquipBaseM03.setRotationPoint(0.0f, 0.0f, 9.0f);
        this.EquipBaseM03.addBox(-3.0f, -14.0f, 0.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.EquipBaseM03, -0.43633232f, 0.0f, 0.0f);
        this.EquipLC2Base01 = new ModelRenderer(this, 128, 0);
        this.EquipLC2Base01.setRotationPoint(3.0f, -1.0f, -10.0f);
        this.EquipLC2Base01.addBox(-4.5f, 0.0f, -10.0f, 9, 10, 10, 0.0f);
        this.EquipLC201 = new ModelRenderer(this, 128, 117);
        this.EquipLC201.setRotationPoint(-2.0f, -4.0f, -8.0f);
        this.EquipLC201.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipLC201, -0.13962634f, 0.0f, 0.0f);
        this.EquipRC02 = new ModelRenderer(this, 132, 113);
        this.EquipRC02.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipRC02.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.EquipRC203 = new ModelRenderer(this, 128, 117);
        this.EquipRC203.setRotationPoint(2.0f, -4.0f, -8.0f);
        this.EquipRC203.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipRC203, -0.17453292f, 0.0f, 0.0f);
        this.EquipR04_1 = new ModelRenderer(this, 128, 60);
        this.EquipR04_1.setRotationPoint(0.0f, 11.0f, -13.0f);
        this.EquipR04_1.addBox(-6.0f, 0.0f, -10.0f, 6, 7, 10, 0.0f);
        this.setRotateAngle(this.EquipR04_1, 0.0f, -0.17453292f, 0.0f);
        this.ArmRight01 = new ModelRenderer(this, 24, 53);
        this.ArmRight01.setRotationPoint(-8.5f, -10.0f, 0.0f);
        this.ArmRight01.addBox(-2.5f, 0.0f, -2.5f, 5, 12, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, 0.0f, 0.0f, 0.15707964f);
        this.EquipBaseM02 = new ModelRenderer(this, 128, 0);
        this.EquipBaseM02.setRotationPoint(0.0f, -1.5f, 11.0f);
        this.EquipBaseM02.addBox(-3.5f, 0.0f, 0.0f, 7, 7, 7, 0.0f);
        this.EquipLC204 = new ModelRenderer(this, 132, 113);
        this.EquipLC204.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipLC204.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.EquipLC01 = new ModelRenderer(this, 128, 117);
        this.EquipLC01.setRotationPoint(4.0f, -2.0f, -4.0f);
        this.EquipLC01.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipLC01, 0.0f, -0.2617994f, 0.0f);
        this.Ahoke = new ModelRenderer(this, 33, 87);
        this.Ahoke.setRotationPoint(-1.0f, -10.0f, -5.0f);
        this.Ahoke.addBox(0.0f, -3.0f, -10.0f, 0, 12, 12, 0.0f);
        this.setRotateAngle(this.Ahoke, 0.0f, 0.5235988f, 0.0f);
        this.HeadEquip02 = new ModelRenderer(this, 92, 30);
        this.HeadEquip02.mirror = true;
        this.HeadEquip02.setRotationPoint(4.0f, 1.0f, 0.0f);
        this.HeadEquip02.addBox(0.0f, -1.0f, -1.0f, 10, 2, 2, 0.0f);
        this.setRotateAngle(this.HeadEquip02, 0.0f, 0.0f, -0.08726646f);
        this.EquipR04 = new ModelRenderer(this, 128, 60);
        this.EquipR04.setRotationPoint(0.0f, 11.0f, -13.0f);
        this.EquipR04.addBox(0.0f, 0.0f, -10.0f, 6, 7, 10, 0.0f);
        this.setRotateAngle(this.EquipR04, 0.0f, 0.17453292f, 0.0f);
        this.Butt = new ModelRenderer(this, 0, 17);
        this.Butt.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Butt.addBox(-8.0f, 4.0f, -5.5f, 16, 8, 7, 0.0f);
        this.setRotateAngle(this.Butt, 0.2617994f, 0.0f, 0.0f);
        this.HairMidL01 = new ModelRenderer(this, 48, 34);
        this.HairMidL01.setRotationPoint(0.0f, 9.0f, 1.5f);
        this.HairMidL01.addBox(-7.5f, 0.0f, 0.0f, 15, 13, 9, 0.0f);
        this.setRotateAngle(this.HairMidL01, 0.34906584f, 0.0f, 0.0f);
        this.EquipR03 = new ModelRenderer(this, 128, 26);
        this.EquipR03.setRotationPoint(-5.3f, 0.0f, 1.3f);
        this.EquipR03.addBox(-6.0f, 0.0f, -14.0f, 6, 18, 14, 0.0f);
        this.setRotateAngle(this.EquipR03, 0.0f, 0.6981317f, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 0, 53);
        this.ArmRight02.setRotationPoint(0.0f, 10.0f, 0.0f);
        this.ArmRight02.addBox(-2.5f, 0.0f, -2.5f, 5, 12, 5, 0.0f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.ArmLeft02 = new ModelRenderer(this, 0, 53);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(0.0f, 10.0f, 0.0f);
        this.ArmLeft02.addBox(-2.5f, 0.0f, -2.5f, 5, 12, 5, 0.0f);
        this.HeadEquip05 = new ModelRenderer(this, 128, 0);
        this.HeadEquip05.setRotationPoint(0.0f, -11.5f, -1.0f);
        this.HeadEquip05.addBox(-16.0f, 0.0f, 0.0f, 32, 1, 1, 0.0f);
        this.EquipLC202 = new ModelRenderer(this, 132, 113);
        this.EquipLC202.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipLC202.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.HeadEquip = new ModelRenderer(this, 128, 0);
        this.HeadEquip.setRotationPoint(0.0f, -8.0f, -1.0f);
        this.HeadEquip.addBox(-9.5f, 0.0f, 0.0f, 19, 4, 11, 0.0f);
        this.setRotateAngle(this.HeadEquip, 0.10471976f, 0.0f, 0.0f);
        this.BodyMain = new ModelRenderer(this, 0, 105);
        this.BodyMain.setRotationPoint(0.0f, -14.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -10.0f, -4.0f, 13, 15, 7, 0.0f);
        this.EquipLC2Base02 = new ModelRenderer(this, 128, 0);
        this.EquipLC2Base02.setRotationPoint(0.0f, 0.0f, -1.0f);
        this.EquipLC2Base02.addBox(-5.0f, -5.0f, -10.0f, 10, 5, 14, 0.0f);
        this.setRotateAngle(this.EquipLC2Base02, 0.05235988f, 0.0f, 0.0f);
        this.EquipLC203 = new ModelRenderer(this, 128, 117);
        this.EquipLC203.setRotationPoint(2.0f, -4.0f, -8.0f);
        this.EquipLC203.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipLC203, -0.08726646f, 0.0f, 0.0f);
        this.EquipLCRadar = new ModelRenderer(this, 128, 0);
        this.EquipLCRadar.setRotationPoint(5.2f, 0.0f, 5.5f);
        this.EquipLCRadar.addBox(0.0f, -7.5f, 0.0f, 1, 15, 5, 0.0f);
        this.EquipRC01 = new ModelRenderer(this, 128, 117);
        this.EquipRC01.setRotationPoint(-4.0f, -2.0f, -4.0f);
        this.EquipRC01.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipRC01, 0.0f, 0.2617994f, 0.0f);
        this.EquipL01 = new ModelRenderer(this, 128, 0);
        this.EquipL01.setRotationPoint(0.0f, -3.0f, 8.0f);
        this.EquipL01.addBox(0.0f, 0.0f, 0.0f, 14, 10, 5, 0.0f);
        this.setRotateAngle(this.EquipL01, -0.20943952f, 0.0f, 0.0f);
        this.HeadEquip01 = new ModelRenderer(this, 128, 0);
        this.HeadEquip01.setRotationPoint(7.5f, 0.0f, 9.0f);
        this.HeadEquip01.addBox(0.0f, 0.0f, -2.0f, 4, 4, 4, 0.0f);
        this.setRotateAngle(this.HeadEquip01, 0.0f, -0.7853982f, -0.17453292f);
        this.EquipRC2Base02 = new ModelRenderer(this, 128, 0);
        this.EquipRC2Base02.setRotationPoint(0.0f, 0.0f, -1.0f);
        this.EquipRC2Base02.addBox(-5.0f, -5.0f, -10.0f, 10, 5, 14, 0.0f);
        this.setRotateAngle(this.EquipRC2Base02, 0.05235988f, 0.0f, 0.0f);
        this.EquipLC03 = new ModelRenderer(this, 128, 117);
        this.EquipLC03.setRotationPoint(4.0f, 2.0f, -4.0f);
        this.EquipLC03.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipLC03, 0.0f, -0.13962634f, 0.0f);
        this.EquipBase = new ModelRenderer(this, 128, 0);
        this.EquipBase.setRotationPoint(0.0f, 0.0f, 4.0f);
        this.EquipBase.addBox(-2.5f, 0.0f, 0.0f, 5, 4, 8, 0.0f);
        this.setRotateAngle(this.EquipBase, 0.17453292f, 0.0f, 0.0f);
        this.EquipLCBase02 = new ModelRenderer(this, 128, 0);
        this.EquipLCBase02.setRotationPoint(7.0f, 0.0f, -6.5f);
        this.EquipLCBase02.addBox(0.0f, -5.0f, -4.0f, 5, 10, 14, 0.0f);
        this.setRotateAngle(this.EquipLCBase02, -0.17453292f, 0.05235988f, 0.0f);
        this.EquipRC202 = new ModelRenderer(this, 132, 113);
        this.EquipRC202.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipRC202.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.EquipRCRadar = new ModelRenderer(this, 128, 0);
        this.EquipRCRadar.setRotationPoint(-5.2f, 0.0f, 5.5f);
        this.EquipRCRadar.addBox(-1.0f, -7.5f, 0.0f, 1, 15, 5, 0.0f);
        this.EquipRC201 = new ModelRenderer(this, 128, 117);
        this.EquipRC201.setRotationPoint(-2.0f, -4.0f, -8.0f);
        this.EquipRC201.addBox(-1.5f, -1.5f, -5.0f, 3, 3, 5, 0.0f);
        this.setRotateAngle(this.EquipRC201, -0.08726646f, 0.0f, 0.0f);
        this.EquipR01 = new ModelRenderer(this, 128, 0);
        this.EquipR01.setRotationPoint(0.0f, -3.0f, 8.0f);
        this.EquipR01.addBox(-14.0f, 0.0f, 0.0f, 14, 10, 5, 0.0f);
        this.setRotateAngle(this.EquipR01, -0.20943952f, 0.0f, 0.0f);
        this.EquipLCBase01 = new ModelRenderer(this, 128, 0);
        this.EquipLCBase01.setRotationPoint(0.0f, 1.0f, -7.0f);
        this.EquipLCBase01.addBox(0.0f, -5.5f, -10.0f, 7, 11, 10, 0.0f);
        this.setRotateAngle(this.EquipLCBase01, 0.0f, 0.08726646f, 0.0f);
        this.EquipLC02 = new ModelRenderer(this, 132, 113);
        this.EquipLC02.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.EquipLC02.addBox(-1.0f, -1.0f, -13.0f, 2, 2, 13, 0.0f);
        this.EquipRCBase02 = new ModelRenderer(this, 128, 0);
        this.EquipRCBase02.setRotationPoint(-7.0f, 0.0f, -6.5f);
        this.EquipRCBase02.addBox(-5.0f, -5.0f, -4.0f, 5, 10, 14, 0.0f);
        this.setRotateAngle(this.EquipRCBase02, -0.17453292f, -0.05235988f, 0.0f);
        this.Butt.addChild(this.LegRight);
        this.BodyMain.addChild(this.Cloth);
        this.EquipL01.addChild(this.EquipL02);
        this.BodyMain.addChild(this.Neck);
        this.Head.addChild(this.Hair);
        this.EquipBase.addChild(this.EquipBaseM01);
        this.EquipRCBase02.addChild(this.EquipRC03);
        this.BodyMain.addChild(this.BoobR);
        this.LegRight.addChild(this.ShoesR);
        this.EquipL02.addChild(this.EquipL03);
        this.EquipR03.addChild(this.EquipRCBase01);
        this.EquipLC03.addChild(this.EquipLC04);
        this.Head.addChild(this.HairMain);
        this.BodyMain.addChild(this.BoobL);
        this.EquipR04_1.addChild(this.EquipRC2Base01);
        this.EquipRC203.addChild(this.EquipRC204);
        this.Butt.addChild(this.Skirt);
        this.Skirt.addChild(this.SkirtEquip);
        this.HeadEquip.addChild(this.HeadEquip03);
        this.EquipRC03.addChild(this.EquipRC04);
        this.HairMidL01.addChild(this.HairMidL02);
        this.HeadEquip03.addChild(this.HeadEquip04);
        this.EquipR01.addChild(this.EquipR02);
        this.BodyMain.addChild(this.ArmLeft01);
        this.Butt.addChild(this.LegLeft);
        this.LegLeft.addChild(this.ShoesL);
        this.EquipBase.addChild(this.EquipBaseM03);
        this.EquipR04.addChild(this.EquipLC2Base01);
        this.EquipLC2Base02.addChild(this.EquipLC201);
        this.EquipRC01.addChild(this.EquipRC02);
        this.EquipRC2Base02.addChild(this.EquipRC203);
        this.EquipR03.addChild(this.EquipR04_1);
        this.BodyMain.addChild(this.ArmRight01);
        this.EquipBase.addChild(this.EquipBaseM02);
        this.EquipLC203.addChild(this.EquipLC204);
        this.EquipLCBase02.addChild(this.EquipLC01);
        this.Hair.addChild(this.Ahoke);
        this.HeadEquip01.addChild(this.HeadEquip02);
        this.EquipL03.addChild(this.EquipR04);
        this.BodyMain.addChild(this.Butt);
        this.HairMain.addChild(this.HairMidL01);
        this.EquipR02.addChild(this.EquipR03);
        this.ArmRight01.addChild(this.ArmRight02);
        this.Neck.addChild(this.Head);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.Head.addChild(this.HeadEquip05);
        this.EquipLC201.addChild(this.EquipLC202);
        this.Head.addChild(this.HeadEquip);
        this.EquipLC2Base01.addChild(this.EquipLC2Base02);
        this.EquipLC2Base02.addChild(this.EquipLC203);
        this.EquipLCBase02.addChild(this.EquipLCRadar);
        this.EquipRCBase02.addChild(this.EquipRC01);
        this.EquipBase.addChild(this.EquipL01);
        this.HeadEquip.addChild(this.HeadEquip01);
        this.EquipRC2Base01.addChild(this.EquipRC2Base02);
        this.EquipLCBase02.addChild(this.EquipLC03);
        this.SkirtEquip.addChild(this.EquipBase);
        this.EquipLCBase01.addChild(this.EquipLCBase02);
        this.EquipRC201.addChild(this.EquipRC202);
        this.EquipRCBase02.addChild(this.EquipRCRadar);
        this.EquipRC2Base02.addChild(this.EquipRC201);
        this.EquipBase.addChild(this.EquipR01);
        this.EquipL03.addChild(this.EquipLCBase01);
        this.EquipLC01.addChild(this.EquipLC02);
        this.EquipRCBase01.addChild(this.EquipRCBase02);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, -14.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(0.0f, -10.0f, 0.0f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        switch (((IShipEmotion)entity).getScaleLevel()) {
            case 3: {
                this.scale = 2.0f;
                this.offsetY = -0.73f;
                break;
            }
            case 2: {
                this.scale = 1.5f;
                this.offsetY = -0.48f;
                break;
            }
            case 1: {
                this.scale = 1.0f;
                this.offsetY = 0.02f;
                break;
            }
            default: {
                this.scale = 0.5f;
                this.offsetY = 1.51f;
            }
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        GlStateManager.enableLighting();
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
        boolean flag;
        int state = ent.getStateEmotion(0);
        this.HeadEquip.isHidden = flag = !EmotionHelper.checkModelState(0, state);
        this.HeadEquip05.isHidden = flag;
        this.EquipBase.isHidden = !EmotionHelper.checkModelState(1, state);
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowNeck.rotateAngleX = this.Neck.rotateAngleX;
        this.GlowNeck.rotateAngleY = this.Neck.rotateAngleY;
        this.GlowNeck.rotateAngleZ = this.Neck.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.73f + 0.28f * ent.getScaleLevel(), 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = 0.0f;
        this.Head.rotateAngleY = 0.0f;
        this.BoobL.rotateAngleX = -0.7854f;
        this.BoobR.rotateAngleX = -0.7854f;
        this.Ahoke.rotateAngleY = 0.5236f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleX = 1.48f;
        this.HairMidL01.rotateAngleX = 0.2f;
        this.HairMidL02.rotateAngleX = -0.3f;
        this.ArmLeft01.rotateAngleX = -2.97f;
        this.ArmLeft01.rotateAngleZ = 0.26f;
        this.ArmRight01.rotateAngleX = -2.8f;
        this.ArmRight01.rotateAngleZ = -1.3f;
        this.ArmRight02.rotateAngleZ = -0.9f;
        this.LegLeft.rotateAngleX = -0.26f;
        this.LegRight.rotateAngleX = -0.26f;
        this.LegLeft.rotateAngleY = 0.0f;
        this.LegRight.rotateAngleY = 0.0f;
        this.LegLeft.rotateAngleZ = -0.14f;
        this.LegRight.rotateAngleZ = 0.14f;
        this.EquipBase.isHidden = true;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float f6;
        float angleX = MathHelper.cos(f2 * 0.08f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.3f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1;
        float addk1;
        float addk2;
        boolean showCannon = EmotionHelper.checkModelState(1, ent.getStateEmotion(0));
        if (ent.getShipDepth(0) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 - 0.2118f;
        addk2 = angleAdd2 - 0.1118f;
        this.Head.rotateAngleX = f4 * 0.014f + 0.1f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.BoobL.rotateAngleX = angleX * 0.06f - 0.7854f;
        this.BoobR.rotateAngleX = angleX * 0.06f - 0.7854f;
        this.Ahoke.rotateAngleY = angleX * 0.25f + 0.5236f;
        this.BodyMain.rotateAngleX = -0.1f;
        this.HairMidL01.rotateAngleX = angleX * 0.06f + 0.2f;
        this.HairMidL02.rotateAngleX = -angleX1 * 0.09f - 0.17f;
        this.HairMidL01.rotateAngleZ = 0.0f;
        this.HairMidL02.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = angleAdd2 * 0.6f + 0.15f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft01.rotateAngleZ = angleX * 0.1f - 0.26f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.6f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = -angleX * 0.1f + 0.26f;
        this.ArmRight02.rotateAngleX = 0.0f;
        this.ArmRight02.rotateAngleY = 0.0f;
        this.ArmRight02.rotateAngleZ = 0.0f;
        this.LegLeft.rotateAngleY = 0.0f;
        this.LegLeft.rotateAngleZ = 0.05f;
        this.LegRight.rotateAngleY = 0.0f;
        this.LegRight.rotateAngleZ = -0.05f;
        if (showCannon) {
            this.EquipBase.rotateAngleX = 0.17f;
            if (this.Head.rotateAngleX <= 0.0f) {
                this.EquipLC201.rotateAngleX = this.Head.rotateAngleX * 0.9f;
                this.EquipLC203.rotateAngleX = this.Head.rotateAngleX * 1.2f;
                this.EquipRC201.rotateAngleX = this.Head.rotateAngleX * 1.1f;
                this.EquipRC203.rotateAngleX = this.Head.rotateAngleX * 0.85f;
            }
            this.EquipLCBase02.rotateAngleX = this.Head.rotateAngleX;
            this.EquipLC2Base01.rotateAngleX = 0.0f;
            this.EquipLC2Base02.rotateAngleY = this.Head.rotateAngleY;
            this.EquipLC01.rotateAngleY = angleX * 0.1f - 0.26f;
            this.EquipLC03.rotateAngleY = -angleX * 0.08f - 0.15f;
            this.EquipRCBase02.rotateAngleX = this.Head.rotateAngleX;
            this.EquipRC2Base01.rotateAngleX = 0.0f;
            this.EquipRC2Base02.rotateAngleY = this.Head.rotateAngleY;
            this.EquipRC01.rotateAngleY = angleX * 0.08f + 0.2f;
            this.EquipRC03.rotateAngleY = -angleX * 0.1f + 0.1f;
        }
        if (ent.getIsSprinting() || f1 > 0.9f) {
            this.Head.rotateAngleX -= 0.35f;
            this.BodyMain.rotateAngleX = 0.5236f;
            this.HairMidL01.rotateAngleX += 0.3f;
            this.HairMidL02.rotateAngleX += 0.3f;
            this.ArmLeft01.rotateAngleX = angleAdd2 * 1.4f - 0.1f;
            this.ArmRight01.rotateAngleX = angleAdd1 * 1.4f - 0.1f;
            this.ArmLeft01.rotateAngleZ = angleX * 0.1f - 0.4f;
            this.ArmRight01.rotateAngleZ = -angleX * 0.1f + 0.4f;
            addk1 -= 0.55f;
            addk2 -= 0.55f;
            this.LegLeft.rotateAngleY = 0.0f;
            this.LegRight.rotateAngleY = 0.0f;
            this.LegLeft.rotateAngleZ = 0.0f;
            this.LegRight.rotateAngleZ = 0.0f;
            if (showCannon) {
                this.EquipLCBase02.rotateAngleX -= 0.45f;
                this.EquipRCBase02.rotateAngleX -= 0.5f;
            }
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            this.Head.rotateAngleX -= 0.35f;
            this.BodyMain.rotateAngleX = 0.5236f;
            this.ArmLeft01.rotateAngleZ = angleX * 0.1f - 0.4f;
            this.ArmRight01.rotateAngleZ = -angleX * 0.1f + 0.4f;
            addk1 -= 0.55f;
            addk2 -= 0.55f;
            this.LegLeft.rotateAngleY = 0.0f;
            this.LegRight.rotateAngleY = 0.0f;
            this.LegLeft.rotateAngleZ = 0.0f;
            this.LegRight.rotateAngleZ = 0.0f;
            if (showCannon) {
                this.EquipLCBase02.rotateAngleX -= 0.45f;
                this.EquipRCBase02.rotateAngleX -= 0.5f;
            }
        }
        if (ent.getIsSitting() || ent.getIsRiding()) {
            if (showCannon) {
                GlStateManager.translate(0.0f, 0.42f, 0.0f);
                this.BodyMain.rotateAngleX = -0.09f;
                this.ArmLeft01.rotateAngleX = 0.52f;
                this.ArmLeft01.rotateAngleZ = -1.04f;
                this.ArmRight01.rotateAngleX = 0.52f;
                this.ArmRight01.rotateAngleZ = 1.04f;
                addk1 = -1.4f;
                addk2 = -1.4f;
                this.LegLeft.rotateAngleY = -0.14f;
                this.LegRight.rotateAngleY = 0.14f;
                this.LegLeft.rotateAngleZ = 0.0f;
                this.LegRight.rotateAngleZ = 0.0f;
                this.EquipLCBase02.rotateAngleX = 1.57f;
                this.EquipLC2Base01.rotateAngleX = 0.8f;
                this.EquipLC01.rotateAngleY = 0.0f;
                this.EquipLC03.rotateAngleY = 0.0f;
                this.EquipLC201.rotateAngleX = 0.0f;
                this.EquipLC203.rotateAngleX = 0.0f;
                this.EquipRCBase02.rotateAngleX = 1.57f;
                this.EquipRC2Base01.rotateAngleX = 0.8f;
                this.EquipRC01.rotateAngleY = 0.0f;
                this.EquipRC03.rotateAngleY = 0.0f;
                this.EquipRC201.rotateAngleX = 0.0f;
                this.EquipRC203.rotateAngleX = 0.0f;
            } else if (ent.getStateEmotion(1) == 4) {
                GlStateManager.translate(0.0f, 0.71f, 0.0f);
                this.setFaceHungry(ent);
                this.BodyMain.rotateAngleX = 1.48f;
                this.HairMidL01.rotateAngleX = 0.2f;
                this.HairMidL02.rotateAngleX = -0.3f;
                this.ArmLeft01.rotateAngleX = -2.97f;
                this.ArmLeft01.rotateAngleZ = 0.26f;
                this.ArmRight01.rotateAngleX = -2.8f;
                this.ArmRight01.rotateAngleZ = -1.3f;
                this.ArmRight02.rotateAngleZ = -0.9f;
                addk1 = -0.26f;
                addk2 = -0.26f;
                this.LegLeft.rotateAngleY = 0.0f;
                this.LegRight.rotateAngleY = 0.0f;
                this.LegLeft.rotateAngleZ = -0.14f;
                this.LegRight.rotateAngleZ = 0.14f;
            } else {
                GlStateManager.translate(0.0f, 0.52f, 0.0f);
                this.BodyMain.rotateAngleX = -0.09f;
                this.ArmLeft01.rotateAngleX = -0.63f;
                this.ArmLeft01.rotateAngleZ = 0.14f;
                this.ArmRight01.rotateAngleX = -0.63f;
                this.ArmRight01.rotateAngleZ = -0.14f;
                addk1 = -1.75f;
                addk2 = -1.75f;
                this.LegLeft.rotateAngleY = -0.14f;
                this.LegRight.rotateAngleY = 0.14f;
                this.LegLeft.rotateAngleZ = 0.0f;
                this.LegRight.rotateAngleZ = 0.0f;
            }
        }
        if (ent.getAttackTick() > 20) {
            switch (ent.getStateEmotion(5)) {
                case 0: 
                case 2: {
                    GlStateManager.translate(0.0f, this.scale * 0.35f + 0.0f, 0.0f);
                    this.Head.rotateAngleX -= 1.22f;
                    this.BodyMain.rotateAngleX = 1.75f;
                    this.HairMidL01.rotateAngleX += 0.3f;
                    this.HairMidL02.rotateAngleX += 0.6f;
                    this.ArmLeft01.rotateAngleX = -1.75f;
                    this.ArmLeft01.rotateAngleY = 0.0f;
                    this.ArmLeft01.rotateAngleZ = 0.0f;
                    this.ArmRight01.rotateAngleX = -1.05f;
                    this.ArmRight01.rotateAngleY = 2.62f;
                    this.ArmRight01.rotateAngleZ = 0.7f;
                    this.ArmRight02.rotateAngleZ = -0.79f;
                    addk1 = -1.75f;
                    addk2 = -2.27f;
                    this.LegLeft.rotateAngleY = -0.44f;
                    this.LegRight.rotateAngleY = 0.44f;
                    this.LegLeft.rotateAngleZ = 0.0f;
                    this.LegRight.rotateAngleZ = 0.0f;
                    this.EquipBase.rotateAngleX = -1.22f;
                    this.EquipLCBase02.rotateAngleX -= 0.5f;
                    this.EquipRCBase02.rotateAngleX -= 0.5f;
                    break;
                }
                default: {
                    this.BodyMain.rotateAngleX = -0.17f;
                    this.ArmLeft01.rotateAngleX = -1.57f;
                    this.ArmLeft01.rotateAngleY = -0.26f;
                    this.ArmLeft01.rotateAngleZ = 0.0f;
                    this.ArmRight01.rotateAngleX = 0.0f;
                    this.ArmRight01.rotateAngleZ = 0.87f;
                    this.ArmRight02.rotateAngleZ = -1.57f;
                    addk1 += 0.2618f;
                    addk2 += 0.2618f;
                    this.LegLeft.rotateAngleY = 0.0f;
                    this.LegRight.rotateAngleY = 0.0f;
                    this.LegLeft.rotateAngleZ = -0.17f;
                    this.LegRight.rotateAngleZ = 0.17f;
                }
            }
        }
        if ((f6 = ent.getSwingTime(f2 - (int)f2)) != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX = -0.4f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = -0.2f;
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 0.2f;
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
            this.ArmRight02.rotateAngleX = 0.0f;
            this.ArmRight02.rotateAngleY = 0.0f;
            this.ArmRight02.rotateAngleZ = 0.0f;
        }
        float headX = this.Head.rotateAngleX * -0.5f;
        float headZ = this.Head.rotateAngleZ * -0.5f;
        this.HairMidL01.rotateAngleX += headX;
        this.HairMidL01.rotateAngleZ += headZ;
        this.HairMidL02.rotateAngleX += headX * 0.5f;
        this.HairMidL02.rotateAngleZ += headZ * 0.5f;
        this.LegLeft.rotateAngleX = addk1;
        this.LegRight.rotateAngleX = addk2;
    }
}
