package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.IShipEmotion;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelMountAfH
extends ModelBase {
    private final ModelRenderer BodyMain;
    private final ModelRenderer ChestCannon01a;
    private final ModelRenderer ChestCannon02a;
    private final ModelRenderer ChestCannon03a;
    private final ModelRenderer EquipBaseL;
    private final ModelRenderer EquipBaseR;
    private final ModelRenderer Neck;
    private final ModelRenderer EquipL01;
    private final ModelRenderer EquipL02;
    private final ModelRenderer EquipCannonPlate;
    private final ModelRenderer EquipCannon01;
    private final ModelRenderer EquipCannon02;
    private final ModelRenderer EquipR01;
    private final ModelRenderer EquipR02;
    private final ModelRenderer EquipCannonPlate_1;
    private final ModelRenderer EquipCannon01_1;
    private final ModelRenderer EquipCannon02_1;
    private final ModelRenderer Head;
    private final ModelRenderer Jaw;
    private final ModelRenderer HeadBack01;
    private final ModelRenderer NeckBack;
    private final ModelRenderer HeadBack03;
    private final ModelRenderer NeckFront;
    private final ModelRenderer CannonBase;
    private final ModelRenderer HeadTooth;
    private final ModelRenderer HeadTooth2;
    private final ModelRenderer JawTooth;
    private final ModelRenderer JawTooth2;
    private final ModelRenderer Cannon01;
    private final ModelRenderer Cannon02;
    private final ModelRenderer Cannon03;
    private final ModelRenderer Cannon04;
    private final ModelRenderer Cannon05;
    private final ModelRenderer Cannon06;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowJaw;
    private final ModelRenderer GlowHead;
    private final ModelRenderer GlowCannonBase;
    private final ModelRenderer GlowCannon04;
    private final ModelRenderer GlowEquipBaseL;
    private final ModelRenderer GlowEquipL01;
    private final ModelRenderer GlowEquipL02;
    private final ModelRenderer GlowEquipBaseR;
    private final ModelRenderer GlowEquipR01;

    public ModelMountAfH() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.EquipCannon02_1 = new ModelRenderer(this, 73, 0);
        this.EquipCannon02_1.setRotationPoint(1.5f, 4.0f, 0.5f);
        this.EquipCannon02_1.addBox(0.0f, 0.0f, -7.0f, 1, 1, 7, 0.0f);
        this.setRotateAngle(this.EquipCannon02_1, 0.18203785f, 0.091106184f, 0.0f);
        this.EquipCannon02 = new ModelRenderer(this, 73, 0);
        this.EquipCannon02.setRotationPoint(1.5f, 4.0f, 0.5f);
        this.EquipCannon02.addBox(0.0f, 0.0f, -7.0f, 1, 1, 7, 0.0f);
        this.setRotateAngle(this.EquipCannon02, 0.0f, -0.08726646f, 0.0f);
        this.EquipR02 = new ModelRenderer(this, 0, 0);
        this.EquipR02.setRotationPoint(0.0f, -3.0f, 0.0f);
        this.EquipR02.addBox(-5.5f, 0.0f, -9.0f, 11, 4, 23, 0.0f);
        this.setRotateAngle(this.EquipR02, 0.05235988f, 0.0f, 0.0f);
        this.Cannon01 = new ModelRenderer(this, 0, 0);
        this.Cannon01.setRotationPoint(2.0f, -9.0f, 0.0f);
        this.Cannon01.addBox(0.0f, 0.0f, -10.0f, 3, 3, 10, 0.0f);
        this.HeadTooth = new ModelRenderer(this, 62, 98);
        this.HeadTooth.setRotationPoint(0.0f, 2.0f, -15.0f);
        this.HeadTooth.addBox(-9.0f, 0.0f, -6.5f, 18, 4, 15, 0.0f);
        this.setRotateAngle(this.HeadTooth, 0.05235988f, 0.0f, 0.0f);
        this.EquipL01 = new ModelRenderer(this, 0, 0);
        this.EquipL01.setRotationPoint(0.0f, -8.0f, 1.0f);
        this.EquipL01.addBox(-6.0f, 0.0f, -7.0f, 10, 9, 20, 0.0f);
        this.setRotateAngle(this.EquipL01, -0.13962634f, 0.0f, 0.0f);
        this.Cannon02 = new ModelRenderer(this, 0, 0);
        this.Cannon02.setRotationPoint(-3.0f, -9.0f, 0.0f);
        this.Cannon02.addBox(0.0f, 0.0f, -10.0f, 3, 3, 10, 0.0f);
        this.JawTooth = new ModelRenderer(this, 63, 99);
        this.JawTooth.setRotationPoint(0.0f, -1.6f, -0.3f);
        this.JawTooth.addBox(-9.0f, 0.0f, -14.0f, 18, 3, 14, 0.0f);
        this.setRotateAngle(this.JawTooth, -0.08726646f, -0.022340214f, 0.0f);
        this.Cannon05 = new ModelRenderer(this, 0, 0);
        this.Cannon05.setRotationPoint(0.0f, -14.6f, 0.5f);
        this.Cannon05.addBox(0.0f, 0.0f, -10.0f, 2, 2, 10, 0.0f);
        this.setRotateAngle(this.Cannon05, -0.05235988f, 0.0f, 0.0f);
        this.CannonBase = new ModelRenderer(this, 0, 0);
        this.CannonBase.setRotationPoint(-1.0f, -16.0f, 7.0f);
        this.CannonBase.addBox(-4.0f, -14.0f, 0.0f, 10, 14, 4, 0.0f);
        this.setRotateAngle(this.CannonBase, -0.5235988f, 0.0f, 0.0f);
        this.ChestCannon01a = new ModelRenderer(this, 0, 0);
        this.ChestCannon01a.setRotationPoint(3.3f, 6.0f, -2.0f);
        this.ChestCannon01a.addBox(0.0f, 0.0f, 0.0f, 5, 5, 17, 0.0f);
        this.setRotateAngle(this.ChestCannon01a, 0.08726646f, 0.0f, 0.0f);
        this.EquipBaseL = new ModelRenderer(this, 0, 10);
        this.EquipBaseL.setRotationPoint(14.5f, 2.0f, 5.0f);
        this.EquipBaseL.addBox(-6.0f, 0.0f, -10.0f, 11, 6, 21, 0.0f);
        this.setRotateAngle(this.EquipBaseL, 0.0f, -0.08726646f, 0.0f);
        this.Cannon04 = new ModelRenderer(this, 0, 0);
        this.Cannon04.setRotationPoint(1.0f, -13.5f, 0.0f);
        this.Cannon04.addBox(0.0f, 0.0f, -13.0f, 4, 4, 13, 0.0f);
        this.setRotateAngle(this.Cannon04, 0.0f, 0.0f, 0.7853982f);
        this.Cannon03 = new ModelRenderer(this, 0, 0);
        this.Cannon03.setRotationPoint(-3.5f, -11.3f, 0.0f);
        this.Cannon03.addBox(0.0f, 0.0f, -9.0f, 2, 2, 9, 0.0f);
        this.HeadBack03 = new ModelRenderer(this, 0, 0);
        this.HeadBack03.setRotationPoint(-4.0f, -16.1f, 14.5f);
        this.HeadBack03.addBox(0.0f, 0.0f, 0.0f, 8, 18, 8, 0.0f);
        this.setRotateAngle(this.HeadBack03, 0.091106184f, 0.0f, 0.0f);
        this.ChestCannon03a = new ModelRenderer(this, 0, 0);
        this.ChestCannon03a.setRotationPoint(-8.3f, 6.0f, -2.0f);
        this.ChestCannon03a.addBox(0.0f, 0.0f, 0.0f, 5, 5, 17, 0.0f);
        this.setRotateAngle(this.ChestCannon03a, 0.08726646f, 0.0f, 0.0f);
        this.NeckBack = new ModelRenderer(this, 0, 0);
        this.NeckBack.setRotationPoint(-2.0f, -6.0f, 11.0f);
        this.NeckBack.addBox(0.0f, 0.0f, 0.0f, 5, 5, 5, 0.0f);
        this.Cannon06 = new ModelRenderer(this, 74, 0);
        this.Cannon06.setRotationPoint(1.0f, 1.0f, -13.0f);
        this.Cannon06.addBox(0.0f, 0.0f, -15.0f, 2, 2, 15, 0.0f);
        this.HeadBack01 = new ModelRenderer(this, 0, 0);
        this.HeadBack01.setRotationPoint(-4.0f, -18.0f, 8.0f);
        this.HeadBack01.addBox(0.0f, 0.0f, 0.0f, 8, 8, 11, 0.0f);
        this.setRotateAngle(this.HeadBack01, -0.13962634f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer(this, 70, 58);
        this.Neck.setRotationPoint(-29.0f, 5.0f, 6.0f);
        this.Neck.addBox(-7.5f, -15.0f, -3.0f, 15, 15, 14, 0.0f);
        this.setRotateAngle(this.Neck, 0.0f, 0.2617994f, 0.0f);
        this.Head = new ModelRenderer(this, 0, 94);
        this.Head.setRotationPoint(0.0f, -15.0f, 7.0f);
        this.Head.addBox(-9.5f, -7.0f, -22.0f, 19, 10, 24, 0.0f);
        this.setRotateAngle(this.Head, -0.20943952f, 0.0f, 0.0f);
        this.EquipBaseR = new ModelRenderer(this, 0, 10);
        this.EquipBaseR.setRotationPoint(-13.5f, 2.0f, 5.0f);
        this.EquipBaseR.addBox(-6.0f, 0.0f, -10.0f, 11, 6, 21, 0.0f);
        this.setRotateAngle(this.EquipBaseR, 0.0f, 0.08726646f, 0.0f);
        this.EquipCannon01_1 = new ModelRenderer(this, 73, 0);
        this.EquipCannon01_1.setRotationPoint(1.5f, 1.0f, 0.5f);
        this.EquipCannon01_1.addBox(0.0f, 0.0f, -7.0f, 1, 1, 7, 0.0f);
        this.setRotateAngle(this.EquipCannon01_1, -0.18203785f, 0.13665928f, 0.0f);
        this.HeadTooth2 = new ModelRenderer(this, 65, 99);
        this.HeadTooth2.mirror = true;
        this.HeadTooth2.setRotationPoint(0.0f, 3.6f, -6.5f);
        this.HeadTooth2.addBox(-8.0f, 0.0f, -14.0f, 16, 3, 14, 0.0f);
        this.setRotateAngle(this.HeadTooth2, 0.17453292f, 0.0f, 0.0f);
        this.EquipR01 = new ModelRenderer(this, 0, 0);
        this.EquipR01.setRotationPoint(0.0f, -8.0f, 1.0f);
        this.EquipR01.addBox(-5.0f, 0.0f, -7.0f, 10, 9, 20, 0.0f);
        this.setRotateAngle(this.EquipR01, -0.13962634f, 0.0f, 0.0f);
        this.EquipCannonPlate_1 = new ModelRenderer(this, 0, 0);
        this.EquipCannonPlate_1.setRotationPoint(-2.0f, 2.0f, -8.0f);
        this.EquipCannonPlate_1.addBox(0.0f, 0.0f, 0.0f, 4, 6, 1, 0.0f);
        this.EquipCannonPlate = new ModelRenderer(this, 0, 0);
        this.EquipCannonPlate.setRotationPoint(-2.0f, 2.0f, -8.0f);
        this.EquipCannonPlate.addBox(0.0f, 0.0f, 0.0f, 4, 6, 1, 0.0f);
        this.Jaw = new ModelRenderer(this, 0, 68);
        this.Jaw.mirror = true;
        this.Jaw.setRotationPoint(0.0f, -3.0f, 0.5f);
        this.Jaw.addBox(-9.5f, 0.0f, -15.0f, 19, 7, 19, 0.0f);
        this.setRotateAngle(this.Jaw, 0.5462881f, 0.0f, 0.0f);
        this.EquipCannon01 = new ModelRenderer(this, 73, 0);
        this.EquipCannon01.setRotationPoint(1.5f, 1.0f, 0.5f);
        this.EquipCannon01.addBox(0.0f, 0.0f, -7.0f, 1, 1, 7, 0.0f);
        this.setRotateAngle(this.EquipCannon01, -0.31869712f, -0.08726646f, 0.0f);
        this.NeckFront = new ModelRenderer(this, 0, 52);
        this.NeckFront.setRotationPoint(0.0f, -14.0f, -5.0f);
        this.NeckFront.addBox(-6.5f, 0.0f, 0.0f, 13, 14, 2, 0.0f);
        this.EquipL02 = new ModelRenderer(this, 0, 0);
        this.EquipL02.setRotationPoint(0.0f, -3.0f, 0.0f);
        this.EquipL02.addBox(-6.5f, 0.0f, -9.0f, 11, 4, 23, 0.0f);
        this.setRotateAngle(this.EquipL02, 0.05235988f, 0.0f, 0.0f);
        this.ChestCannon02a = new ModelRenderer(this, 0, 0);
        this.ChestCannon02a.setRotationPoint(-2.5f, 6.0f, -2.0f);
        this.ChestCannon02a.addBox(0.0f, 0.0f, 0.0f, 5, 5, 17, 0.0f);
        this.setRotateAngle(this.ChestCannon02a, 0.08726646f, 0.0f, 0.0f);
        this.JawTooth2 = new ModelRenderer(this, 66, 100);
        this.JawTooth2.mirror = true;
        this.JawTooth2.setRotationPoint(0.0f, -2.6f, 0.0f);
        this.JawTooth2.addBox(-8.0f, 0.0f, -13.0f, 16, 3, 13, 0.0f);
        this.setRotateAngle(this.JawTooth2, -0.13962634f, 0.0f, 0.0f);
        this.BodyMain = new ModelRenderer(this, 0, 0);
        this.BodyMain.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.BodyMain.addBox(-9.0f, -7.0f, 10.0f, 18, 12, 9, 0.0f);
        this.EquipR01.addChild(this.EquipR02);
        this.CannonBase.addChild(this.Cannon01);
        this.EquipBaseL.addChild(this.EquipL01);
        this.CannonBase.addChild(this.Cannon02);
        this.CannonBase.addChild(this.Cannon05);
        this.Neck.addChild(this.CannonBase);
        this.BodyMain.addChild(this.ChestCannon01a);
        this.BodyMain.addChild(this.EquipBaseL);
        this.CannonBase.addChild(this.Cannon04);
        this.CannonBase.addChild(this.Cannon03);
        this.Neck.addChild(this.HeadBack03);
        this.BodyMain.addChild(this.ChestCannon03a);
        this.Neck.addChild(this.NeckBack);
        this.Neck.addChild(this.HeadBack01);
        this.BodyMain.addChild(this.Neck);
        this.Neck.addChild(this.Head);
        this.BodyMain.addChild(this.EquipBaseR);
        this.EquipBaseR.addChild(this.EquipR01);
        this.Neck.addChild(this.Jaw);
        this.EquipL01.addChild(this.EquipL02);
        this.BodyMain.addChild(this.ChestCannon02a);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(-29.0f, 5.0f, 6.0f);
        this.setRotateAngle(this.GlowNeck, 0.0f, 0.2617994f, 0.0f);
        this.GlowJaw = new ModelRenderer(this, 0, 0);
        this.GlowJaw.setRotationPoint(0.0f, -3.0f, 0.5f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -15.0f, 7.0f);
        this.setRotateAngle(this.GlowHead, -0.20943952f, 0.0f, 0.0f);
        this.GlowCannonBase = new ModelRenderer(this, 0, 0);
        this.GlowCannonBase.setRotationPoint(-1.0f, -16.0f, 7.0f);
        this.setRotateAngle(this.GlowCannonBase, -0.5235988f, 0.0f, 0.0f);
        this.GlowCannon04 = new ModelRenderer(this, 0, 0);
        this.GlowCannon04.setRotationPoint(1.0f, -13.5f, 0.0f);
        this.setRotateAngle(this.GlowCannon04, 0.0f, 0.0f, 0.7853982f);
        this.GlowEquipBaseL = new ModelRenderer(this, 0, 0);
        this.GlowEquipBaseL.setRotationPoint(14.5f, 2.0f, 5.0f);
        this.setRotateAngle(this.GlowEquipBaseL, 0.0f, -0.08726646f, 0.0f);
        this.GlowEquipL01 = new ModelRenderer(this, 0, 0);
        this.GlowEquipL01.setRotationPoint(0.0f, -8.0f, 1.0f);
        this.setRotateAngle(this.GlowEquipL01, -0.13962634f, 0.0f, 0.0f);
        this.GlowEquipL02 = new ModelRenderer(this, 0, 0);
        this.GlowEquipL02.setRotationPoint(0.0f, -3.0f, 0.0f);
        this.setRotateAngle(this.GlowEquipL02, 0.05235988f, 0.0f, 0.0f);
        this.GlowEquipBaseR = new ModelRenderer(this, 0, 0);
        this.GlowEquipBaseR.setRotationPoint(-13.5f, 2.0f, 5.0f);
        this.setRotateAngle(this.GlowEquipBaseR, 0.0f, 0.08726646f, 0.0f);
        this.GlowEquipR01 = new ModelRenderer(this, 0, 0);
        this.GlowEquipR01.setRotationPoint(0.0f, -8.0f, 1.0f);
        this.setRotateAngle(this.GlowEquipR01, -0.13962634f, 0.0f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowJaw);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowNeck.addChild(this.NeckFront);
        this.GlowHead.addChild(this.HeadTooth);
        this.GlowHead.addChild(this.HeadTooth2);
        this.GlowJaw.addChild(this.JawTooth);
        this.GlowJaw.addChild(this.JawTooth2);
        this.GlowNeck.addChild(this.GlowCannonBase);
        this.GlowCannonBase.addChild(this.GlowCannon04);
        this.GlowCannon04.addChild(this.Cannon06);
        this.GlowBodyMain.addChild(this.GlowEquipBaseL);
        this.GlowEquipBaseL.addChild(this.GlowEquipL01);
        this.GlowEquipL01.addChild(this.GlowEquipL02);
        this.GlowEquipL01.addChild(this.EquipCannonPlate);
        this.EquipCannonPlate.addChild(this.EquipCannon01);
        this.EquipCannonPlate.addChild(this.EquipCannon02);
        this.GlowBodyMain.addChild(this.GlowEquipBaseR);
        this.GlowEquipBaseR.addChild(this.GlowEquipR01);
        this.GlowEquipR01.addChild(this.EquipCannonPlate_1);
        this.EquipCannonPlate_1.addChild(this.EquipCannon01_1);
        this.EquipCannonPlate_1.addChild(this.EquipCannon02_1);
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(0.7f, 0.7f, 0.7f);
        GlStateManager.translate(0.0f, 1.1f, -0.47f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableBlend();
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        GlStateManager.enableLighting();
        GlStateManager.popMatrix();
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        IShipEmotion ent = (IShipEmotion)entity;
        this.motionHumanPos(f2, ent);
    }

    private void motionHumanPos(float f2, IShipEmotion ent) {
        float angleX = MathHelper.cos(f2 * 0.08f);
        if (ent.getShipDepth(0) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.025f + 0.025f, 0.0f);
        }
        this.GlowJaw.rotateAngleX = this.Jaw.rotateAngleX = angleX * 0.1f + 0.4f;
        this.EquipCannon01.rotateAngleX = angleX * 0.08f - 0.32f;
        this.EquipCannon02.rotateAngleX = -angleX * 0.14f;
        this.EquipCannon01_1.rotateAngleX = -angleX * 0.12f - 0.18f;
        this.EquipCannon02_1.rotateAngleX = angleX * 0.08f + 0.18f;
        if (ent.getStateEmotion(1) > 0) {
            // empty if block
        }
    }
}
