package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.BasicEntityMount;
import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelCarrierWDemon
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer Butt;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer Cloth01;
    private final ModelRenderer EquipBase;
    private final ModelRenderer Head;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ShipModelRenderer HeadS01;
    private final ModelRenderer HeadS04;
    private final ModelRenderer HeadS05;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairL01;
    private final ModelRenderer HairR01;
    private final ModelRenderer HairL02;
    private final ModelRenderer HairR02;
    private final ModelRenderer Hair01;
    private final ModelRenderer Hair02;
    private final ModelRenderer Hair03;
    private final ModelRenderer HeadS02;
    private final ModelRenderer HeadS03;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer Skirt01;
    private final ModelRenderer LegRight02;
    private final ModelRenderer ShoesR01;
    private final ModelRenderer ShoesR02;
    private final ModelRenderer ShoesR03;
    private final ModelRenderer ShoesR04;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer ShoesL01;
    private final ModelRenderer ShoesL02;
    private final ModelRenderer ShoesL03;
    private final ModelRenderer ShoesL04;
    private final ModelRenderer Skirt02;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmLeft03;
    private final ModelRenderer ArmLeft04;
    private final ModelRenderer ArmLeft05;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer ArmRight03;
    private final ModelRenderer ArmRight04;
    private final ModelRenderer ArmRight05;
    private final ModelRenderer EquipL01;
    private final ModelRenderer EquipR01;
    private final ModelRenderer EquipL02;
    private final ModelRenderer EquipL03;
    private final ModelRenderer EquipL04;
    private final ModelRenderer EquipL05;
    private final ModelRenderer EquipR02;
    private final ModelRenderer EquipR03;
    private final ModelRenderer EquipR04;
    private final ModelRenderer EquipR05;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowBodyMain2;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;

    public ModelCarrierWDemon() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.scale = 0.47f;
        this.offsetY = 1.7f;
        this.offsetItem = new float[]{0.06f, 0.98f, -0.06f};
        this.offsetBlock = new float[]{0.06f, 0.98f, -0.06f};
        this.setDefaultFaceModel();
        this.Cloth01 = new ModelRenderer(this, 0, 9);
        this.Cloth01.setRotationPoint(0.5f, -4.7f, -6.3f);
        this.Cloth01.addBox(-3.5f, 0.0f, 0.0f, 6, 7, 0, 0.0f);
        this.Hair = new ModelRenderer(this, 50, 77);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.0f);
        this.Hair.addBox(-8.0f, -8.0f, -7.2f, 16, 16, 8, 0.0f);
        this.HeadS05 = new ModelRenderer(this, 0, 0);
        this.HeadS05.setRotationPoint(-8.1f, -7.5f, -6.7f);
        this.HeadS05.addBox(0.0f, 0.0f, 0.0f, 0, 3, 3, 0.0f);
        this.setRotateAngle(this.HeadS05, 0.7853982f, 0.0f, 0.0f);
        this.ArmLeft03 = new ModelRenderer(this, 100, 14);
        this.ArmLeft03.mirror = true;
        this.ArmLeft03.setRotationPoint(2.0f, 10.0f, 3.0f);
        this.ArmLeft03.addBox(-5.5f, 0.0f, -6.5f, 7, 8, 7, 0.0f);
        this.LegLeft02 = new ModelRenderer(this, 0, 95);
        this.LegLeft02.mirror = true;
        this.LegLeft02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegLeft02.addBox(-3.0f, 0.0f, 0.0f, 6, 3, 6, 0.0f);
        this.EquipBase = new ModelRenderer(this, 0, 0);
        this.EquipBase.setRotationPoint(0.0f, -23.0f, 0.0f);
        this.EquipBase.addBox(0.0f, 0.0f, 0.0f, 0, 0, 0, 0.0f);
        this.EquipL04 = new ModelRenderer(this, 67, 14);
        this.EquipL04.mirror = true;
        this.EquipL04.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.EquipL04.addBox(0.0f, 0.0f, -6.5f, 2, 9, 13, 0.0f);
        this.Ahoke = new ModelRenderer(this, 104, 29);
        this.Ahoke.setRotationPoint(0.0f, -9.0f, -5.5f);
        this.Ahoke.addBox(0.0f, -4.0f, -11.5f, 0, 12, 12, 0.0f);
        this.setRotateAngle(this.Ahoke, 0.0f, 0.6981317f, 0.0f);
        this.HairR02 = new ModelRenderer(this, 86, 101);
        this.HairR02.mirror = true;
        this.HairR02.setRotationPoint(0.2f, 7.0f, 0.0f);
        this.HairR02.addBox(-1.0f, 0.0f, 0.0f, 2, 9, 4, 0.0f);
        this.setRotateAngle(this.HairR02, 0.17453292f, 0.0f, -0.05235988f);
        this.Skirt02 = new ModelRenderer(this, 42, 47);
        this.Skirt02.setRotationPoint(0.0f, 2.8f, -0.5f);
        this.Skirt02.addBox(-9.0f, 0.0f, -6.0f, 18, 4, 10, 0.0f);
        this.EquipL02 = new ModelRenderer(this, 0, 0);
        this.EquipL02.mirror = true;
        this.EquipL02.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.EquipL02.addBox(-0.5f, 0.0f, -10.0f, 3, 2, 20, 0.0f);
        this.ArmRight01 = new ModelRenderer(this, 2, 85);
        this.ArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 5, 5, 0.0f);
        this.ArmLeft02 = new ModelRenderer(this, 25, 85);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(0.5f, 3.0f, 0.0f);
        this.ArmLeft02.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.HeadS03 = new ModelRenderer(this, 0, 0);
        this.HeadS03.setRotationPoint(-2.5f, 2.9f, 0.0f);
        this.HeadS03.addBox(0.0f, 0.0f, 0.0f, 3, 3, 0, 0.0f);
        this.ShoesL04 = new ModelRenderer(this, 32, 0);
        this.ShoesL04.mirror = true;
        this.ShoesL04.setRotationPoint(0.0f, 3.0f, -1.0f);
        this.ShoesL04.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.setRotateAngle(this.ShoesL04, -0.12f, 0.0f, 0.0f);
        this.HeadS02 = new ModelRenderer(this, 0, 0);
        this.HeadS02.setRotationPoint(2.9f, -2.5f, 0.0f);
        this.HeadS02.addBox(0.0f, 0.0f, 0.0f, 3, 3, 0, 0.0f);
        this.ShoesR04 = new ModelRenderer(this, 32, 0);
        this.ShoesR04.setRotationPoint(0.0f, 3.0f, -1.0f);
        this.ShoesR04.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.setRotateAngle(this.ShoesR04, -0.12f, 0.0f, 0.0f);
        this.ShoesL02 = new ModelRenderer(this, 98, 0);
        this.ShoesL02.mirror = true;
        this.ShoesL02.setRotationPoint(0.0f, 3.0f, -0.7f);
        this.ShoesL02.addBox(-3.5f, 0.0f, -4.0f, 7, 4, 8, 0.0f);
        this.ArmLeft05 = new ModelRenderer(this, 72, 36);
        this.ArmLeft05.mirror = true;
        this.ArmLeft05.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.ArmLeft05.addBox(-2.5f, 0.0f, -3.0f, 5, 5, 6, 0.0f);
        this.EquipL01 = new ModelRenderer(this, 0, 0);
        this.EquipL01.mirror = true;
        this.EquipL01.setRotationPoint(30.0f, 0.0f, 0.0f);
        this.EquipL01.addBox(0.0f, 0.0f, -3.5f, 2, 2, 7, 0.0f);
        this.ArmLeft04 = new ModelRenderer(this, 54, 49);
        this.ArmLeft04.mirror = true;
        this.ArmLeft04.setRotationPoint(-2.0f, 8.0f, -3.0f);
        this.ArmLeft04.addBox(-4.0f, 0.0f, -4.0f, 8, 4, 8, 0.0f);
        this.setRotateAngle(this.ArmLeft04, 0.0f, -0.08726646f, 0.0f);
        this.HairR01 = new ModelRenderer(this, 86, 101);
        this.HairR01.mirror = true;
        this.HairR01.setRotationPoint(-7.0f, 3.0f, -5.5f);
        this.HairR01.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 4, 0.0f);
        this.setRotateAngle(this.HairR01, -0.13962634f, 0.17453292f, 0.08726646f);
        this.BodyMain = new ModelRenderer(this, 0, 104);
        this.BodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 17, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.10471976f, 0.0f, 0.0f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.HairL01 = new ModelRenderer(this, 86, 101);
        this.HairL01.setRotationPoint(7.0f, 3.0f, -5.5f);
        this.HairL01.addBox(-1.0f, 0.0f, 0.0f, 2, 8, 4, 0.0f);
        this.setRotateAngle(this.HairL01, -0.13962634f, -0.17453292f, -0.08726646f);
        this.HairL02 = new ModelRenderer(this, 86, 101);
        this.HairL02.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.HairL02.addBox(-1.0f, 0.0f, 0.0f, 2, 9, 4, 0.0f);
        this.setRotateAngle(this.HairL02, 0.17453292f, 0.0f, 0.08726646f);
        this.Hair02 = new ModelRenderer(this, 0, 58);
        this.Hair02.setRotationPoint(0.0f, 13.5f, 5.5f);
        this.Hair02.addBox(-8.0f, 0.0f, -5.0f, 16, 16, 8, 0.0f);
        this.setRotateAngle(this.Hair02, -0.08726646f, 0.0f, 0.0f);
        this.ShoesR03 = new ModelRenderer(this, 66, 0);
        this.ShoesR03.setRotationPoint(0.0f, 4.0f, -0.9f);
        this.ShoesR03.addBox(-4.0f, 0.0f, -4.0f, 8, 4, 8, 0.0f);
        this.EquipL03 = new ModelRenderer(this, 43, 0);
        this.EquipL03.mirror = true;
        this.EquipL03.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.EquipL03.addBox(0.0f, 0.0f, -8.5f, 2, 9, 17, 0.0f);
        this.EquipR01 = new ModelRenderer(this, 0, 0);
        this.EquipR01.setRotationPoint(-30.0f, 0.0f, 0.0f);
        this.EquipR01.addBox(-2.0f, 0.0f, -3.5f, 2, 2, 7, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 2, 85);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 5, 5, 0.0f);
        this.LegLeft01 = new ModelRenderer(this, 0, 84);
        this.LegLeft01.mirror = true;
        this.LegLeft01.setRotationPoint(4.8f, 5.5f, -2.6f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.EquipL05 = new ModelRenderer(this, 46, 29);
        this.EquipL05.mirror = true;
        this.EquipL05.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.EquipL05.addBox(0.0f, 0.0f, -4.5f, 2, 9, 9, 0.0f);
        this.Skirt01 = new ModelRenderer(this, 0, 22);
        this.Skirt01.setRotationPoint(0.0f, 2.9f, 0.0f);
        this.Skirt01.addBox(-8.5f, 0.0f, -6.0f, 17, 4, 9, 0.0f);
        this.EquipR05 = new ModelRenderer(this, 46, 29);
        this.EquipR05.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.EquipR05.addBox(-2.0f, 0.0f, -4.5f, 2, 9, 9, 0.0f);
        this.HairMain = new ModelRenderer(this, 0, 57);
        this.HairMain.setRotationPoint(0.0f, -15.0f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 12, 10, 0.0f);
        this.HeadS01 = new ShipModelRenderer(this, 0, 0);
        this.HeadS01.setRotationPoint(0.0f, -14.0f, -7.4f);
        this.HeadS01.addBox(0.0f, 0.0f, 0.0f, 3, 3, 0, 0.0f);
        this.HeadS01.tweakModel = true;
        this.HeadS01.scale2x = 1.0f;
        this.HeadS01.scale2y = 0.7f;
        this.HeadS01.scale2z = 1.0f;
        this.HeadS01.trans2x = 0.0f;
        this.HeadS01.trans2y = -0.25f;
        this.HeadS01.trans2z = 0.0f;
        this.setRotateAngle(this.HeadS01, 0.0f, 0.0f, 0.7853982f);
        this.LegRight02 = new ModelRenderer(this, 0, 95);
        this.LegRight02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegRight02.addBox(-3.0f, 0.0f, 0.0f, 6, 3, 6, 0.0f);
        this.Hair01 = new ModelRenderer(this, 0, 57);
        this.Hair01.setRotationPoint(0.0f, 9.0f, 1.0f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 17, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.20943952f, 0.0f, 0.0f);
        this.EquipR03 = new ModelRenderer(this, 43, 0);
        this.EquipR03.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.EquipR03.addBox(-2.0f, 0.0f, -8.5f, 2, 9, 17, 0.0f);
        this.Butt = new ModelRenderer(this, 52, 61);
        this.Butt.setRotationPoint(0.0f, 4.0f, 1.3f);
        this.Butt.addBox(-7.5f, 0.0f, -5.7f, 15, 8, 8, 0.0f);
        this.EquipR04 = new ModelRenderer(this, 67, 14);
        this.EquipR04.setRotationPoint(0.0f, 9.0f, 0.0f);
        this.EquipR04.addBox(-2.0f, 0.0f, -6.5f, 2, 9, 13, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 25, 85);
        this.ArmRight02.setRotationPoint(-0.5f, 3.0f, 0.0f);
        this.ArmRight02.addBox(-3.0f, 0.0f, -3.0f, 6, 10, 6, 0.0f);
        this.ArmRight05 = new ModelRenderer(this, 72, 36);
        this.ArmRight05.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.ArmRight05.addBox(-2.5f, 0.0f, -3.0f, 5, 5, 6, 0.0f);
        this.Hair03 = new ModelRenderer(this, 0, 35);
        this.Hair03.setRotationPoint(0.0f, 12.5f, -0.1f);
        this.Hair03.addBox(-8.0f, 0.0f, -4.5f, 16, 15, 7, 0.0f);
        this.setRotateAngle(this.Hair03, -0.13962634f, 0.0f, 0.0f);
        this.BoobL = new ModelRenderer(this, 33, 101);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.7f, -8.1f, -3.7f);
        this.BoobL.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobL, -0.6981317f, 0.13962634f, 0.08726646f);
        this.ShoesL03 = new ModelRenderer(this, 66, 0);
        this.ShoesL03.mirror = true;
        this.ShoesL03.setRotationPoint(0.0f, 4.0f, -0.9f);
        this.ShoesL03.addBox(-4.0f, 0.0f, -4.0f, 8, 4, 8, 0.0f);
        this.BoobR = new ModelRenderer(this, 33, 101);
        this.BoobR.setRotationPoint(-3.7f, -8.1f, -3.7f);
        this.BoobR.addBox(-3.5f, 0.0f, 0.0f, 7, 5, 5, 0.0f);
        this.setRotateAngle(this.BoobR, -0.6981317f, -0.13962634f, -0.08726646f);
        this.ShoesR01 = new ModelRenderer(this, 99, 1);
        this.ShoesR01.setRotationPoint(0.0f, 1.0f, 2.6f);
        this.ShoesR01.addBox(-3.5f, 0.0f, -3.5f, 7, 4, 7, 0.0f);
        this.setRotateAngle(this.ShoesR01, 0.2617994f, 0.0f, 0.0f);
        this.ShoesL01 = new ModelRenderer(this, 99, 1);
        this.ShoesL01.mirror = true;
        this.ShoesL01.setRotationPoint(0.0f, 1.0f, 2.6f);
        this.ShoesL01.addBox(-3.5f, 0.0f, -3.5f, 7, 3, 7, 0.0f);
        this.setRotateAngle(this.ShoesL01, 0.2617994f, 0.0f, 0.0f);
        this.HeadS04 = new ModelRenderer(this, 0, 0);
        this.HeadS04.setRotationPoint(8.1f, -7.5f, -6.7f);
        this.HeadS04.addBox(0.0f, 0.0f, 0.0f, 0, 3, 3, 0.0f);
        this.setRotateAngle(this.HeadS04, 0.7853982f, 0.0f, 0.0f);
        this.Neck = new ModelRenderer(this, 88, 29);
        this.Neck.setRotationPoint(0.0f, -10.3f, -0.2f);
        this.Neck.addBox(-5.5f, -2.0f, -5.0f, 11, 3, 9, 0.0f);
        this.ArmRight04 = new ModelRenderer(this, 54, 49);
        this.ArmRight04.setRotationPoint(2.0f, 8.0f, -3.0f);
        this.ArmRight04.addBox(-4.0f, 0.0f, -4.0f, 8, 4, 8, 0.0f);
        this.setRotateAngle(this.ArmRight04, 0.0f, 0.08726646f, 0.0f);
        this.ArmRight03 = new ModelRenderer(this, 100, 14);
        this.ArmRight03.setRotationPoint(-2.0f, 10.0f, 3.0f);
        this.ArmRight03.addBox(-1.5f, 0.0f, -6.5f, 7, 8, 7, 0.0f);
        this.EquipR02 = new ModelRenderer(this, 0, 0);
        this.EquipR02.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.EquipR02.addBox(-2.5f, 0.0f, -10.0f, 3, 2, 20, 0.0f);
        this.LegRight01 = new ModelRenderer(this, 0, 84);
        this.LegRight01.setRotationPoint(-4.8f, 5.5f, -2.6f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.ShoesR02 = new ModelRenderer(this, 98, 0);
        this.ShoesR02.setRotationPoint(0.0f, 3.0f, -0.7f);
        this.ShoesR02.addBox(-3.5f, 0.0f, -4.0f, 7, 4, 8, 0.0f);
        this.BodyMain.addChild(this.Cloth01);
        this.Head.addChild(this.Hair);
        this.Head.addChild(this.HeadS05);
        this.ArmLeft02.addChild(this.ArmLeft03);
        this.LegLeft01.addChild(this.LegLeft02);
        this.EquipL03.addChild(this.EquipL04);
        this.Hair.addChild(this.Ahoke);
        this.HairR01.addChild(this.HairR02);
        this.Skirt01.addChild(this.Skirt02);
        this.EquipL01.addChild(this.EquipL02);
        this.BodyMain.addChild(this.ArmRight01);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.HeadS01.addChild(this.HeadS03);
        this.ShoesL03.addChild(this.ShoesL04);
        this.HeadS01.addChild(this.HeadS02);
        this.ShoesR03.addChild(this.ShoesR04);
        this.ShoesL01.addChild(this.ShoesL02);
        this.ArmLeft04.addChild(this.ArmLeft05);
        this.ArmLeft03.addChild(this.ArmLeft04);
        this.Hair.addChild(this.HairR01);
        this.Neck.addChild(this.Head);
        this.Hair.addChild(this.HairL01);
        this.HairL01.addChild(this.HairL02);
        this.Hair01.addChild(this.Hair02);
        this.ShoesR02.addChild(this.ShoesR03);
        this.EquipL02.addChild(this.EquipL03);
        this.BodyMain.addChild(this.ArmLeft01);
        this.Butt.addChild(this.LegLeft01);
        this.EquipL04.addChild(this.EquipL05);
        this.Butt.addChild(this.Skirt01);
        this.EquipR04.addChild(this.EquipR05);
        this.Head.addChild(this.HairMain);
        this.Head.addChild(this.HeadS01);
        this.LegRight01.addChild(this.LegRight02);
        this.HairMain.addChild(this.Hair01);
        this.EquipR02.addChild(this.EquipR03);
        this.BodyMain.addChild(this.Butt);
        this.EquipR03.addChild(this.EquipR04);
        this.ArmRight01.addChild(this.ArmRight02);
        this.ArmRight04.addChild(this.ArmRight05);
        this.Hair02.addChild(this.Hair03);
        this.BodyMain.addChild(this.BoobL);
        this.ShoesL02.addChild(this.ShoesL03);
        this.BodyMain.addChild(this.BoobR);
        this.LegRight02.addChild(this.ShoesR01);
        this.LegLeft02.addChild(this.ShoesL01);
        this.Head.addChild(this.HeadS04);
        this.BodyMain.addChild(this.Neck);
        this.ArmRight03.addChild(this.ArmRight04);
        this.ArmRight02.addChild(this.ArmRight03);
        this.EquipR01.addChild(this.EquipR02);
        this.Butt.addChild(this.LegRight01);
        this.ShoesR01.addChild(this.ShoesR02);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain, -0.10471976f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(0.0f, -10.3f, -0.2f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.GlowBodyMain2 = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain2.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain2, -0.10471976f, 0.0f, 0.0f);
        this.GlowBodyMain2.addChild(this.EquipBase);
        this.EquipBase.addChild(this.EquipL01);
        this.EquipBase.addChild(this.EquipR01);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02, this.ArmRight03};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02, this.ArmLeft03};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        float light = 80.0f + MathHelper.cos(f2 * 0.075f) * 80.0f;
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, light, light);
        this.GlowBodyMain2.render(f5);
        GlStateManager.enableLighting();
        int j = entity.getBrightnessForRender();
        int k = j % 65536;
        int l = j / 65536;
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, k, l);
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
        this.EquipBase.isHidden = !EmotionHelper.checkModelState(1, ent.getStateEmotion(0));
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowBodyMain2.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain2.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain2.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowNeck.rotateAngleX = this.Neck.rotateAngleX;
        this.GlowNeck.rotateAngleY = this.Neck.rotateAngleY;
        this.GlowNeck.rotateAngleZ = this.Neck.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.48f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = 0.0f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.BoobL.rotateAngleX = -0.7f;
        this.BoobR.rotateAngleX = -0.7f;
        this.Ahoke.rotateAngleY = 0.7f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.Hair01.rotateAngleX = 0.21f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -0.09f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -0.14f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleZ = 0.087f;
        this.HairL02.rotateAngleZ = 0.087f;
        this.HairR01.rotateAngleZ = 0.087f;
        this.HairR02.rotateAngleZ = -0.052f;
        this.HairL01.rotateAngleX = -0.65f;
        this.HairL02.rotateAngleX = 0.17f;
        this.HairR01.rotateAngleX = -0.65f;
        this.HairR02.rotateAngleX = 0.17f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft05.rotateAngleZ = 0.2618f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight03.rotateAngleX = 0.0f;
        this.ArmRight03.rotateAngleZ = 0.0f;
        this.LegLeft01.rotateAngleX = -1.0472f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.ShoesL04.rotateAngleX = -0.1f;
        this.LegRight01.rotateAngleX = -1.0472f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.EquipBase.rotateAngleX = 0.0f;
        this.EquipL01.offsetX = 0.0f;
        this.EquipL01.offsetY = 0.0f;
        this.EquipL01.offsetZ = 0.0f;
        this.EquipL01.rotateAngleX = 0.2618f;
        this.EquipL01.rotateAngleY = 0.1745f;
        this.EquipL01.rotateAngleZ = 0.0f;
        this.EquipL05.rotateAngleZ = 0.0f;
        this.EquipR01.offsetX = 0.0f;
        this.EquipR01.offsetY = 0.0f;
        this.EquipR01.offsetZ = 0.0f;
        this.EquipR01.rotateAngleX = 0.2618f;
        this.EquipR01.rotateAngleY = -0.1745f;
        this.EquipR01.rotateAngleZ = 0.0f;
        this.Head.rotateAngleX = 0.55f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.Hair01.rotateAngleX = -0.1f;
        this.Hair02.rotateAngleX = -0.2f;
        this.Neck.rotateAngleX = 0.3f;
        this.Butt.rotateAngleX = -0.14f;
        this.Skirt01.rotateAngleX = -0.1745f;
        this.Skirt02.rotateAngleX = -0.2618f;
        this.ArmLeft01.rotateAngleX = 0.4f;
        this.ArmLeft01.rotateAngleZ = -0.2618f;
        this.ArmLeft03.rotateAngleX = 0.0f;
        this.ArmLeft03.rotateAngleZ = 0.0f;
        this.ArmRight01.rotateAngleX = 0.4f;
        this.ArmRight01.rotateAngleZ = 0.2618f;
        this.LegLeft01.rotateAngleZ = -0.14f;
        this.LegLeft02.rotateAngleX = 1.2217f;
        this.LegLeft02.rotateAngleY = 1.2217f;
        this.LegLeft02.rotateAngleZ = -1.0472f;
        this.LegLeft02.offsetX = 0.175f;
        this.LegLeft02.offsetY = -0.02f;
        this.LegLeft02.offsetZ = 0.1635f;
        this.LegRight01.rotateAngleZ = 0.14f;
        this.LegRight02.rotateAngleX = 1.2217f;
        this.LegRight02.rotateAngleY = -1.2217f;
        this.LegRight02.rotateAngleZ = 1.0472f;
        this.LegRight02.offsetX = -0.175f;
        this.LegRight02.offsetY = -0.05f;
        this.LegRight02.offsetZ = 0.1635f;
        this.EquipL01.offsetY = 0.6f;
        this.EquipR01.offsetY = 0.6f;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float f6;
        int nodf2;
        float angleX = MathHelper.cos(f2 * 0.08f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.3f + f * 0.5f);
        float angleX2 = MathHelper.cos(f2 * 0.08f + 0.6f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1 * 0.7f;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1 * 0.7f;
        float addk1;
        float addk2;
        float headX;
        float headZ;
        if (ent.getShipDepth(0) > 0.0 || ent.getShipDepth(1) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 * 0.6f - 0.35f;
        addk2 = angleAdd2 * 0.6f - 0.07f;
        this.Head.rotateAngleX = f4 * 0.014f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.Head.rotateAngleZ = 0.0f;
        headX = this.Head.rotateAngleX * -0.5f;
        this.BoobL.rotateAngleX = angleX * 0.08f - 0.7f;
        this.BoobR.rotateAngleX = angleX * 0.08f - 0.7f;
        this.Ahoke.rotateAngleY = angleX * 0.15f + 0.7f;
        this.Neck.rotateAngleX = 0.1f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.Butt.rotateAngleX = 0.3142f;
        this.Skirt01.rotateAngleX = -0.14f;
        this.Skirt02.rotateAngleX = -0.087f;
        this.Hair01.rotateAngleX = angleX * 0.03f + 0.21f + headX;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -angleX1 * 0.04f - 0.09f + headX;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -angleX2 * 0.07f - 0.14f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = 0.2618f;
        this.ArmLeft01.rotateAngleY = 0.0f;
        this.ArmLeft01.rotateAngleZ = -0.7f;
        this.ArmLeft03.rotateAngleX = -0.14f;
        this.ArmLeft03.rotateAngleZ = 1.4835f;
        this.ArmLeft05.rotateAngleZ = 0.2618f;
        this.ArmRight01.rotateAngleX = angleAdd1 * 0.375f + 0.2618f;
        this.ArmRight01.rotateAngleY = 0.0f;
        this.ArmRight01.rotateAngleZ = 0.2618f;
        this.ArmRight03.rotateAngleX = 0.0f;
        this.ArmRight03.rotateAngleZ = 0.0f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.14f;
        this.LegLeft02.offsetX = 0.0f;
        this.LegLeft02.offsetY = 0.0f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegLeft02.rotateAngleX = 0.0f;
        this.LegLeft02.rotateAngleY = 0.0f;
        this.LegLeft02.rotateAngleZ = 0.0f;
        this.ShoesL04.rotateAngleX = -0.1f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.14f;
        this.LegRight02.offsetX = 0.0f;
        this.LegRight02.offsetY = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        this.LegRight02.rotateAngleX = 0.0f;
        this.LegRight02.rotateAngleY = 0.0f;
        this.LegRight02.rotateAngleZ = 0.0f;
        this.EquipBase.rotateAngleX = 0.0f;
        this.EquipL01.offsetX = 0.0f;
        this.EquipL01.offsetY = angleX * 0.125f;
        this.EquipL01.offsetZ = 0.0f;
        this.EquipL01.rotateAngleX = 0.2618f;
        this.EquipL01.rotateAngleY = 0.1745f;
        this.EquipL01.rotateAngleZ = 0.0f;
        this.EquipL05.rotateAngleZ = 0.0f;
        this.EquipR01.offsetX = 0.0f;
        this.EquipR01.offsetY = -angleX * 0.125f;
        this.EquipR01.offsetZ = 0.0f;
        this.EquipR01.rotateAngleX = 0.2618f;
        this.EquipR01.rotateAngleY = -0.1745f;
        this.EquipR01.rotateAngleZ = 0.0f;
        if (ent.getIsSprinting() || f1 > 0.9f) {
            this.Hair01.rotateAngleX += 0.09f;
            this.Hair02.rotateAngleX += 0.43f;
            this.Hair03.rotateAngleX += 0.49f;
            this.BoobL.rotateAngleX = angleAdd2 * 0.1f - 0.83f;
            this.BoobR.rotateAngleX = angleAdd1 * 0.1f - 0.83f;
            this.ArmLeft01.rotateAngleX = angleAdd2 * 0.6f + 0.2618f;
            this.ArmLeft01.rotateAngleY = 0.0f;
            this.ArmLeft01.rotateAngleZ = -0.3f;
            this.ArmLeft03.rotateAngleX = 0.0f;
            this.ArmLeft03.rotateAngleZ = 0.0f;
            this.ArmLeft05.rotateAngleZ = 0.0f;
            this.ArmRight01.rotateAngleX = angleAdd1 * 0.6f + 0.2618f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = 0.3f;
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.05f, 0.0f);
            this.Head.rotateAngleX -= 0.6283f;
            this.BodyMain.rotateAngleX = 0.8727f;
            this.Butt.rotateAngleX = -0.6283f;
            this.Skirt01.rotateAngleX = -0.1745f;
            this.Skirt02.rotateAngleX = -0.2618f;
            this.ArmLeft01.rotateAngleX = 0.2618f;
            this.ArmLeft01.rotateAngleY = 0.0f;
            this.ArmLeft01.rotateAngleZ = 0.2618f;
            this.ArmLeft03.rotateAngleX = 0.0f;
            this.ArmLeft03.rotateAngleZ = 0.0f;
            this.ArmLeft05.rotateAngleZ = 0.0f;
            this.ArmRight01.rotateAngleX = 0.2618f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = -0.2618f;
            this.ArmRight05.rotateAngleZ = 0.0f;
            this.Hair01.rotateAngleX += 0.37f;
            this.Hair02.rotateAngleX += 0.23f;
            this.Hair03.rotateAngleX -= 0.1f;
        }
        if (ent.getIsSitting() && !ent.getIsRiding()) {
            if (ent.getStateEmotion(1) == 4) {
                this.setFace(1);
                GlStateManager.translate(0.0f, 0.48f, 0.0f);
                nodf2 = (int)f2 % 60;
                this.Head.rotateAngleX = 0.3f;
                if (nodf2 < 30) {
                    if (nodf2 < 6) {
                        this.Head.rotateAngleX = nodf2 * 0.02f + 0.3f;
                    } else if (nodf2 < 11) {
                        this.Head.rotateAngleX = (nodf2 - 5) * 0.03f + 0.4f;
                    } else if (nodf2 < 14) {
                        this.Head.rotateAngleX = (nodf2 - 10) * -0.09f + 0.55f;
                    }
                }
                this.Head.rotateAngleY = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                headX = this.Head.rotateAngleX * -0.5f;
                this.Hair01.rotateAngleX = angleX * 0.012f + 0.21f + headX;
                this.Hair02.rotateAngleX = angleX * 0.015f - 0.09f + headX;
                this.Neck.rotateAngleX = 0.3f;
                this.Butt.rotateAngleX = -0.14f;
                this.Skirt01.rotateAngleX = -0.1745f;
                this.Skirt02.rotateAngleX = -0.2618f;
                this.ArmLeft01.rotateAngleX = 0.4f;
                this.ArmLeft01.rotateAngleZ = -0.2618f;
                this.ArmLeft03.rotateAngleX = 0.0f;
                this.ArmLeft03.rotateAngleZ = 0.0f;
                this.ArmRight01.rotateAngleX = 0.4f;
                this.ArmRight01.rotateAngleZ = 0.2618f;
                addk1 = -1.0472f;
                addk2 = -1.0472f;
                this.LegLeft01.rotateAngleZ = -0.14f;
                this.LegLeft02.rotateAngleX = 1.2217f;
                this.LegLeft02.rotateAngleY = 1.2217f;
                this.LegLeft02.rotateAngleZ = -1.0472f;
                this.LegLeft02.offsetX = 0.175f;
                this.LegLeft02.offsetY = -0.02f;
                this.LegLeft02.offsetZ = 0.1635f;
                this.LegRight01.rotateAngleZ = 0.14f;
                this.LegRight02.rotateAngleX = 1.2217f;
                this.LegRight02.rotateAngleY = -1.2217f;
                this.LegRight02.rotateAngleZ = 1.0472f;
                this.LegRight02.offsetX = -0.175f;
                this.LegRight02.offsetY = -0.05f;
                this.LegRight02.offsetZ = 0.1635f;
                this.EquipL01.offsetY = 0.6f;
                this.EquipR01.offsetY = 0.6f;
            } else {
                GlStateManager.translate(0.0f, 0.4f, 0.0f);
                this.Neck.rotateAngleX = 0.35f;
                this.BodyMain.rotateAngleX = -0.6283f;
                this.Butt.rotateAngleX = -0.6283f;
                this.Skirt01.rotateAngleX = -0.1745f;
                this.Skirt02.rotateAngleX = -0.2618f;
                this.ArmRight01.rotateAngleX = angleX * 0.125f + 0.5236f;
                addk1 = -0.8727f;
                addk2 = -0.35f;
                this.LegLeft01.rotateAngleZ = 0.4363f;
                this.LegLeft02.rotateAngleX = 0.7854f;
                this.LegRight01.rotateAngleZ = -0.35f;
                this.LegRight02.rotateAngleX = 0.8727f;
                this.ShoesL04.rotateAngleX = angleX * 0.25f - 0.1f;
                this.EquipL01.offsetX = -1.9f;
                this.EquipL01.offsetY = 0.6f;
                this.EquipL01.offsetZ = 0.4f;
                this.EquipL01.rotateAngleX = 0.0f;
                this.EquipL01.rotateAngleY = 1.57f;
                this.EquipL05.rotateAngleZ = -1.0f;
                this.EquipR01.offsetX = 1.9f;
                this.EquipR01.offsetY = -1.0f;
                this.EquipR01.offsetZ = -0.4f;
                this.EquipR01.rotateAngleX = -1.5708f;
                this.EquipR01.rotateAngleY = 0.6f;
                this.EquipR01.rotateAngleZ = -1.5708f;
            }
        }
        if (ent.getIsRiding()) {
            if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
                this.EquipBase.isHidden = false;
                if (ent.getIsSitting()) {
                    if (ent.getStateEmotion(1) == 4) {
                        this.setFace(1);
                        GlStateManager.translate(0.0f, 0.48f, 0.0f);
                        nodf2 = (int)f2 % 60;
                        this.Head.rotateAngleX = 0.3f;
                        if (nodf2 < 30) {
                            if (nodf2 < 6) {
                                this.Head.rotateAngleX = nodf2 * 0.02f + 0.3f;
                            } else if (nodf2 < 11) {
                                this.Head.rotateAngleX = (nodf2 - 5) * 0.03f + 0.4f;
                            } else if (nodf2 < 14) {
                                this.Head.rotateAngleX = (nodf2 - 10) * -0.09f + 0.55f;
                            }
                        }
                        this.Head.rotateAngleY = 0.0f;
                        this.Head.rotateAngleZ = 0.0f;
                        headX = this.Head.rotateAngleX * -0.5f;
                        this.Hair01.rotateAngleX = angleX * 0.012f + 0.21f + headX;
                        this.Hair02.rotateAngleX = angleX * 0.015f - 0.09f + headX;
                        this.Neck.rotateAngleX = 0.3f;
                        this.Butt.rotateAngleX = -0.14f;
                        this.Skirt01.rotateAngleX = -0.1745f;
                        this.Skirt02.rotateAngleX = -0.2618f;
                        this.ArmLeft01.rotateAngleX = 0.4f;
                        this.ArmLeft01.rotateAngleZ = -0.2618f;
                        this.ArmLeft03.rotateAngleX = 0.0f;
                        this.ArmLeft03.rotateAngleZ = 0.0f;
                        this.ArmRight01.rotateAngleX = 0.4f;
                        this.ArmRight01.rotateAngleZ = 0.2618f;
                        addk1 = -1.0472f;
                        addk2 = -1.0472f;
                        this.LegLeft01.rotateAngleZ = -0.14f;
                        this.LegLeft02.rotateAngleX = 1.2217f;
                        this.LegLeft02.rotateAngleY = 1.2217f;
                        this.LegLeft02.rotateAngleZ = -1.0472f;
                        this.LegLeft02.offsetX = 0.175f;
                        this.LegLeft02.offsetY = -0.02f;
                        this.LegLeft02.offsetZ = 0.1635f;
                        this.LegRight01.rotateAngleZ = 0.14f;
                        this.LegRight02.rotateAngleX = 1.2217f;
                        this.LegRight02.rotateAngleY = -1.2217f;
                        this.LegRight02.rotateAngleZ = 1.0472f;
                        this.LegRight02.offsetX = -0.175f;
                        this.LegRight02.offsetY = -0.05f;
                        this.LegRight02.offsetZ = 0.1635f;
                        this.EquipBase.rotateAngleX = -0.4f;
                        this.EquipL01.offsetX = -0.3f;
                        this.EquipL01.offsetY = 0.6f;
                        this.EquipL01.offsetZ = 0.6f;
                        this.EquipL01.rotateAngleY = 1.4f;
                        this.EquipR01.offsetX = 0.3f;
                        this.EquipR01.offsetY = 0.6f;
                        this.EquipR01.offsetZ = 0.6f;
                        this.EquipR01.rotateAngleY = -1.4f;
                    } else {
                        GlStateManager.translate(0.0f, 0.64f, -0.11f);
                        this.Neck.rotateAngleX = 0.35f;
                        this.BodyMain.rotateAngleX = -0.6283f;
                        this.Butt.rotateAngleX = -0.6283f;
                        this.Skirt01.rotateAngleX = -0.1745f;
                        this.Skirt02.rotateAngleX = -0.2618f;
                        this.ArmRight01.rotateAngleX = angleX * 0.125f + 0.5236f;
                        this.ArmRight01.rotateAngleZ = 0.45f;
                        this.ArmRight03.rotateAngleX = -0.5f;
                        addk1 = -0.8727f;
                        addk2 = -0.35f;
                        this.LegLeft01.rotateAngleZ = 0.4363f;
                        this.LegLeft02.rotateAngleX = 0.7854f;
                        this.LegRight01.rotateAngleZ = -0.35f;
                        this.LegRight02.rotateAngleX = 0.8727f;
                        this.ShoesL04.rotateAngleX = angleX * 0.25f - 0.1f;
                        this.EquipBase.rotateAngleX = 0.2f;
                        this.EquipL01.offsetX = -0.25f;
                        this.EquipL01.offsetY = 0.1f;
                        this.EquipL01.rotateAngleY = 1.4f;
                        this.EquipR01.offsetX = 0.25f;
                        this.EquipR01.offsetY = 0.1f;
                        this.EquipR01.rotateAngleY = -1.4f;
                    }
                } else {
                    GlStateManager.translate(0.0f, 0.64f, -0.11f);
                    this.Neck.rotateAngleX = 0.35f;
                    this.BodyMain.rotateAngleX = -0.6283f;
                    this.Butt.rotateAngleX = -0.6283f;
                    this.Skirt01.rotateAngleX = -0.1745f;
                    this.Skirt02.rotateAngleX = -0.2618f;
                    this.ArmRight01.rotateAngleX = angleX * 0.125f + 0.5236f;
                    this.ArmRight01.rotateAngleZ = 0.45f;
                    this.ArmRight03.rotateAngleX = -0.5f;
                    addk1 = -0.8727f;
                    addk2 = -0.35f;
                    this.LegLeft01.rotateAngleZ = 0.4363f;
                    this.LegLeft02.rotateAngleX = 0.7854f;
                    this.LegRight01.rotateAngleZ = -0.35f;
                    this.LegRight02.rotateAngleX = 0.8727f;
                    this.ShoesL04.rotateAngleX = angleX * 0.25f - 0.1f;
                    this.EquipBase.rotateAngleX = -0.9f;
                    this.EquipL01.offsetX = -0.25f;
                    this.EquipL01.offsetY = 0.1f;
                    this.EquipL01.offsetZ = 0.45f;
                    this.EquipL01.rotateAngleY = 1.4f;
                    this.EquipR01.offsetX = 0.25f;
                    this.EquipR01.offsetY = 0.1f;
                    this.EquipR01.offsetZ = 0.45f;
                    this.EquipR01.rotateAngleY = -1.4f;
                }
            } else if (ent.getStateEmotion(1) == 4) {
                this.setFace(1);
                GlStateManager.translate(0.0f, 0.48f, 0.0f);
                nodf2 = (int)f2 % 60;
                this.Head.rotateAngleX = 0.2f;
                if (nodf2 < 30) {
                    if (nodf2 < 6) {
                        this.Head.rotateAngleX = nodf2 * 0.02f + 0.2f;
                    } else if (nodf2 < 11) {
                        this.Head.rotateAngleX = (nodf2 - 5) * 0.03f + 0.3f;
                    } else if (nodf2 < 14) {
                        this.Head.rotateAngleX = (nodf2 - 10) * -0.09f + 0.45f;
                    }
                }
                this.Head.rotateAngleY = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                headX = this.Head.rotateAngleX * -0.5f;
                this.Hair01.rotateAngleX = angleX * 0.012f + 0.21f + headX;
                this.Hair02.rotateAngleX = angleX * 0.015f - 0.09f + headX;
                this.Neck.rotateAngleX = 0.3f;
                this.Butt.rotateAngleX = -0.14f;
                this.Skirt01.rotateAngleX = -0.1745f;
                this.Skirt02.rotateAngleX = -0.2618f;
                this.ArmLeft01.rotateAngleX = 0.4f;
                this.ArmLeft01.rotateAngleZ = -0.2618f;
                this.ArmLeft03.rotateAngleX = 0.0f;
                this.ArmLeft03.rotateAngleZ = 0.0f;
                this.ArmRight01.rotateAngleX = 0.4f;
                this.ArmRight01.rotateAngleZ = 0.2618f;
                addk1 = -1.0472f;
                addk2 = -1.0472f;
                this.LegLeft01.rotateAngleZ = -0.14f;
                this.LegLeft02.rotateAngleX = 1.2217f;
                this.LegLeft02.rotateAngleY = 1.2217f;
                this.LegLeft02.rotateAngleZ = -1.0472f;
                this.LegLeft02.offsetX = 0.175f;
                this.LegLeft02.offsetY = -0.02f;
                this.LegLeft02.offsetZ = 0.1635f;
                this.LegRight01.rotateAngleZ = 0.14f;
                this.LegRight02.rotateAngleX = 1.2217f;
                this.LegRight02.rotateAngleY = -1.2217f;
                this.LegRight02.rotateAngleZ = 1.0472f;
                this.LegRight02.offsetX = -0.175f;
                this.LegRight02.offsetY = -0.05f;
                this.LegRight02.offsetZ = 0.1635f;
                this.EquipL01.offsetY = 0.6f;
                this.EquipR01.offsetY = 0.6f;
            } else {
                GlStateManager.translate(0.0f, 0.39f, 0.0f);
                this.Neck.rotateAngleX = 0.35f;
                this.BodyMain.rotateAngleX = -0.6283f;
                this.Butt.rotateAngleX = -0.6283f;
                this.Skirt01.rotateAngleX = -0.1745f;
                this.Skirt02.rotateAngleX = -0.2618f;
                this.ArmRight01.rotateAngleX = angleX * 0.125f + 0.5236f;
                addk1 = -0.8727f;
                addk2 = -0.35f;
                this.LegLeft01.rotateAngleZ = 0.4363f;
                this.LegLeft02.rotateAngleX = 0.7854f;
                this.LegRight01.rotateAngleZ = -0.35f;
                this.LegRight02.rotateAngleX = 0.8727f;
                this.ShoesL04.rotateAngleX = angleX * 0.25f - 0.1f;
                this.EquipL01.offsetX = -1.9f;
                this.EquipL01.offsetY = 0.6f;
                this.EquipL01.offsetZ = 0.4f;
                this.EquipL01.rotateAngleX = 0.0f;
                this.EquipL01.rotateAngleY = 1.57f;
                this.EquipL05.rotateAngleZ = -1.0f;
                this.EquipR01.offsetX = 1.9f;
                this.EquipR01.offsetY = -1.0f;
                this.EquipR01.offsetZ = -0.4f;
                this.EquipR01.rotateAngleX = -1.5708f;
                this.EquipR01.rotateAngleY = 0.6f;
                this.EquipR01.rotateAngleZ = -1.5708f;
            }
        }
        if (ent.getAttackTick() > 0) {
            if (ent.getIsRiding()) {
                this.ArmRight01.rotateAngleX = -1.1f;
                this.ArmRight03.rotateAngleX = 0.0f;
                this.EquipBase.isHidden = false;
                this.EquipBase.rotateAngleX = -1.2f + f4 * ((float)Math.PI / 180);
                this.EquipL01.rotateAngleX = -0.1f;
                this.EquipR01.rotateAngleX = 0.1f;
            } else {
                this.ArmRight01.rotateAngleX = -1.5f;
                this.EquipBase.isHidden = false;
                this.EquipBase.rotateAngleX = -1.6f + f4 * ((float)Math.PI / 180);
                this.EquipL01.offsetY = 0.0f;
                this.EquipR01.offsetY = 0.0f;
            }
        }
        if ((f6 = ent.getSwingTime(f2 - (int)f2)) != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX = -0.4f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = -0.2f;
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 0.2f;
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
        }
        this.Hair01.rotateAngleZ = headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair02.rotateAngleZ = headZ;
        this.HairL01.rotateAngleZ = headZ - 0.087f;
        this.HairL02.rotateAngleZ = headZ + 0.087f;
        this.HairR01.rotateAngleZ = headZ + 0.087f;
        this.HairR02.rotateAngleZ = headZ - 0.052f;
        headX = this.Head.rotateAngleX * -0.5f;
        this.HairL01.rotateAngleX = angleX * 0.02f + headX - 0.14f;
        this.HairL02.rotateAngleX = angleX * 0.02f + headX + 0.17f;
        this.HairR01.rotateAngleX = angleX * 0.02f + headX - 0.14f;
        this.HairR02.rotateAngleX = angleX * 0.02f + headX + 0.17f;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }
}
