package com.lulan.shincolle.client.model;

import com.lulan.shincolle.entity.BasicEntityMount;
import com.lulan.shincolle.entity.IShipEmotion;
import com.lulan.shincolle.utility.EmotionHelper;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelHarbourHime
extends ShipModelBaseAdv {
    private final ModelRenderer BodyMain;
    private final ModelRenderer Neck;
    private final ModelRenderer BoobR;
    private final ModelRenderer BoobL;
    private final ModelRenderer ArmLeft01;
    private final ModelRenderer Butt;
    private final ModelRenderer ArmRight01;
    private final ModelRenderer Head;
    private final ModelRenderer Hair;
    private final ModelRenderer HairMain;
    private final ModelRenderer HeadH;
    private final ModelRenderer Ahoke;
    private final ModelRenderer HairL01;
    private final ModelRenderer HairR01;
    private final ModelRenderer HairL02;
    private final ModelRenderer HairR02;
    private final ModelRenderer Hair01;
    private final ModelRenderer Hair02;
    private final ModelRenderer Hair03;
    private final ModelRenderer HeadH2;
    private final ModelRenderer HeadH3;
    private final ModelRenderer ArmLeft02;
    private final ModelRenderer ArmLeft03;
    private final ModelRenderer ArmLeft04;
    private final ModelRenderer ArmLeft05;
    private final ModelRenderer ArmLeft06;
    private final ModelRenderer ArmLeft07;
    private final ModelRenderer LegRight01;
    private final ModelRenderer LegLeft01;
    private final ModelRenderer Skirt;
    private final ModelRenderer LegRight02;
    private final ModelRenderer ShoesR;
    private final ModelRenderer LegLeft02;
    private final ModelRenderer ShoesL;
    private final ModelRenderer ArmRight02;
    private final ModelRenderer ArmRight03;
    private final ModelRenderer ArmRight04;
    private final ModelRenderer ArmRight05;
    private final ModelRenderer ArmRight06;
    private final ModelRenderer ArmRight07;
    private final ModelRenderer GlowBodyMain;
    private final ModelRenderer GlowNeck;
    private final ModelRenderer GlowHead;

    public ModelHarbourHime() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.scale = 0.53f;
        this.offsetY = 1.35f;
        this.offsetItem = new float[]{0.0f, 0.74f, -0.07f};
        this.offsetBlock = new float[]{0.0f, 0.74f, -0.07f};
        this.setDefaultFaceModel();
        this.ArmRight05 = new ModelRenderer(this, 46, 0);
        this.ArmRight05.mirror = true;
        this.ArmRight05.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.ArmRight05.addBox(-5.5f, -0.2f, -6.5f, 11, 4, 13, 0.0f);
        this.HairL02 = new ModelRenderer(this, 24, 84);
        this.HairL02.setRotationPoint(-0.1f, 10.0f, 0.1f);
        this.HairL02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 5, 0.0f);
        this.setRotateAngle(this.HairL02, 0.1745f, 0.0f, 0.08726646f);
        this.Hair02 = new ModelRenderer(this, 0, 58);
        this.Hair02.setRotationPoint(0.0f, 13.5f, 5.5f);
        this.Hair02.addBox(-8.0f, 0.0f, -5.0f, 16, 16, 8, 0.0f);
        this.setRotateAngle(this.Hair02, -0.08726646f, 0.0f, 0.0f);
        this.LegRight01 = new ModelRenderer(this, 0, 84);
        this.LegRight01.setRotationPoint(-5.2f, 9.5f, -2.6f);
        this.LegRight01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegRight01, -0.20943952f, 0.0f, -0.05235988f);
        this.ArmLeft04 = new ModelRenderer(this, 50, 60);
        this.ArmLeft04.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.ArmLeft04.addBox(-5.0f, 0.0f, -5.5f, 10, 6, 11, 0.0f);
        this.ArmLeft01 = new ModelRenderer(this, 2, 85);
        this.ArmLeft01.mirror = true;
        this.ArmLeft01.setRotationPoint(7.8f, -9.3f, -0.7f);
        this.ArmLeft01.addBox(-2.0f, -1.0f, -2.5f, 5, 8, 5, 0.0f);
        this.setRotateAngle(this.ArmLeft01, -0.2617994f, 0.6981317f, 0.0f);
        this.ArmRight03 = new ModelRenderer(this, 46, 46);
        this.ArmRight03.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.ArmRight03.addBox(-4.0f, 0.0f, -4.5f, 8, 5, 9, 0.0f);
        this.setRotateAngle(this.ArmRight03, 0.0f, -0.34906584f, 0.0f);
        this.ArmLeft02 = new ModelRenderer(this, 72, 38);
        this.ArmLeft02.mirror = true;
        this.ArmLeft02.setRotationPoint(0.5f, 4.0f, 0.0f);
        this.ArmLeft02.addBox(-3.0f, 0.0f, -3.5f, 6, 10, 7, 0.0f);
        this.HeadH = new ModelRenderer(this, 33, 101);
        this.HeadH.mirror = true;
        this.HeadH.setRotationPoint(0.0f, -10.0f, -6.5f);
        this.HeadH.addBox(-2.0f, -2.0f, -3.0f, 4, 4, 4, 0.0f);
        this.setRotateAngle(this.HeadH, -0.31415927f, 0.0f, 0.0f);
        this.ArmRight01 = new ModelRenderer(this, 2, 85);
        this.ArmRight01.mirror = true;
        this.ArmRight01.setRotationPoint(-7.8f, -9.3f, -0.7f);
        this.ArmRight01.addBox(-3.0f, -1.0f, -2.5f, 5, 8, 5, 0.0f);
        this.setRotateAngle(this.ArmRight01, -0.2617994f, -0.6981317f, 0.0f);
        this.Hair = new ModelRenderer(this, 45, 77);
        this.Hair.setRotationPoint(0.0f, -7.5f, 0.0f);
        this.Hair.addBox(-8.0f, -8.0f, -7.2f, 16, 16, 8, 0.0f);
        this.LegLeft01 = new ModelRenderer(this, 0, 84);
        this.LegLeft01.mirror = true;
        this.LegLeft01.setRotationPoint(5.2f, 9.5f, -2.6f);
        this.LegLeft01.addBox(-3.0f, 0.0f, -3.0f, 6, 14, 6, 0.0f);
        this.setRotateAngle(this.LegLeft01, -0.20943952f, 0.0f, 0.05235988f);
        this.HeadH3 = new ModelRenderer(this, 45, 105);
        this.HeadH3.setRotationPoint(0.0f, 0.0f, -3.8f);
        this.HeadH3.addBox(-1.0f, -1.2f, -3.0f, 2, 2, 4, 0.0f);
        this.setRotateAngle(this.HeadH3, -0.13962634f, 0.0f, 0.0f);
        this.Skirt = new ModelRenderer(this, 0, 19);
        this.Skirt.setRotationPoint(0.0f, 6.9f, -6.0f);
        this.Skirt.addBox(-8.5f, 0.0f, 0.0f, 17, 6, 9, 0.0f);
        this.setRotateAngle(this.Skirt, -0.13962634f, 0.0f, 0.0f);
        this.Hair01 = new ModelRenderer(this, 0, 57);
        this.Hair01.setRotationPoint(0.0f, 9.0f, 1.0f);
        this.Hair01.addBox(-7.5f, 0.0f, 0.0f, 15, 17, 9, 0.0f);
        this.setRotateAngle(this.Hair01, 0.20943952f, 0.0f, 0.0f);
        this.BoobR = new ModelRenderer(this, 46, 33);
        this.BoobR.setRotationPoint(-3.9f, -8.1f, -4.0f);
        this.BoobR.addBox(-4.0f, 0.0f, 0.0f, 8, 6, 6, 0.0f);
        this.setRotateAngle(this.BoobR, -0.87266463f, 0.08726646f, -0.08726646f);
        this.Butt = new ModelRenderer(this, 0, 0);
        this.Butt.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Butt.addBox(-7.5f, 4.0f, -5.7f, 15, 8, 8, 0.0f);
        this.setRotateAngle(this.Butt, 0.31415927f, 0.0f, 0.0f);
        this.Head = new ModelRenderer(this, 44, 101);
        this.Head.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.Head.addBox(-7.0f, -14.5f, -6.5f, 14, 14, 13, 0.0f);
        this.ArmRight04 = new ModelRenderer(this, 50, 60);
        this.ArmRight04.mirror = true;
        this.ArmRight04.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.ArmRight04.addBox(-5.0f, 0.0f, -5.5f, 10, 6, 11, 0.0f);
        this.BodyMain = new ModelRenderer(this, 0, 104);
        this.BodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.BodyMain.addBox(-6.5f, -11.0f, -4.0f, 13, 17, 7, 0.0f);
        this.setRotateAngle(this.BodyMain, -0.10471976f, 0.0f, 0.0f);
        this.BoobL = new ModelRenderer(this, 46, 33);
        this.BoobL.mirror = true;
        this.BoobL.setRotationPoint(3.9f, -8.1f, -4.0f);
        this.BoobL.addBox(-4.0f, 0.0f, 0.0f, 8, 6, 6, 0.0f);
        this.setRotateAngle(this.BoobL, -0.87266463f, -0.08726646f, 0.08726646f);
        this.Hair03 = new ModelRenderer(this, 0, 35);
        this.Hair03.setRotationPoint(0.0f, 12.5f, -0.1f);
        this.Hair03.addBox(-8.0f, 0.0f, -4.5f, 16, 15, 7, 0.0f);
        this.setRotateAngle(this.Hair03, -0.13962634f, 0.0f, 0.0f);
        this.HairR02 = new ModelRenderer(this, 24, 84);
        this.HairR02.mirror = true;
        this.HairR02.setRotationPoint(0.1f, 10.0f, 0.1f);
        this.HairR02.addBox(-1.0f, 0.0f, 0.0f, 2, 12, 5, 0.0f);
        this.setRotateAngle(this.HairR02, 0.1745f, 0.0f, -0.05235988f);
        this.LegLeft02 = new ModelRenderer(this, 0, 84);
        this.LegLeft02.mirror = true;
        this.LegLeft02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegLeft02.addBox(-3.0f, 0.0f, 0.0f, 6, 6, 6, 0.0f);
        this.ArmLeft06 = new ModelRenderer(this, 68, 17);
        this.ArmLeft06.setRotationPoint(-2.0f, 1.0f, 0.5f);
        this.ArmLeft06.addBox(0.0f, 0.0f, -4.2f, 5, 9, 9, 0.0f);
        this.setRotateAngle(this.ArmLeft06, 0.08726646f, 0.13962634f, 0.2617994f);
        this.ArmRight06 = new ModelRenderer(this, 68, 17);
        this.ArmRight06.mirror = true;
        this.ArmRight06.setRotationPoint(1.0f, 1.0f, 0.5f);
        this.ArmRight06.addBox(-4.0f, 0.0f, -4.2f, 5, 9, 9, 0.0f);
        this.setRotateAngle(this.ArmRight06, 0.08726646f, -0.13962634f, -0.2617994f);
        this.ShoesL = new ModelRenderer(this, 100, 0);
        this.ShoesL.mirror = true;
        this.ShoesL.setRotationPoint(0.0f, 1.0f, 3.0f);
        this.ShoesL.addBox(-3.5f, 0.0f, -3.5f, 7, 14, 7, 0.0f);
        this.setRotateAngle(this.ShoesL, 0.0f, 0.0f, 0.036477383f);
        this.ArmLeft03 = new ModelRenderer(this, 46, 46);
        this.ArmLeft03.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.ArmLeft03.addBox(-4.0f, 0.0f, -4.5f, 8, 5, 9, 0.0f);
        this.setRotateAngle(this.ArmLeft03, 0.0f, 0.34906584f, 0.0f);
        this.ArmLeft07 = new ModelRenderer(this, 43, 18);
        this.ArmLeft07.setRotationPoint(-1.0f, 0.0f, -2.0f);
        this.ArmLeft07.addBox(0.0f, 0.0f, -3.0f, 4, 6, 4, 0.0f);
        this.setRotateAngle(this.ArmLeft07, -0.2617994f, 0.0f, 0.17453292f);
        this.ArmRight07 = new ModelRenderer(this, 43, 18);
        this.ArmRight07.setRotationPoint(1.0f, 0.0f, -2.0f);
        this.ArmRight07.addBox(-3.0f, 0.0f, -3.0f, 4, 6, 4, 0.0f);
        this.setRotateAngle(this.ArmRight07, -0.2617994f, 0.0f, -0.17453292f);
        this.Neck = new ModelRenderer(this, 88, 26);
        this.Neck.setRotationPoint(0.0f, -10.3f, -0.2f);
        this.Neck.addBox(-5.5f, -2.0f, -5.0f, 11, 3, 9, 0.0f);
        this.setRotateAngle(this.Neck, 0.10471976f, 0.0f, 0.0f);
        this.ArmRight02 = new ModelRenderer(this, 72, 38);
        this.ArmRight02.mirror = true;
        this.ArmRight02.setRotationPoint(-0.5f, 4.0f, 0.0f);
        this.ArmRight02.addBox(-3.0f, 0.0f, -3.5f, 6, 10, 7, 0.0f);
        this.HairL01 = new ModelRenderer(this, 24, 84);
        this.HairL01.setRotationPoint(7.0f, 3.0f, -5.5f);
        this.HairL01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 5, 0.0f);
        this.setRotateAngle(this.HairL01, -0.14f, -0.1745f, -0.0873f);
        this.ShoesR = new ModelRenderer(this, 100, 0);
        this.ShoesR.setRotationPoint(0.0f, 1.0f, 3.0f);
        this.ShoesR.addBox(-3.5f, 0.0f, -3.5f, 7, 14, 7, 0.0f);
        this.LegRight02 = new ModelRenderer(this, 0, 84);
        this.LegRight02.setRotationPoint(0.0f, 14.0f, -3.0f);
        this.LegRight02.addBox(-3.0f, 0.0f, 0.0f, 6, 6, 6, 0.0f);
        this.HeadH2 = new ModelRenderer(this, 84, 64);
        this.HeadH2.setRotationPoint(0.0f, -0.2f, -3.7f);
        this.HeadH2.addBox(-1.5f, -1.5f, -3.0f, 3, 3, 4, 0.0f);
        this.setRotateAngle(this.HeadH2, -0.13962634f, 0.0f, 0.0f);
        this.HairR01 = new ModelRenderer(this, 24, 84);
        this.HairR01.mirror = true;
        this.HairR01.setRotationPoint(-7.0f, 3.0f, -5.5f);
        this.HairR01.addBox(-1.0f, 0.0f, 0.0f, 2, 11, 5, 0.0f);
        this.setRotateAngle(this.HairR01, -0.14f, 0.1745f, 0.0873f);
        this.Ahoke = new ModelRenderer(this, 104, 29);
        this.Ahoke.setRotationPoint(0.0f, -9.0f, -5.5f);
        this.Ahoke.addBox(0.0f, -4.0f, -11.5f, 0, 12, 12, 0.0f);
        this.setRotateAngle(this.Ahoke, -0.17453292f, 0.6981317f, 0.0f);
        this.HairMain = new ModelRenderer(this, 0, 57);
        this.HairMain.setRotationPoint(0.0f, -15.0f, -3.0f);
        this.HairMain.addBox(-7.5f, 0.0f, 0.0f, 15, 12, 10, 0.0f);
        this.ArmLeft05 = new ModelRenderer(this, 46, 0);
        this.ArmLeft05.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.ArmLeft05.addBox(-5.5f, -0.2f, -6.5f, 11, 4, 13, 0.0f);
        this.ArmRight04.addChild(this.ArmRight05);
        this.HairL01.addChild(this.HairL02);
        this.Hair01.addChild(this.Hair02);
        this.Butt.addChild(this.LegRight01);
        this.ArmLeft03.addChild(this.ArmLeft04);
        this.BodyMain.addChild(this.ArmLeft01);
        this.ArmRight02.addChild(this.ArmRight03);
        this.ArmLeft01.addChild(this.ArmLeft02);
        this.BodyMain.addChild(this.ArmRight01);
        this.Head.addChild(this.Hair);
        this.Butt.addChild(this.LegLeft01);
        this.Butt.addChild(this.Skirt);
        this.HairMain.addChild(this.Hair01);
        this.BodyMain.addChild(this.BoobR);
        this.BodyMain.addChild(this.Butt);
        this.Neck.addChild(this.Head);
        this.ArmRight03.addChild(this.ArmRight04);
        this.BodyMain.addChild(this.BoobL);
        this.Hair02.addChild(this.Hair03);
        this.HairR01.addChild(this.HairR02);
        this.LegLeft01.addChild(this.LegLeft02);
        this.ArmLeft05.addChild(this.ArmLeft06);
        this.ArmRight05.addChild(this.ArmRight06);
        this.LegLeft02.addChild(this.ShoesL);
        this.ArmLeft02.addChild(this.ArmLeft03);
        this.ArmLeft06.addChild(this.ArmLeft07);
        this.ArmRight06.addChild(this.ArmRight07);
        this.BodyMain.addChild(this.Neck);
        this.ArmRight01.addChild(this.ArmRight02);
        this.Hair.addChild(this.HairL01);
        this.LegRight02.addChild(this.ShoesR);
        this.LegRight01.addChild(this.LegRight02);
        this.Hair.addChild(this.HairR01);
        this.Hair.addChild(this.Ahoke);
        this.Head.addChild(this.HairMain);
        this.ArmLeft04.addChild(this.ArmLeft05);
        this.GlowBodyMain = new ModelRenderer(this, 0, 0);
        this.GlowBodyMain.setRotationPoint(0.0f, -15.0f, 0.0f);
        this.setRotateAngle(this.GlowBodyMain, -0.10471976f, 0.0f, 0.0f);
        this.GlowNeck = new ModelRenderer(this, 0, 0);
        this.GlowNeck.setRotationPoint(0.0f, -10.3f, -0.2f);
        this.setRotateAngle(this.GlowNeck, 0.10471976f, 0.0f, 0.0f);
        this.GlowHead = new ModelRenderer(this, 0, 0);
        this.GlowHead.setRotationPoint(0.0f, -1.5f, 0.0f);
        this.GlowBodyMain.addChild(this.GlowNeck);
        this.GlowNeck.addChild(this.GlowHead);
        this.GlowHead.addChild(this.Face0);
        this.GlowHead.addChild(this.Face1);
        this.GlowHead.addChild(this.Face2);
        this.GlowHead.addChild(this.Face3);
        this.GlowHead.addChild(this.Face4);
        this.GlowHead.addChild(this.Mouth0);
        this.GlowHead.addChild(this.Mouth1);
        this.GlowHead.addChild(this.Mouth2);
        this.GlowHead.addChild(this.Flush0);
        this.GlowHead.addChild(this.Flush1);
        this.GlowHead.addChild(this.HeadH);
        this.HeadH.addChild(this.HeadH2);
        this.HeadH2.addChild(this.HeadH3);
        this.armMain = new ModelRenderer[]{this.BodyMain, this.ArmRight01, this.ArmRight02, this.ArmRight03, this.ArmRight04, this.ArmRight05, this.ArmRight06};
        this.armOff = new ModelRenderer[]{this.BodyMain, this.ArmLeft01, this.ArmLeft02, this.ArmLeft03, this.ArmLeft04, this.ArmLeft05, this.ArmLeft06};
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (f3 <= -180.0f) {
            f3 += 360.0f;
        } else if (f3 >= 180.0f) {
            f3 -= 360.0f;
        }
        GlStateManager.pushMatrix();
        GlStateManager.enableBlend();
        GlStateManager.blendFunc(GlStateManager.SourceFactor.SRC_ALPHA, GlStateManager.DestFactor.ONE_MINUS_SRC_ALPHA);
        GlStateManager.scale(this.scale, this.scale, this.scale);
        GlStateManager.translate(0.0f, this.offsetY, 0.0f);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.BodyMain.render(f5);
        GlStateManager.disableLighting();
        GlStateManager.enableCull();
        OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0f, 240.0f);
        this.GlowBodyMain.render(f5);
        GlStateManager.disableCull();
        GlStateManager.enableLighting();
        GlStateManager.disableBlend();
        GlStateManager.popMatrix();
    }

    @Override
    public void showEquip(IShipEmotion ent) {
    }

    @Override
    public void syncRotationGlowPart() {
        this.GlowBodyMain.rotateAngleX = this.BodyMain.rotateAngleX;
        this.GlowBodyMain.rotateAngleY = this.BodyMain.rotateAngleY;
        this.GlowBodyMain.rotateAngleZ = this.BodyMain.rotateAngleZ;
        this.GlowNeck.rotateAngleX = this.Neck.rotateAngleX;
        this.GlowNeck.rotateAngleY = this.Neck.rotateAngleY;
        this.GlowNeck.rotateAngleZ = this.Neck.rotateAngleZ;
        this.GlowHead.rotateAngleX = this.Head.rotateAngleX;
        this.GlowHead.rotateAngleY = this.Head.rotateAngleY;
        this.GlowHead.rotateAngleZ = this.Head.rotateAngleZ;
    }

    @Override
    public void applyDeadPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        GlStateManager.translate(0.0f, 0.74f, 0.0f);
        this.setFaceHungry(ent);
        this.Head.rotateAngleX = -0.35f;
        this.Head.rotateAngleY = 0.0f;
        this.Head.rotateAngleZ = 0.0f;
        this.BoobL.rotateAngleX = -0.76f;
        this.BoobR.rotateAngleX = -0.76f;
        this.Ahoke.rotateAngleY = 0.6f;
        this.BodyMain.rotateAngleX = 1.4835f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = 1.0472f;
        this.Butt.offsetZ = -0.05f;
        this.Skirt.offsetY = -0.1f;
        this.Hair01.rotateAngleX = 0.35f;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = 0.2f;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -0.3f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.HairL01.rotateAngleX = -0.14f;
        this.HairL02.rotateAngleX = 0.17f;
        this.HairR01.rotateAngleX = -0.14f;
        this.HairR02.rotateAngleX = 0.17f;
        this.ArmLeft01.rotateAngleX = -2.967f;
        this.ArmLeft01.rotateAngleY = -0.6981f;
        this.ArmLeft01.rotateAngleZ = 0.08f;
        this.ArmLeft03.rotateAngleX = 0.0f;
        this.ArmLeft03.rotateAngleY = 0.35f;
        this.ArmLeft03.rotateAngleZ = 0.0f;
        this.ArmLeft06.rotateAngleX = 0.0873f;
        this.ArmLeft06.rotateAngleY = 0.14f;
        this.ArmLeft06.rotateAngleZ = 0.26f;
        this.ArmLeft07.rotateAngleX = -0.2618f;
        this.ArmRight01.rotateAngleX = -2.967f;
        this.ArmRight01.rotateAngleY = 0.6981f;
        this.ArmRight01.rotateAngleZ = -0.08f;
        this.ArmRight03.rotateAngleX = 0.0f;
        this.ArmRight03.rotateAngleY = -0.35f;
        this.ArmRight03.rotateAngleZ = 0.0f;
        this.ArmRight06.rotateAngleZ = -0.26f;
        this.ArmRight07.rotateAngleX = -0.2618f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleX = -1.7f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.05f;
        this.LegLeft02.rotateAngleX = 0.7f;
        this.LegRight01.rotateAngleX = -1.7f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.05f;
        this.LegRight02.rotateAngleX = 0.7f;
    }

    @Override
    public void applyNormalPose(float f, float f1, float f2, float f3, float f4, IShipEmotion ent) {
        float f6;
        if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
            BasicEntityMount mount = (BasicEntityMount)((Entity)ent).getRidingEntity();
            f1 = mount.prevLimbSwingAmount + (mount.limbSwingAmount - mount.prevLimbSwingAmount) * (f2 - (int)f2);
            f = mount.limbSwing - mount.limbSwingAmount * (1.0f - (f2 - (int)f2));
            if (f1 > 1.0f) {
                f1 = 1.0f;
            }
        }
        float angleX = MathHelper.cos(f2 * 0.08f);
        float angleX1 = MathHelper.cos(f2 * 0.08f + 0.3f + f * 0.5f);
        float angleX2 = MathHelper.cos(f2 * 0.08f + 0.6f + f * 0.5f);
        float angleAdd1 = MathHelper.cos(f * 0.7f) * f1 * 0.7f;
        float angleAdd2 = MathHelper.cos(f * 0.7f + (float)Math.PI) * f1 * 0.7f;
        float addk1;
        float addk2;
        float headX;
        float headZ;
        if (ent.getShipDepth(0) > 0.0 || ent.getShipDepth(1) > 0.0) {
            GlStateManager.translate(0.0f, angleX * 0.05f + 0.025f, 0.0f);
        }
        addk1 = angleAdd1 * 0.6f - 0.21f;
        addk2 = angleAdd2 * 0.6f - 0.21f;
        this.Head.rotateAngleX = f4 * 0.014f;
        this.Head.rotateAngleY = f3 * 0.01f;
        this.Head.rotateAngleZ = 0.0f;
        headX = this.Head.rotateAngleX * -0.5f;
        this.BoobL.rotateAngleX = angleX * 0.08f - 0.76f;
        this.BoobR.rotateAngleX = angleX * 0.08f - 0.76f;
        this.Ahoke.rotateAngleY = angleX * 0.15f + 0.6f;
        this.BodyMain.rotateAngleX = -0.1047f;
        this.BodyMain.rotateAngleY = 0.0f;
        this.BodyMain.rotateAngleZ = 0.0f;
        this.Butt.rotateAngleX = 0.3142f;
        this.Butt.offsetZ = 0.0f;
        this.Skirt.offsetY = 0.0f;
        this.Hair01.rotateAngleX = angleX * 0.03f + 0.21f + headX;
        this.Hair01.rotateAngleZ = 0.0f;
        this.Hair02.rotateAngleX = -angleX1 * 0.04f - 0.08f + headX;
        this.Hair02.rotateAngleZ = 0.0f;
        this.Hair03.rotateAngleX = -angleX2 * 0.07f - 0.14f;
        this.Hair03.rotateAngleZ = 0.0f;
        this.ArmLeft01.rotateAngleX = -0.2618f;
        this.ArmLeft01.rotateAngleY = 0.7f;
        this.ArmLeft01.rotateAngleZ = 0.0f;
        this.ArmLeft03.rotateAngleX = 0.0f;
        this.ArmLeft03.rotateAngleY = 0.35f;
        this.ArmLeft03.rotateAngleZ = 0.0f;
        this.ArmLeft06.rotateAngleX = 0.0873f;
        this.ArmLeft06.rotateAngleY = 0.14f;
        this.ArmLeft06.rotateAngleZ = angleX * 0.1f + 0.26f;
        this.ArmLeft07.rotateAngleX = -0.2618f;
        this.ArmRight01.rotateAngleX = -0.2618f;
        this.ArmRight01.rotateAngleY = -0.7f;
        this.ArmRight01.rotateAngleZ = 0.0f;
        this.ArmRight03.rotateAngleX = 0.0f;
        this.ArmRight03.rotateAngleY = -0.35f;
        this.ArmRight03.rotateAngleZ = 0.0f;
        this.ArmRight06.rotateAngleZ = -angleX * 0.1f - 0.26f;
        this.ArmRight07.rotateAngleX = -0.2618f;
        this.LegLeft02.offsetZ = 0.0f;
        this.LegRight02.offsetZ = 0.0f;
        this.LegLeft01.rotateAngleY = 0.0f;
        this.LegLeft01.rotateAngleZ = 0.05f;
        this.LegLeft02.rotateAngleX = 0.0f;
        this.LegRight01.rotateAngleY = 0.0f;
        this.LegRight01.rotateAngleZ = -0.05f;
        this.LegRight02.rotateAngleX = 0.0f;
        if (ent.getIsSprinting() || f1 > 0.9f) {
            this.Hair01.rotateAngleX += 0.09f;
            this.Hair02.rotateAngleX += 0.43f;
            this.Hair03.rotateAngleX += 0.49f;
            this.BoobL.rotateAngleX = angleAdd2 * 0.1f - 0.83f;
            this.BoobR.rotateAngleX = angleAdd1 * 0.1f - 0.83f;
            this.ArmLeft01.rotateAngleX = angleAdd2 * 0.8f + 0.1745f;
            this.ArmLeft01.rotateAngleY = 0.0f;
            this.ArmLeft01.rotateAngleZ = -0.35f;
            this.ArmLeft03.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleX = angleAdd1 * 0.8f + 0.1745f;
            this.ArmRight01.rotateAngleY = 0.0f;
            this.ArmRight01.rotateAngleZ = 0.35f;
            this.ArmRight03.rotateAngleY = 0.0f;
        }
        this.Head.rotateAngleZ = EmotionHelper.getHeadTiltAngle(ent, f2);
        this.Hair01.rotateAngleZ = headZ = this.Head.rotateAngleZ * -0.5f;
        this.Hair02.rotateAngleZ = headZ;
        this.HairL01.rotateAngleZ = headZ - 0.14f;
        this.HairL02.rotateAngleZ = headZ + 0.087f;
        this.HairR01.rotateAngleZ = headZ + 0.14f;
        this.HairR02.rotateAngleZ = headZ - 0.052f;
        if (ent.getIsSneaking()) {
            GlStateManager.translate(0.0f, 0.1f, 0.0f);
            this.Head.rotateAngleX -= 0.6283f;
            this.BodyMain.rotateAngleX = 0.8727f;
            this.ArmLeft01.rotateAngleX = -0.61f;
            this.ArmLeft01.rotateAngleY = 0.35f;
            this.ArmLeft01.rotateAngleZ = -0.14f;
            this.ArmLeft03.rotateAngleY = 0.7f;
            this.ArmLeft06.rotateAngleZ = -0.35f;
            this.ArmRight01.rotateAngleX = -0.61f;
            this.ArmRight01.rotateAngleY = -0.35f;
            this.ArmRight01.rotateAngleZ = 0.14f;
            this.ArmRight03.rotateAngleY = -0.7f;
            this.ArmRight06.rotateAngleZ = 0.35f;
            addk1 -= 1.0f;
            addk2 -= 1.0f;
            this.Hair01.rotateAngleX += 0.37f;
            this.Hair02.rotateAngleX += 0.23f;
            this.Hair03.rotateAngleX -= 0.1f;
        }
        if (ent.getIsSitting() && !ent.getIsRiding()) {
            if (ent.getStateEmotion(1) == 4) {
                this.setFace(2);
                GlStateManager.translate(0.0f, 0.57f, 0.0f);
                this.Head.rotateAngleX = this.Head.rotateAngleX * 0.5f + 0.55f;
                this.Head.rotateAngleY = this.Head.rotateAngleY * 0.5f - 0.2f;
                this.BodyMain.rotateAngleX = -0.61f;
                this.BodyMain.rotateAngleY = -0.2618f;
                this.BodyMain.rotateAngleZ = -0.5236f;
                this.ArmLeft01.rotateAngleX = 1.3f;
                this.ArmLeft01.rotateAngleY = 0.7f;
                this.ArmLeft01.rotateAngleZ = -0.1745f;
                this.ArmLeft03.rotateAngleX = -2.53f;
                this.ArmLeft03.rotateAngleY = -0.7f;
                this.ArmLeft06.rotateAngleX = -0.5236f;
                this.ArmLeft06.rotateAngleY = -0.5236f;
                this.ArmLeft06.rotateAngleZ = 0.7f;
                this.ArmRight01.rotateAngleX = 0.7f;
                this.ArmRight01.rotateAngleY = 0.0f;
                this.ArmRight01.rotateAngleZ = 0.5236f;
                this.ArmRight03.rotateAngleX = -1.57f;
                this.ArmRight03.rotateAngleY = 0.14f;
                this.ArmRight03.rotateAngleZ = 1.7453f;
                this.ArmRight06.rotateAngleZ = -0.5236f;
                addk1 = -1.05f;
                addk2 = -1.31f;
                this.LegLeft01.rotateAngleZ = -0.5236f;
                this.LegLeft02.rotateAngleX = 1.05f;
                this.LegRight01.rotateAngleY = -0.4363f;
                this.LegRight02.rotateAngleX = 0.7f;
                this.Hair01.rotateAngleX -= 0.12f;
                this.Hair01.rotateAngleZ = -0.09f;
                this.Hair02.rotateAngleX -= 0.18f;
                this.Hair02.rotateAngleZ = -0.26f;
                this.Hair03.rotateAngleX -= 0.21f;
                this.Hair03.rotateAngleZ = -0.35f;
            } else {
                GlStateManager.translate(0.0f, 0.4f, 0.0f);
                this.Head.rotateAngleX -= 0.25f;
                this.ArmLeft01.rotateAngleX = -0.44f;
                this.ArmLeft01.rotateAngleY = 0.44f;
                this.ArmLeft01.rotateAngleZ = 0.0f;
                this.ArmLeft03.rotateAngleY = 0.87f;
                this.ArmLeft06.rotateAngleZ = 0.1f;
                this.ArmRight01.rotateAngleX = -0.44f;
                this.ArmRight01.rotateAngleY = -0.44f;
                this.ArmRight01.rotateAngleZ = 0.0f;
                this.ArmRight03.rotateAngleY = -0.87f;
                this.ArmRight06.rotateAngleZ = -0.1f;
                addk1 = -1.2217f;
                addk2 = -1.2217f;
                this.LegLeft02.offsetZ = 0.37f;
                this.LegRight02.offsetZ = 0.37f;
                this.LegLeft01.rotateAngleY = 0.14f;
                this.LegRight01.rotateAngleY = -0.14f;
                this.LegLeft02.rotateAngleX = 2.53f;
                this.LegRight02.rotateAngleX = 2.53f;
            }
        }
        if (ent.getIsRiding()) {
            if (((Entity)ent).getRidingEntity() instanceof BasicEntityMount) {
                if (ent.getIsSitting()) {
                    if (ent.getStateEmotion(1) == 4) {
                        this.setFace(2);
                        GlStateManager.translate(0.0f, 0.57f, 0.0f);
                        this.Head.rotateAngleX = this.Head.rotateAngleX * 0.5f + 0.55f;
                        this.Head.rotateAngleY = this.Head.rotateAngleY * 0.5f - 0.2f;
                        this.BodyMain.rotateAngleX = -0.61f;
                        this.BodyMain.rotateAngleY = -0.2618f;
                        this.BodyMain.rotateAngleZ = -0.5236f;
                        this.ArmLeft01.rotateAngleX = 1.3f;
                        this.ArmLeft01.rotateAngleY = 0.7f;
                        this.ArmLeft01.rotateAngleZ = -0.1745f;
                        this.ArmLeft03.rotateAngleX = -2.53f;
                        this.ArmLeft03.rotateAngleY = -0.7f;
                        this.ArmLeft06.rotateAngleX = -0.5236f;
                        this.ArmLeft06.rotateAngleY = -0.5236f;
                        this.ArmLeft06.rotateAngleZ = 0.7f;
                        this.ArmRight01.rotateAngleX = 0.7f;
                        this.ArmRight01.rotateAngleY = 0.0f;
                        this.ArmRight01.rotateAngleZ = 0.5236f;
                        this.ArmRight03.rotateAngleX = -1.57f;
                        this.ArmRight03.rotateAngleY = 0.14f;
                        this.ArmRight03.rotateAngleZ = 1.7453f;
                        this.ArmRight06.rotateAngleZ = -0.5236f;
                        addk1 = -1.05f;
                        addk2 = -1.31f;
                        this.LegLeft01.rotateAngleZ = -0.5236f;
                        this.LegLeft02.rotateAngleX = 1.05f;
                        this.LegRight01.rotateAngleY = -0.4363f;
                        this.LegRight02.rotateAngleX = 0.7f;
                        this.Hair01.rotateAngleX -= 0.12f;
                        this.Hair01.rotateAngleZ = -0.09f;
                        this.Hair02.rotateAngleX -= 0.18f;
                        this.Hair02.rotateAngleZ = -0.26f;
                        this.Hair03.rotateAngleX -= 0.21f;
                        this.Hair03.rotateAngleZ = -0.35f;
                    } else {
                        GlStateManager.translate(0.0f, 0.41f, 0.0f);
                        this.Head.rotateAngleX -= 0.35f;
                        this.Hair01.rotateAngleX += 0.35f;
                        this.ArmLeft01.rotateAngleX = 0.2f;
                        this.ArmLeft01.rotateAngleY = 0.0f;
                        this.ArmLeft01.rotateAngleZ = -1.1f;
                        this.ArmLeft03.rotateAngleY = 0.0f;
                        this.ArmLeft03.rotateAngleZ = -0.4f;
                        this.ArmRight01.rotateAngleX = 0.2f;
                        this.ArmRight01.rotateAngleY = 0.0f;
                        this.ArmRight01.rotateAngleZ = 1.1f;
                        this.ArmRight03.rotateAngleZ = 0.4f;
                        addk1 = -1.2217f;
                        addk2 = -1.2217f;
                        this.LegLeft02.offsetZ = 0.37f;
                        this.LegRight02.offsetZ = 0.37f;
                        this.LegLeft01.rotateAngleY = 0.14f;
                        this.LegRight01.rotateAngleY = -0.14f;
                        this.LegLeft02.rotateAngleX = 2.53f;
                        this.LegRight02.rotateAngleX = 2.53f;
                    }
                } else {
                    this.Hair01.rotateAngleX += 0.35f;
                    this.ArmLeft01.rotateAngleX = 0.5f;
                    this.ArmLeft01.rotateAngleY = 0.0f;
                    this.ArmLeft01.rotateAngleZ = -0.7f;
                    this.ArmLeft03.rotateAngleX = -0.5f;
                    this.ArmLeft03.rotateAngleY = 0.0f;
                    this.ArmLeft03.rotateAngleZ = -0.4f;
                    this.ArmLeft06.rotateAngleZ = 0.4f;
                    this.ArmLeft07.rotateAngleX = -1.2f;
                    this.ArmRight01.rotateAngleX = 0.5f;
                    this.ArmRight01.rotateAngleY = 0.0f;
                    this.ArmRight01.rotateAngleZ = 0.7f;
                    this.ArmRight03.rotateAngleX = -0.5f;
                    this.ArmRight03.rotateAngleY = 0.0f;
                    this.ArmRight03.rotateAngleZ = 0.4f;
                    this.ArmRight06.rotateAngleZ = -0.4f;
                    this.ArmRight07.rotateAngleX = -1.2f;
                }
            } else if (ent.getStateEmotion(1) == 4) {
                this.setFace(2);
                GlStateManager.translate(0.0f, 0.37f, 0.0f);
                this.Head.rotateAngleX = this.Head.rotateAngleX * 0.5f + 0.55f;
                this.Head.rotateAngleY = this.Head.rotateAngleY * 0.5f - 0.2f;
                this.BodyMain.rotateAngleX = -0.61f;
                this.BodyMain.rotateAngleY = -0.2618f;
                this.BodyMain.rotateAngleZ = -0.5236f;
                this.ArmLeft01.rotateAngleX = 1.3f;
                this.ArmLeft01.rotateAngleY = 0.7f;
                this.ArmLeft01.rotateAngleZ = -0.1745f;
                this.ArmLeft03.rotateAngleX = -2.53f;
                this.ArmLeft03.rotateAngleY = -0.7f;
                this.ArmLeft06.rotateAngleX = -0.5236f;
                this.ArmLeft06.rotateAngleY = -0.5236f;
                this.ArmLeft06.rotateAngleZ = 0.7f;
                this.ArmRight01.rotateAngleX = 0.7f;
                this.ArmRight01.rotateAngleY = 0.0f;
                this.ArmRight01.rotateAngleZ = 0.5236f;
                this.ArmRight03.rotateAngleX = -1.57f;
                this.ArmRight03.rotateAngleY = 0.14f;
                this.ArmRight03.rotateAngleZ = 1.7453f;
                this.ArmRight06.rotateAngleZ = -0.5236f;
                addk1 = -1.05f;
                addk2 = -1.31f;
                this.LegLeft01.rotateAngleZ = -0.5236f;
                this.LegLeft02.rotateAngleX = 1.05f;
                this.LegRight01.rotateAngleY = -0.4363f;
                this.LegRight02.rotateAngleX = 0.7f;
                this.Hair01.rotateAngleX -= 0.12f;
                this.Hair01.rotateAngleZ = -0.09f;
                this.Hair02.rotateAngleX -= 0.18f;
                this.Hair02.rotateAngleZ = -0.26f;
                this.Hair03.rotateAngleX -= 0.21f;
                this.Hair03.rotateAngleZ = -0.35f;
            } else {
                GlStateManager.translate(0.0f, 0.5f, 0.0f);
                this.ArmLeft01.rotateAngleX = -0.44f;
                this.ArmLeft01.rotateAngleY = 0.44f;
                this.ArmLeft01.rotateAngleZ = 0.0f;
                this.ArmLeft03.rotateAngleY = 0.87f;
                this.ArmLeft06.rotateAngleZ = 0.1f;
                this.ArmRight01.rotateAngleX = -0.44f;
                this.ArmRight01.rotateAngleY = -0.44f;
                this.ArmRight01.rotateAngleZ = 0.0f;
                this.ArmRight03.rotateAngleY = -0.87f;
                this.ArmRight06.rotateAngleZ = -0.1f;
                addk1 = -1.2217f;
                addk2 = -1.2217f;
                this.LegLeft02.offsetZ = 0.37f;
                this.LegRight02.offsetZ = 0.37f;
                this.LegLeft01.rotateAngleY = 0.14f;
                this.LegRight01.rotateAngleY = -0.14f;
                this.LegLeft02.rotateAngleX = 2.53f;
                this.LegRight02.rotateAngleX = 2.53f;
            }
        }
        if (ent.getAttackTick() > 0) {
            if (ent.getAttackTick() > 25) {
                this.setFace(3);
            }
            this.ArmLeft01.rotateAngleX = -1.4f;
            this.ArmLeft01.rotateAngleY = -0.14f;
            this.ArmLeft01.rotateAngleZ = 0.0f;
            this.ArmLeft06.rotateAngleZ = -0.96f;
            this.ArmRight01.rotateAngleX = -1.4f;
            this.ArmRight01.rotateAngleY = 0.14f;
            this.ArmRight01.rotateAngleZ = 0.0f;
            this.ArmRight06.rotateAngleZ = 0.96f;
        }
        if ((f6 = ent.getSwingTime(f2 - (int)f2)) != 0.0f) {
            float f7 = MathHelper.sin(f6 * f6 * (float)Math.PI);
            float f8 = MathHelper.sin(MathHelper.sqrt(f6) * (float)Math.PI);
            this.ArmRight01.rotateAngleX += -f8 * 80.0f * ((float)Math.PI / 180);
            this.ArmRight01.rotateAngleY += -f7 * 20.0f * ((float)Math.PI / 180) + 1.0f;
            this.ArmRight01.rotateAngleZ += -f8 * 20.0f * ((float)Math.PI / 180);
        }
        if (ent.getStateEmotion(6) == 1) {
            this.Head.rotateAngleX += 0.2f;
        }
        headX = this.Head.rotateAngleX * -0.5f;
        this.HairL01.rotateAngleX = angleX * 0.02f + headX - 0.14f;
        this.HairL02.rotateAngleX = -angleX1 * 0.04f + headX + 0.17f;
        this.HairR01.rotateAngleX = angleX * 0.02f + headX - 0.14f;
        this.HairR02.rotateAngleX = -angleX1 * 0.04f + headX + 0.17f;
        this.LegLeft01.rotateAngleX = addk1;
        this.LegRight01.rotateAngleX = addk2;
    }
}
